### ISSUE TITLE
ReferenceError: Can't find variable: fetch

### ISSUE THREAD

**Issue by gl2748** [thoughtbot/capybara-webkit#1007]
I am trying to use this...
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

Getting this from our specs.

```
ReferenceError: Can't find variable: fetch
```

**Comment by twalpole** [comment]
`fetch` is a relatively new browser feature and is implemented in the versions of QtWebkit capybara-webkit supports.  If you want to use it with capybara-webkit you will need to polyfill the functionality.

**Comment by raldred** [comment]
I'm using a polyfill (whatwg-fetch) having an issue with requests in a react app.
Payload seems to get dropped from PATCH requests.

Works fine if I use poltergeist, so I suspect qt webkit at fault maybe it doesn't support PATCH?
using qt5.5 OSX.
