### ISSUE TITLE
Gem working without qt?

### ISSUE THREAD

**Issue by jevin** [thoughtbot/capybara-webkit#1008]
I just installed this gem on a new laptop and everything seems to be working fine without qt. I'm on Sierra 10.12.5. How is that even possible?

FYI, my driver is set to webkit:

```ruby
Capybara.javascript_driver = :webkit
```

**Comment by mhoran** [comment]
You must have Qt installed on your system somehow. What does `qmake -v` report?

The gem would not successfully install if Qt were not installed, as the gem must compile against the Qt libraries.

**Comment by jevin** [comment]
Oh you're right!
```
$ qmake -v
QMake version 3.0
Using Qt version 5.5.1 in /usr/local/Cellar/qt@5.5/5.5.1_1/lib
```

All this time I was checking with `brew info qt`. Of course it said the latest version was not installed.

Thanks a lot @mhoran!
