### ISSUE TITLE
How to set javascript driver to Capybara webkit

### ISSUE THREAD

**Issue by lokeshh** [thoughtbot/capybara-webkit#1014]
In the README it is mentioned that following line has to be added:
```
Capybara.javascript_driver = :webkit
```
Where to add this line?

**Comment by jferris** [comment]
That depends on which framework you're using to test. If you're using a recent version of RSpec, you probably want to put it in `spec/rails_helper.rb`. Check out the [Capybara setup guide](https://github.com/teamcapybara/capybara#setup) for more information.
