### ISSUE TITLE
Launching specs with docker-compose

### ISSUE THREAD

**Issue by RemyMaucourt** [thoughtbot/capybara-webkit#1019]
I can't launch rspec with docker-compose since I installed capybara-webkit.

This next command just hold up for hours, doing nothing:

`$ docker-compose run web xvfb-run -a bundle exec rspec`

Running it with the --verbose option don't give much more information.

It's working if I launch a bash terminal in my container and fire the command from there. `$ docker-compose run web bash` then `$ xvfb-run -a bundle exec rspec spec` launch the specs correctly.

Is there a special config for docker-compose I should be aware of?

The Dockerfile:

```
FROM ruby:2.4.1

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  xvfb \
  qt5-default \
  libqt5webkit5-dev \
  gstreamer1.0-plugins-base \
  gstreamer1.0-tools \
  gstreamer1.0-x

RUN mkdir /app_dir
WORKDIR /app_dir

ADD Gemfile* /app_dir/

RUN bundle install

COPY . .
```

I give more details on this [Stackoverflow post](https://stackoverflow.com/questions/45510512/launching-capybara-webkit-on-a-dockerized-rails-5-app)

**Comment by ryansch** [comment]
I didn't have much luck with xvfb-run so I just put the following into my entrypoint:
```sh
    echo 'Starting Xvfb'
    Xvfb :99 -screen 0 1280x1024x24 &
    export DISPLAY=:99
```

**Comment by jferris** [comment]
Could you run something else within `xvfb-run` to figure out if it's something capybara-webkit is doing? For example: `docker-compose run web xvfb-run -a bash`

**Comment by RemyMaucourt** [comment]
Well, it seems to be a docker-compose / xvfb problem: `docker-compose run web xvfb-run -a bash` is staying on hold too.

**Comment by jferris** [comment]
I'm going to close this issue, as it doesn't seem like a bug in capybara-webkit, but feel free to continue commenting.

If you wrap the xvfb-run invocation in a shell, does that have any effect?

`docker-compose run bash -c 'xvfb-run -a rspec'`

I don't know what's causing the hang, but my best guesses are something to do with 1) the default shell 2) stdin 3) interactive vs non-interactive shell invocations.

**Comment by RemyMaucourt** [comment]
Thank you for the courtesy and the reactivity.

`docker-compose run web bash -c 'xvfb-run -a rspec' ` stays on hold too. 

I like the 'non-interactive shell' lead, I keep investigating and will keep you informed.

**Comment by asafigan** [comment]
I'm having the exact same problem. If you find a fix or any more information could you pass it on?

**Comment by RemyMaucourt** [comment]
I endend up writing another [Stackoverflow post](https://stackoverflow.com/questions/45964813/docker-compose-and-xvfb-incompatibility)
