### ISSUE TITLE
Could not resolve SDK Path for 'macosx' white installing capybara-webkit

### ISSUE THREAD

**Issue by vilola** [thoughtbot/capybara-webkit#1022]
I am trying to install capybara-webkit gem on my macbook (sierra 10.12.6) but I still have some problems. I installed Xcode, gt, I tried almost every solution but I think I made it even worse :(

Now the error is "Could not resolve SDK Path for 'macosx'". Full message is on image.

Can someone help me please? :-/

<img width="639" alt="snimek obrazovky 2017-08-19 v 11 14 46" src="https://user-images.githubusercontent.com/26657627/29486207-cbbc3a08-84e0-11e7-9d53-e36b1b6ee9bb.png">

**Comment by MarcoHarris** [comment]
This might help:

https://github.com/therecipe/qt/issues/327
https://stackoverflow.com/questions/41513456/qt-5-7-xcode-8-1-os-x-el-captain-could-not-resolve-sdk-path-for-macosx

**Comment by wtfiwtz** [comment]
Looks like you need to install `xcode` on Mac OS X
