### ISSUE TITLE
Dependency on Capybara 2.13.x

### ISSUE THREAD

**Issue by stratigos** [thoughtbot/capybara-webkit#1023]
I would like to keep using `capybara-webkit`, and also use the latest minor release for `capybara`. 

`capybara` is now at [2.15.1](https://rubygems.org/gems/capybara/versions/2.15.1). `capybara-webkit` is dependent on _2.13.x_ : 

```
Bundler could not find compatible versions for gem "capybara":
  In Gemfile:
    capybara (~> 2.15.1)

    capybara-webkit (~> 1.14.0) was resolved to 1.14.0, which depends on
      capybara (< 2.14.0, >= 2.3.0)
```

Is there a way I can leverage something > 2.14.0, or plans for a new release to update to the latest `capybara` minor version? Thanks!

**Comment by mikegee** [comment]
I think https://github.com/thoughtbot/capybara-webkit/pull/1000 resolves this for you, but there hasn't been another release since then.

**Comment by andy4thehuynh** [comment]
#1000 doesn't have instructions how to install.  Still having issues with this.

**Comment by stratigos** [comment]
Thanks @mikegee, glad to know theres lots of traction on it.

**Comment by twalpole** [comment]
You can use the current master branch with the latest Capybara

**Comment by bmulholland** [comment]
@twalpole Am I reading correctly that the fix was merged in May? When will a new version be released?

**Comment by twalpole** [comment]
@bmulholland No clue - I don't do the releases - just code commits -- use the master branch if you want the newest stuff.

**Comment by bmulholland** [comment]
@twalpole I've tried master and am hitting crashes of Capybara Webkit. Sadly it doesn't seem like there's a viable way to use latest Capybara without migrating off this project.

**Comment by twalpole** [comment]
@bmulholland Thats one option.  A better option would be to report the crashes with reproducible test cases, help get them fixed, and help the whole community.

**Comment by bmulholland** [comment]
@twalpole That's a good idea. I won't have time to do a reproducible test case before the holidays - would a crash log on its own be useful?

We do need to upgrade Capybara in the next few days - is there a stable commit I can use as a temporary measure?
