### ISSUE TITLE
EADDRNOTAVAIL - port issues when using Spork

### ISSUE THREAD

**Issue by nicholaides** [thoughtbot/capybara-webkit#103]
I'm getting this when I upgrade to HEAD:

```
 Errno::EADDRNOTAVAIL:
   Can't assign requested address - connect(2)
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/bundler/gems/capybara-webkit-6b7dbca1c4f6/lib/capybara/driver/webkit/browser.rb:108:in `initialize'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/bundler/gems/capybara-webkit-6b7dbca1c4f6/lib/capybara/driver/webkit/browser.rb:108:in `open'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/bundler/gems/capybara-webkit-6b7dbca1c4f6/lib/capybara/driver/webkit/browser.rb:108:in `attempt_connect'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/bundler/gems/capybara-webkit-6b7dbca1c4f6/lib/capybara/driver/webkit/browser.rb:102:in `block in connect'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/gems/capybara-1.0.0/lib/capybara/util/timeout.rb:13:in `timeout'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/bundler/gems/capybara-webkit-6b7dbca1c4f6/lib/capybara/driver/webkit/browser.rb:101:in `connect'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/bundler/gems/capybara-webkit-6b7dbca1c4f6/lib/capybara/driver/webkit/browser.rb:12:in `initialize'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/bundler/gems/capybara-webkit-6b7dbca1c4f6/lib/capybara/driver/webkit.rb:16:in `new'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/bundler/gems/capybara-webkit-6b7dbca1c4f6/lib/capybara/driver/webkit.rb:16:in `initialize'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/bundler/gems/capybara-webkit-6b7dbca1c4f6/lib/capybara-webkit.rb:5:in `new'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/bundler/gems/capybara-webkit-6b7dbca1c4f6/lib/capybara-webkit.rb:5:in `block in <top (required)>'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/gems/capybara-1.0.0/lib/capybara/session.rb:61:in `call'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/gems/capybara-1.0.0/lib/capybara/session.rb:61:in `driver'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/gems/capybara-1.0.0/lib/capybara/session.rb:157:in `visit'
 # /Users/mikenicholaides/.rvm/gems/ruby-1.9.2-p180@managept/gems/capybara-1.0.0/lib/capybara/dsl.rb:139:in `visit'
 ... 
```

I'm on Leopard with ruby 1.9.2

Also, this commit is the issue: https://github.com/thoughtbot/capybara-webkit/commit/6b7dbca1c4f685f2414cbb7d3c65fcc2fe4b829f

I'm running fine on the previous commit.

**Comment by rajkumarram** [comment]
PS D:\PROJECT DOCUMENTS\IBM-CLOUD-CHEF\projects\chefnew\chef-starter\chef-repo> knife bootstrap 10.68.1.173 -x root -p password --sudo
 -N Node1
Creating new client for Node1
Creating new node for Node1
Connecting to 10.68.1.173
#<Thread:0x000000000a7ff5d0@C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        14: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
        13: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_actions.rb:36:in `block (2 levels) in sessions'
        12: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:in `session'
        11: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488:in `next_session'
        10: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:186:in `new_session'
         9: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
         8: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
         7: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:70:in `initialize'
         6: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:631:in `tcp'
         5: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:227:in `foreach'
         4: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:227:in `each'
         3: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:641:in `block in tcp'
         2: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:137:in `connect'
         1: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:64:in `connect_internal'
C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:64:in `connect': The requested address is not valid in its context. - connect(2) for 10.68.1.173 (Errno::EADDRNOTAVAIL)
ERROR: Errno::EADDRNOTAVAIL: The requested address is not valid in its context. - connect(2) for 10.68.1.173
