### ISSUE TITLE
Cached React files

### ISSUE THREAD

**Issue by bgarr** [thoughtbot/capybara-webkit#1042]
I am currently working on a project that uses xvfb-run with rspec and Capybara::Webkit. When I set Capybara::Webkit's debug config to true, I can see a React component registry error. The components listed do not reflect the contents of my current registration.jsx file, however; they match an earlier version in my git repository, probably 7-8 versions old. The component works fine when I run the app locally. Is there a way I can flush out whatever cache is holding the older version of the file? I should note that this is in a Docker environment.

**Comment by bgarr** [comment]
... I have reinstalled Docker and rebuilt/re-pulled all of my docker container images, and the same problem persists.

**Comment by bgarr** [comment]
... also applying ReactOnRails config, per https://shakacode.gitbooks.io/react-on-rails/content/docs/additional-reading/rspec-configuration.html

**Comment by twalpole** [comment]
I don't see how this could be a capybara-webkit caching issue, since there are no persistent caches between runs.

**Comment by bgarr** [comment]
Turned out it was a proxy issue during Docker build, preventing yarn from loading new libraries and therefor Rails from picking up a revised webpack-bundle.js.
