### ISSUE TITLE
Broken Pipe Bug with Capybara-Webkit

### ISSUE THREAD

**Issue by emilyseibert** [thoughtbot/capybara-webkit#1045]
I cannot replicate this bug locally, but when running rspec tests through Semaphore this error appears sporadically. I rebuilt my build on Semaphore and then the same error appeared just on a different file. I attached the debug log for one of the times the build failed.

PAGE DRIVER OUTPUT
Capybara: 2.7.1
capybara-webkit: 1.11.1
Qt: 5.5.1
WebKit: 538.1
QtWebKit: 5.5.1

[log0142--9d6f93bf-a086-41f3-bbad-2b3d615decbd.txt](https://github.com/thoughtbot/capybara-webkit/files/1589720/log0142--9d6f93bf-a086-41f3-bbad-2b3d615decbd.txt)

**Comment by twalpole** [comment]
1.11 is approaching 2 years old.  The latest release is 1.14, with the master branch having moved beyond that quite a bit too.  Please try try 1.14 and/or the master branch with your project.

**Comment by emilyseibert** [comment]
We upgraded to 1.14 successfully and that resolved the issue. Thank you!
