### ISSUE TITLE
capybara ~>2.16.1

### ISSUE THREAD

**Issue by lgromanowski** [thoughtbot/capybara-webkit#1046]
Hello,
would you please change runtime dependency for capybara to ~>2.16.1 ?

**Comment by twalpole** [comment]
@lgromanowski Setting the dependency to ~> 2.16.1 would only allow Capybara 2.16.x to be used, which is not desired.  It's currently set to ~>2.3 in the master branch which will allow use with any 2.x Capybara >= 2.3.0 .  The currently released capybara-webkit gem has the Capybara versions locked to a lower version but you can always specify to use the master branch in your project if you need to use current Capybara releases.

**Comment by lgromanowski** [comment]
Ok, thank you for response.
