### ISSUE TITLE
Release a new version of capybara-webkit

### ISSUE THREAD

**Issue by jamesRaybould** [thoughtbot/capybara-webkit#1047]
Hello,

Would it please be possible to release the latest version of master to RubyGems?

**Comment by twalpole** [comment]
@jferris @mhoran  Quite a few people have recently had issues where bundler has been selecting capybara-webkit 1.1.0 to use with the latest Capybara release which of course causes all sorts of issues.  Would it be possible for you to release a `1.15.0`  from master in the near future?

**Comment by jferris** [comment]
I updated the changelog, updated the version, tagged, and relased v1.15: https://rubygems.org/gems/capybara-webkit/versions/1.15.0
