### ISSUE TITLE
I am getting error when bootstrap from Window to Linux machine

### ISSUE THREAD

**Issue by rajkumarram** [thoughtbot/capybara-webkit#1070]
PS D:\PROJECT DOCUMENTS\IBM-CLOUD-CHEF\projects\chefnew\chef-starter\chef-repo> knife bootstrap 10.68.x.x -x root -p password --sudo
 -N Node1
Creating new client for Node1
Creating new node for Node1
Connecting to 10.68.x.x
#<Thread:0x000000000a7ff5d0@C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        14: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
        13: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_actions.rb:36:in `block (2 levels) in sessions'
        12: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:in `session'
        11: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488:in `next_session'
        10: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:186:in `new_session'
         9: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
         8: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
         7: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:70:in `initialize'
         6: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:631:in `tcp'
         5: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:227:in `foreach'
         4: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:227:in `each'
         3: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:641:in `block in tcp'
         2: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:137:in `connect'
         1: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:64:in `connect_internal'
C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:64:in `connect': The requested address is not valid in its context. - connect(2) for 10.68.1.173 (Errno::EADDRNOTAVAIL)
ERROR: Errno::EADDRNOTAVAIL: The requested address is not valid in its context. - connect(2) for 10.68.x.x

**Comment by jferris** [comment]
Looking at your backtrace, it doesn't appear as though capbyara-webkit is involved. Are you trying to run tests using capybara-webkit?

This doesn't look like a bug, so I'm going to close this issue. However, you should feel free to keep commenting if you'd like more help.
