### ISSUE TITLE
fatal: reference is not a tree: 9ba3d6ef8891e5c15dbdc9333f857b13711d4e97

### ISSUE THREAD

**Issue by OlegTurbal** [thoughtbot/capybara-webkit#1076]
For brand new brew installation when you try:
git checkout 9ba3d6ef8891e5c15dbdc9333f857b13711d4e97 Formula/qt@5.5.rb 
fatal: reference is not a tree: 9ba3d6ef8891e5c15dbdc9333f857b13711d4e97

Can be fixed in this way:

1) cd $( brew --prefix )/Homebrew/Library/Taps/homebrew/
2) rm -rf homebrew-core
3) git clone https://github.com/Homebrew/homebrew-core.git
4) cd homebrew-core
5) git checkout 9ba3d6ef8891e5c15dbdc9333f857b13711d4e97 Formula/qt@5.5.rb

**Comment by OlegTurbal** [comment]
or 
cd $( brew --prefix )/Homebrew/Library/Taps/homebrew/homebrew-core
git -C "$(brew --repo homebrew/core)" fetch --unshallow

**Comment by jferris** [comment]
I think you're referring to instructions here: https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#homebrew

If that's the case, you can edit the wiki here: https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit/_edit

The wiki is community managed and editable.

This doesn't appear to be a bug in capybara-webkit, so I'm going to close this issue, but you can still comment and ask questions here.
