### ISSUE TITLE
Be sure to terminate webkit_server cleanly

### ISSUE THREAD

**Issue by yfeldblum** [thoughtbot/capybara-webkit#147]
The Capybara-Webkit driver should be sure to terminate the webkit_server process cleanly, even in the event that the cucumber process is forcefully killed. This can be done, for example, by starting another watcher process which polls the state of the cucumber process or waits on a read pipe from the cucumber process, and which then kills the webkit_server if it is still alive.

**Comment by dannote** [comment]
I'm facing the same issue. I've tried to use Capybara-Webkit within a Sidekiq worker and it seems the `Connection` object is not released. https://github.com/mperham/sidekiq/issues/1100 seems to be the cause. Is there a proper way to terminate `webkit_server` by hand?

**Comment by mhoran** [comment]
We don't expose a method for killing the `webkit_server` process, as such usage is not a supported use case of capybara-webkit. An (unsupported) example of how to add a `#quit` method to the `Connection` object can be found in [this thread](https://github.com/thoughtbot/capybara-webkit/issues/802#issuecomment-116195006).
