### ISSUE TITLE
Error installing capybara webkit on Windows 7 (64-bit)

### ISSUE THREAD

**Issue by colin-jack** [thoughtbot/capybara-webkit#148]
I think this is ultimately a duplicate of https://github.com/thoughtbot/capybara-webkit/issues/72 but I do want to use capybara-webkit and get the same issue on Windows 7 64-bit. I do have QT (hopefully currently) installed and in my path. 

The error I'm getting starts with:

"Installing capybara-webkit (0.6.1) with native extensions C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:552:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

```
    C:/Ruby192/bin/ruby.exe extconf.rb "
```

Any thoughts on how to proceed?

**Comment by zaagan** [comment]
Here is quick fix that I implemented to solve my problem:

Step 1 : Clone the repo to your local from the master branch.

Step 2 : Open your Gemfile and update the gem configs as follows

`gem "capybara-webkit", path: 'Path-To-The-Plugin-In-Your-Local-Machine\capybara-webkit-master'`

Step 3 : Try running the bundle install and see if works. That's it.
