### ISSUE TITLE
page.evaluate_script throws Capybara::NotSupportedByDriverError

### ISSUE THREAD

**Issue by jc00ke** [thoughtbot/capybara-webkit#153]
Using capybara 1.0.1 & capybara-webkit 0.6.1, I can't evaluate any js. I know this was supported in the past.

``` ruby
  page.evaluate_script("false").should be_false
  # => Capybara::NotSupportedByDriverError
```

```
∴ uname -a
Linux maynard 2.6.38-11-generic #48-Ubuntu SMP Fri Jul 29 19:02:55 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nfriend21** [comment]
:js => true

fixed this for me.

**Comment by schulmanworks** [comment]
@nfriend21 I'm really new to this. Where does :js => true go in your files?

**Comment by twalpole** [comment]
@schulmanworks https://github.com/teamcapybara/capybara#using-capybara-with-rspec

**Comment by nfriend21** [comment]
@schulmanworks - it goes in your describe block, like this:

describe 'Something', :type => :feature, :js => true do
  it 'does something' do
    # code to test something
  end
end
