### ISSUE TITLE
Add driver support for http verbs get, post, put, delete

### ISSUE THREAD

**Issue by joshuaclayton** [thoughtbot/capybara-webkit#180]
`Rack::Test` supports sending requests with params or a request body to specific urls and updates `page` accordingly. It'd be nice if capybara-webkit could support this as well.

**Comment by Smarre** [comment]
+1 ...

**Comment by michaelmagistro** [comment]
+1 this would be great

**Comment by jferris** [comment]
We've decided not to support this unless Capybara decides to make it part of their public API. We're trying to limit the number of unofficial methods we support, and this is on case where Capybara has taken a clear design stance.

I'm going to lock this thread to prevent it from being revived again. If you feel strongly that directly performing web requests is a necessary tool, please bring this up with the Capybara team.
