### ISSUE TITLE
Not following javascript redirect using window.location.href

### ISSUE THREAD

**Issue by gavinhughes** [thoughtbot/capybara-webkit#207]
I have a javascript redirects in my app like this: `window.location.href = 'http://somewhere.com'`.  They're not being following.  Is this a bug?

**Comment by dustinbrownman** [comment]
For what it's worth, I ended up using `page.evaluate_script('window.location.reload()')` in order to solve this issue. Feels like a hack, but from what I can tell, the headless browser won't auto-reload on location change the way normal browser might.

**Comment by h1u2i3** [comment]
I have the same problem, and when I do the same with poltergeist, the test past. May be you guys should try it.

**Comment by nav0285** [comment]
Even i'm facing the same issue. Did anyone find the solution for this?

**Comment by lukeaus** [comment]
I also have this problem.

**Comment by twalpole** [comment]
@lukeaus This issue was closed years ago and the last comment was almost a year ago.

Here's a gist showing that when `window.location.href` is updated the current url is updated as is the page content.   https://gist.github.com/twalpole/7287b8d2e9b2ba6287c93df519e90765

If you can produce a short self-contained example that reproduces your problem then please file a new issue with it - otherwise stating "I also have this problem" on long closed issues really isn't getting to get you much help.

**Comment by lukeaus** [comment]
@twalpole Apologies for the poor post. My problem was related to this code but on further investigation is actually a browser compatibility issue. Sorry to inconvenience you.

**Comment by Kosmin** [comment]
Not sure if anyone's still following this thread, but I discovered the following behaviour:
```
# This doesn't work
#############
scenario "test redirect" do
  ...
  submit_form
  other_redirects
  ...
  perform_call_that_redirects_with_location
  expect(page).to have_content('page after redirection with window.location')
end

# This does work
#############
scenario "test redirect" do
  visit some_page_directly
  perform_call_that_redirects_with_location
  expect(page).to have_content('page after redirection with window.location')
end
```

It seems like when I have multiple redirects, before testing the redirection with `window.location`, for some reason Capybara craps out. But if the test only looks at a single redirect, the one from `window.location` then the Capybara returns the expected results.

This works for me so I won't look into it any further, hope it helps someone out there

**Comment by FinnYoung** [comment]
@Kosmin thank you. your idea to visit some page directly saved me with
capybara (2.18.0)
capybara-selenium (0.0.6)
chromedriver-helper (1.2.0)

but i never experienced this issue with
capybara-webkit 1.14.0 or 1.15.0
