### ISSUE TITLE
Show application backtrace on 500

### ISSUE THREAD

**Issue by steve9001** [thoughtbot/capybara-webkit#226]
WIth rspec_rails integration tests, when you use the rack_test driver, an exception in the rails application during a request results in an informative stack trace for the failed scenario. We can't seem to make this happen with capybara-webkit.  

As a partial workaround we remove "js: true" for features to work through 500 errors, and then turn it back on to fix failed assertions, but this is tedious and doesn't work when an ajax request causes an exception.

I'm trying to implement this functionality, starting in browser.rb, but I have no familiarity with capybara or capybara-webkit implementations, so any guidance would be great.

**Comment by stevenspiel** [comment]
Thank you @jferris. I was hitting webmock errors and couldn't find why it wasn't bubbling up.
