### ISSUE TITLE
AJAX POST content-type Warning 

### ISSUE THREAD

**Issue by visoft** [thoughtbot/capybara-webkit#260]
I have a link that does a POST, e.g.

    link_to "Add", my_url(obj), :method => :post, :remote => :true

In my Cucumber output I get the message:

    content-type missing in HTTP POST, defaulting to application/octet-stream

According to [the docs](http://developer.qt.nokia.com/doc/note_revisions/84/125/view), this warning can be muted by setting the following:

    networkRequest.setHeader(QNetworkRequest::ContentTypeHeader, "application/octet-stream");

If you don't want to or can't add it, is there another way to stop this warning from showing up?

Thanks,
-Damien

**Comment by calleerlandsson** [comment]
Since #586 has been merged, can this be closed? This issue seems to refer to suppressing the warnings rather than the `Content-Type` header being set to the wrong thing like stated in #636.

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity. Please re-open it if you're still experiencing these issues.
