### ISSUE TITLE
Intermittent Capybara::TimeoutErrors 

### ISSUE THREAD

**Issue by joshk** [thoughtbot/capybara-webkit#275]
Hey Guys,

On Travis we are seeing intermittent Capybara::TimeoutErrors, switching to Selenium fixes this issue. I would love promote capybara-webkit as a good solution for use on Travis, but this makes it a bit of a blocker.

http://travis-ci.org/#!/joshk/workshop_prep/jobs/680282/L1256

Thanks,

Josh

**Comment by calleerlandsson** [comment]
@jferris Was there any conclusion after looking at the apps?

**Comment by jferris** [comment]
Oops, I forgot about this. When I ran it locally, I didn't see the timeout errors. We haven't had other users reporting this, and this issue is really old (my fault), so I'm going to close this.
