### ISSUE TITLE
Value is not filled right on a masked input (jQuery)

### ISSUE THREAD

**Issue by sobrinho** [thoughtbot/capybara-webkit#303]
Hi,

I will try to explain the problem :)

I use the [jQuery Masked Input](https://github.com/digitalBush/jquery.maskedinput) plugin.

My form looks like that:

``` html
<input data-mask="9999" value="2012">
```

My javascript:

``` javascript
(function ($) {
  $('input[data-mask]').live('focus', function () {
    var input = $(this);

    input.mask(input.attr("data-mask")).trigger('focus.mask');
  });
})(jQuery);
```

But when I try to change the value of input using `fill_in` something wrong happens:

``` ruby
fill_in 'Ano', :with => '2011'
puts page.find_field('Ano')[:value] #=> '2201'
```

Note the input loads with `2012` by default and when I use capybara-webkit to fill, the value result is `2201`.

I'm guessing this way (the brackets are the original value):

```
[2012]
[2]2[01]
[2]20[1]
[2]201
```

Seems like the input starts to be filled on second position.

But, I can't reproduce this behavior in any browser except of the fact I start typing after the first `2`:

```
2[start typing here]012
```

Using the debug version, I guess the relevant part is this:

```
 >> Find
 >> 1
 >> 499
 >> .//*[self::input | self::textarea][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'radio' or ./@type = 'checkbox' or ./@type = 'hidden' or ./@type = 'file')][((./@id = 'Ano' or ./@name = 'Ano') or ./@id = //label[contains(normalize-space(string(.)), 'Ano')]/@for)] | .//label[contains(normalize-space(string(.)), 'Ano')]//.//*[self::input | self::textarea][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'radio' or ./@type = 'checkbox' or ./@type = 'hidden' or ./@type = 'file')]
 << ok
 << 1
 << 1
 >> Node
 >> 2
 >> 10
 >> isAttached
 >> 1
 >> 1
 << ok
 << 4
 << true
 >> Node
 >> 2
 >> 7
 >> visible
 >> 1
 >> 1
 << ok
 << 4
 << true
 >> Node
 >> 2
 >> 10
 >> isAttached
 >> 1
 >> 1
 << ok
 << 4
 << true
 >> Node
 >> 2
 >> 7
 >> visible
 >> 1
 >> 1
 << ok
 << 4
 << true
 >> Node
 >> 2
 >> 10
 >> isAttached
 >> 1
 >> 1
 << ok
 << 4
 << true
 >> Node
 >> 3
 >> 3
 >> set
 >> 1
 >> 1
 >> 4
 >> 2012
 << ok
 << 0
```

I'm guessing it's a fault of masked input implementation but because I can't reproduce that in a browser (including IE) I'm guessing it's a "integration" problem between masked input and capybara-webkit.

Something I can check?

**Comment by plicjo** [comment]
@mtoigo Great solution!

**Comment by omgmakeme** [comment]
@mtoigo Great solution!

**Comment by av-ast** [comment]
+1 for @mtoigo solution!

**Comment by cerdiogenes** [comment]
I used a combination of the solutions and added a blur simulation:

```ruby
def fill_inputmask(location, value)
  find(location).click
  page.execute_script "$('#{location}').val('#{value}');"
  page.find('body').click # simulating blur
end
```

**Comment by repoles** [comment]
I had the same problem here using `capybara 2.6.2`, `selenium-webdriver 2.53.0` and [jQuery Masked Input plugin](https://github.com/digitalBush/jquery.maskedinput).

My workaround was fill in the input twice, first time with a blank value:

```
fill_in '.js-mask-date-field', with: ''
fill_in '.js-mask-date-field', with: '08/04/2016'
```

**Comment by jakeonrails** [comment]
I seem to have found a solution that does not need javascript, borrowing some input from @cerdiogenes:

```ruby
def fill_inputmask(element, value)
  element.click
  element.send_keys(value.to_s)
  page.find('body').click
end
```

Granted, this was on flaky spec - about 1 out of 3 executions would fail with the normal "fill_in". So far I've rerun it about 15 times with no failures.

**Comment by AmitPatel-BoTreeConsulting** [comment]
`pagge.find('body').click` somehow redirecting to other page. Following worked for me


```ruby
def fill_inputmask(location, value)
    find(location).click
    page.execute_script "$('#{location}').val('#{value}');"
    # page.find('body').click # This didn't work
    find(location).send_keys :tab
end

```

**Comment by jakeonrails** [comment]
It could be that you have a link or a button in the center of the `body` element. I'm pretty sure that the `click` method just clicks literally in the exact middle of any element that you call it on, and if there's something sitting on top of it, well... it gets clicked instead!

**Comment by twalpole** [comment]
Technically, `click` finds the position at the middle of the element it's called on, and then checks if clicking on that position would click on that element OR any of that elements descendants.  Since everything on the page is a descendant of body though, it does basically just click in the middle of the page, thereby triggering a click on whatever is there.

**Comment by sobrinho** [comment]
Would make sense for us to click on the top left of the elements instead then?

**Comment by mhoran** [comment]
I believe other drivers also click in the center of the element, and in general that is also what I find myself doing as the user of a Web page. I may have even experimented with other click positions and had found the center of the element to be the most reliable; but I don't recall at this time, it's been a while.

**Comment by jakeonrails** [comment]
Maybe it would make sense for a hack such as this, that relies on a `body` element to be clicked, to add a invisible (at least to a user) 1 pixel element just to receive such clicks.

As a side-note, there have been a few strange cases that I've seen where a link element has a hard time receiving a click, b/c of this center-click behavior. Maybe a situation where the link text wrapped, and thus the center became a void-space in between the two lines of text that wouldn't receive a click.

**Comment by mhoran** [comment]
Re: text wrapping, we do our best not to just click in the center of an element, but the center of the first [client rectangle](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects) that seems like it can be clicked: https://github.com/thoughtbot/capybara-webkit/blob/6670981917f40eb18d077878fdd640d8a74f4c6b/src/capybara.js#L194-L201. So, while the statement "center of the element" is generally accurate, there are some subtleties as you can see in the code above.

**Comment by twalpole** [comment]
Clicking on corners doesn't help because rounded corners cause the clicks to be missed, and there's no guarantee another element won't overlap at the corners (in the case of body things like headers/footers are most likely going to be at the corners).  Now that capybara-webkit basically fully  supports `send_key` you're probably better off sending something like a tab keypress rather than clicking on other elements to force the blur

**Comment by twalpole** [comment]
@AmitPatel-BoTreeConsulting  FYI - the latest capybara-webkit release added the ability to pass elements to execute_script, so rather than having to find again you should now be able to do something like

    def fill_inputmask(location, value)
      el = find(location).click
      page.execute_script "$(arguments[0]).val('#{value}');", el
      el.send_keys :tab
    end

**Comment by PrabuBalasundaram** [comment]
try giving control +A. Then your input. This should work.

**Comment by luislezcair** [comment]
I found this problem and tried the workarounds posted here until I found that `split`ing the string to `send_keys` did the job. In my case I had an input with a time mask.

```ruby
  element = find('#masked_input').click
  element.send_keys '12:13'.split
```

**Comment by 01oseluiz** [comment]
I have tried the workarounds posted here to, but not works well for me, so i just filled my field like the mask requires, like: fill_in('time', with: '10:20')
