### ISSUE TITLE
Thin server causes WebkitInvalidResponseError

### ISSUE THREAD

**Issue by nickpellant** [thoughtbot/capybara-webkit#331]
I've been receiving a `WebkitInvalidResponseError` for some very simple acceptance tests that contain more than one redirect recently (testing the devise forgotten password functionality within my application). I found this strange, as when I first wrote the tests they passed fine.

Then I found the problem. I'd introduced the thin gem to run Faye. Since this, it appears that capybara-webkit used it by default, and then started throwing errors.

Everything works fine with unicorn.

**Comment by calleerlandsson** [comment]
Are you still experiencing these issues using the latest version of capybara-webkit?

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity. Please re-open it if you're still experiencing these issues.
