### ISSUE TITLE
Iframes and javascript errors with capybara webkit

### ISSUE THREAD

**Issue by galkon** [thoughtbot/capybara-webkit#349]
Hi there,

I have found a weird issue where if a page within an iframe has a javascript error capybara-webkit interprets the page to be the contents of the iframe rather than the actual page which contains the iframe. 

I have recently came from using selenium-webdriver where all the tests ran fine but with capybara webkit i have this issue so it must be specific to capybara-webkit.

I found this by outputting page.html into the console.

**Comment by calleerlandsson** [comment]
I'm closing this issue due to the long time of inactivity. Please re-open it if you're still experiencing these issues using the latest version of capybara-webkit.
