### ISSUE TITLE
resize_window has no effect on save_screenshot

### ISSUE THREAD

**Issue by Sephi-Chan** [thoughtbot/capybara-webkit#354]
Hi,

I'm testing an app using modals (via Twitter Bootstrap) but I can't see al the modal on the page since the page height is too low. The `resize_window` method has no effect on the height.

Example: http://img29.imageshack.us/img29/6224/suggestedfixes.png

How can I change the size of the windows?

Thanks.

**Comment by calleerlandsson** [comment]
@mhoran, @jferris have there been changes related to this issue? Can it be closed?

**Comment by jferris** [comment]
There haven't been any updates here.

I think a few different bugs have been discussed, and there are some issues regarding Qt 4 vs Qt 5.

Given the age of the issue, the fact that Capybara doesn't really have a spec for exactly how screenshots should work, and that we're phasing out Qt 4, I think it makes the most sense to close this issue.

If anybody is still having trouble with the way screenshots work, please open a new issue for your particular bug.

I'm also open to pull requests that change the way this works if somebody thinks the current behavior is unintuitive.
