### ISSUE TITLE
Regain focus of parent of the frame that has been removed.

### ISSUE THREAD

**Issue by piotrj** [thoughtbot/capybara-webkit#365]
I have a page that has an iframe but after some operations it closes that iframe. This causes the following error:

```
Capybara::Driver::Webkit::WebkitInvalidResponseError:
  Already at parent frame.
```

I guess this is because:

``` ruby
within_frame "frame1" do
  click_link "A"
  click_link "B" # At this point the iframe closes
end # so it's detached here and it raises and error
```

Maybe this could be fixed by remembering the parent frame at the moment of focusing on the child iframe and then at the end of the block:

``` ruby
def within_frame(frame_id_or_index)
  # parent = get the current frame
  browser.frame_focus(frame_id_or_index)
  begin
    yield
  ensure
    browser.frame_focus(parent) # Regain the focus of the parent even if the frame has been detached
  end
end
```

Does this make sense? Or maybe the situation I described is not supported on purpose?

**Comment by calleerlandsson** [comment]
Can anyone confirm that this is still an issue using the latest version of capybara-webkit?

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity. Please re-open it if you're still experiencing these issues.

**Comment by kolen** [comment]
I still have this problem in 1.11.1

```ruby
let!(:iframe) { find 'body > div > iframe' }

it '...' do
  within_frame iframe do
    click_link 'X'
  end
end
```

```
     Failure/Error: within_frame iframe do
     Capybara::Webkit::InvalidResponseError:
       Already at parent frame.
```

This link 'X' inside iframe triggers removal of iframe from DOM.

**Comment by twalpole** [comment]
FYI: There is a spec for this behavior in Capybara master, and is the reason for the Capybara master failure in the last passing travis build of capybara-webkit - https://travis-ci.org/thoughtbot/capybara-webkit/jobs/127799105

**Comment by snelson** [comment]
We're still having this problem as well in 1.11.1. Here's a temporary workaround we've been using that avoids the `page.driver.browser` deprecation warnings:

````ruby
  def within_frame(selector)
    page.within_frame(selector) do
      yield
    end
  rescue Capybara::Webkit::InvalidResponseError => e
    raise(e) unless e.message == "Already at parent frame."
  end
````

**Comment by twalpole** [comment]
Closing since this should be fixed in the latest release version
