### ISSUE TITLE
select method does not trigger changed event

### ISSUE THREAD

**Issue by mariochavez** [thoughtbot/capybara-webkit#389]
I have a cucumber test that select a value in a dropdown, I'm selecting the value like:
select 'Value', from: 'My Field'

This code works with selenium, which triggers the change event for js. But if a switch to use capybara-webkit the new value is selected but the event is never triggered.

**Comment by jferris** [comment]
@teggen @juhlila could you provide more information about what you're doing? An example from your JavaScript, HTML, and test would be helpful.

**Comment by mariochavez** [comment]
It's been a while since I had this issue but if I recall correctly, it is related to effects and animations, like the selector not being visible at the time that capybara code runs to select an item, this was because a previous step trigger an animation to display the select.

**Comment by mhoran** [comment]
I've seen sporadic failures due to CSS animations. We recently added the following to our application layout to work around the issue:

```haml
-# This disables modal animations/transitions in tests.
- if Rails.env.test?
  :css
    .modal.fade .modal-dialog {
      transition: inherit;
      -webkit-transition: inherit;
    }
```

This is a specific override for Bootstrap modals, but it should be applicable to any CSS animation.
