### ISSUE TITLE
Cannot connect to X server error

### ISSUE THREAD

**Issue by naveediitb** [thoughtbot/capybara-webkit#402]
Running on Ubuntu
Checked both on EC2 and Linode

webkit_server: cannot connect to X server 
/usr/lib/ruby/gems/1.8/gems/capybara-webkit-0.12.1/lib/capybara/driver/webkit/connection.rb:103:in `attempt_connect'
/usr/lib/ruby/gems/1.8/gems/capybara-webkit-0.12.1/lib/capybara/driver/webkit/connection.rb:96:in`connect'
/usr/lib/ruby/1.8/timeout.rb:62:in `timeout'
/usr/lib/ruby/gems/1.8/gems/capybara-webkit-0.12.1/lib/capybara/driver/webkit/connection.rb:94:in`connect'
/usr/lib/ruby/gems/1.8/gems/capybara-webkit-0.12.1/lib/capybara/driver/webkit/connection.rb:17:in `initialize'
/usr/lib/ruby/gems/1.8/gems/capybara-webkit-0.12.1/lib/capybara/driver/webkit.rb:26:in`new'
/usr/lib/ruby/gems/1.8/gems/capybara-webkit-0.12.1/lib/capybara/driver/webkit.rb:26:in `initialize'
/usr/lib/ruby/gems/1.8/gems/capybara-webkit-0.12.1/lib/capybara/webkit.rb:5:in`new'
/usr/lib/ruby/gems/1.8/gems/capybara-webkit-0.12.1/lib/capybara/webkit.rb:5
/usr/lib/ruby/gems/1.8/gems/capybara-1.1.2/lib/capybara/session.rb:61:in `call'
/usr/lib/ruby/gems/1.8/gems/capybara-1.1.2/lib/capybara/session.rb:61:in`driver'
/usr/lib/ruby/gems/1.8/gems/capybara-1.1.2/lib/capybara/session.rb:157:in `visit'
/usr/lib/ruby/gems/1.8/gems/capybara-1.1.2/lib/capybara/dsl.rb:161:in`visit'

Need help.

Thank you

**Comment by pcsgithubid** [comment]
How to fix the below error. i have installed QT5 and the environment is linux.

[31mFailure/Error: login_as user, property[0m
     [31mCapybara::Webkit::ConnectionError:[0m
     [31m  /home/jenkins/.rvm/gems/ext-jruby-1.7.20@resquared/gems/capybara-webkit-1.3.1/bin/webkit_server failed to start.[0m
     [36m# /home/jenkins/.rvm/gems/ext-jruby-1.7.20@resquared/gems/capybara-webkit-1.3.1/lib/capybara/webkit/connection.rb:75:in `parse_port'[0m

**Comment by kstevens** [comment]
@pcsgithubid might want to check the solutions proposed here: https://github.com/thoughtbot/capybara-webkit/issues/678
