### ISSUE TITLE
Tests failing on Integration Server (Ubuntu 12.10)

### ISSUE THREAD

**Issue by HangingClowns** [thoughtbot/capybara-webkit#467]
I have an integration server that runs the tests to make sure that we dont' submit broken code. The tests get run through rake tasks through jenkins. 2 tests seem to fail (by not finding an element that should be there, but they are not there for some strange reason), but tests on 10.8.2 work fine both with cucumber-guard and rake cucumber task.

**Comment by redbar0n** [comment]
If it is the same problem I was having, then it's an issue with the Webkit implementation that Qt 4 uses on OSX. The solution is to upgrade to Qt 5 which uses a newer version that doesn't throw these kinds of errors when trying to play MP4 videos, for instance. See this blog post for details about the problem and solution: http://magnemg.tumblr.com/post/113251336220/how-to-solve-a-capybara-webkit-and-video-js

**Comment by calleerlandsson** [comment]
Thanks for the possible fix @redbar0n.

I'll close this issue due to the long time of inactivity. If you're still having this issue, @HangingClowns, please feel free to re-open it.
