### ISSUE TITLE
undefined method `switch_to' for Capybara::Driver::Webkit::Browser (NoMethodError) 

### ISSUE THREAD

**Issue by nathanvda** [thoughtbot/capybara-webkit#47]
Hi, we have a help button on our site, that opens the 'help'  window. So to be able to check, we need to switch windows. Before, using `selenium` we needed to do something like:

```
page.driver.browser.switch_to.window('online_manuals')
```

But then i get the error that the method `switch_to` is not defined.

I am happy to add that, if that is possible. I just have no clue where to start. If somebody is willing to give me some pointers, i am willing to take a shot at it.

**Comment by LucasCioffi** [comment]
You may also find the answer that starts with "Adding an answer for those hitting this in 2016 and beyond..." at https://stackoverflow.com/questions/6930927/how-do-i-confirm-a-javascript-popup-with-capybara helpful.
