### ISSUE TITLE
Choose method dont triggers the 'change' event.

### ISSUE THREAD

**Issue by cibernox** [thoughtbot/capybara-webkit#496]
I have a 3 radio buttons.
I also have a 'change' event binded to that radio buttons via a delegated call.

``` cofescript
node.on 'change', ':radio', @enableOrDisableRejectReasonField
```

When the third radio button, labeled with "Other (specify)", is chosen, a text field next to it should be enabled.
In my test I do that:

``` ruby
# I have a disabled field
page.should have_css '#availability_answer_reject_reason_explanation[disabled]'
# I choose the radio button that should enable that field
choose 'Other (specify)'
find_field('Other (specify)').trigger('change')  #=> I need to manualy trigger the change event only with capybara-webkit
# The field is not disabled now
page.should have_no_css '#availability_answer_reject_reason_explanation[disabled]'
```

With selenium I have no need to manually trigger the event. Capybara-webkit doesn't seem to fire the change event.

Is this behavior intended or known?

**Comment by jankeesvw** [comment]
I'm seeing the same issue, upgraded to Capybara-webkit 1.6 but unfortunately that makes no difference.
