### ISSUE TITLE
Cucumber feature failing with Errno::EPIPE: Broken pipe on first step

### ISSUE THREAD

**Issue by MadWagon** [thoughtbot/capybara-webkit#498]
Hello,

I am trying to use webkit instead of selenium in my cucumber features. I am on Ubuntu 10.04, I have Qt 4.8.4, I could compile different versions of the gem (0.13.0 and 0.14.2), but I always getting this error on the first step:
```visit "/users/login"```

This is the error I get 
```/home/franz/.rvm/gems/ruby-1.9.3-p374/gems/capybara-webkit-0.14.2/bin/webkit_server: symbol lookup error: /home/franz/.rvm/gems/ruby-1.9.3-p374/gems/capybara-webkit-0.14.2/bin/webkit_server: undefined symbol: _ZN9QListData11detach_growEPii```

```Errno::EPIPE: Broken pipe```
```./features/step_definitions/user_steps.rb:65:in `sign_in'```

I get exactly the same resultt with versions 0.13 and 0.14.2

**Comment by calleerlandsson** [comment]
I'll close this issue due to the long time of inactivity.
