### ISSUE TITLE
Autocomplete inputs

### ISSUE THREAD

**Issue by dougalcorn** [thoughtbot/capybara-webkit#50]
When using selenium (or even culerity) I can simply fill_in fields with strings and the jquery ui autocomplete fields will trigger the proper events to make the right ajax calls. I can then properly find the right links and click them to select which autocomplete result I want.

Unfortunately, all these tests fail with capybara-webkit. I tried manually triggering the right events, but I get Capybara::NotsupportedByDriverError when doing find("#id").trigger("focus") and also page.evaluate_javascript("$('#id').focus();").

BTW, I'm running with JRuby 1.6.1

**Comment by calleerlandsson** [comment]
Can someone confirm whether or not this issue still exists in the latest version of capybara-webkit?

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity. Please re-open it if you're still experiencing these issues.

**Comment by KernelFolla** [comment]
i can confirm that it's a JQuery UI issue, absolutely not related to capybara, because same issue exists on all headless environments and can be solved easily doing js tricks described in this issue

**Comment by Ethanator** [comment]
This worked for me.
`def fill_in_autocomplete(id, value)
  page.execute_script("document.getElementById('#{id}').setAttribute('value', '#{value}');")
end`

**Comment by joycesolis** [comment]
Thankyou for the solution Ethanator, worked, had been searching for a solution but nothing else worked.
