### ISSUE TITLE
QNetworkReplyImplPrivate printed to stdout

### ISSUE THREAD

**Issue by DivineDominion** [thoughtbot/capybara-webkit#509]
After setting up `capybara-webkit`, I encountered this error message which is simply printed to the console during execution:

    QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.

It doesn't occur every time, though.  The test which makes this message appear is:

    # spec/requests/event_form_validation_spec.rb
    require File.expand_path(__dir__ + '/../spec_helper')

    describe "Form validation" do
      describe "async form validation", :js => true do
        it "shows the error only once" do
          visit timeline_path
          submit_weight("invalid one")
          submit_weight("invalid two")      
      
          find('form#new_event').should have_selector('.error', count: 1)
        end
      end
    
      def submit_weight(custom_weight = nil)
        raise "missing weight value" unless custom_weight
    
        within 'form#new_event' do
          fill_in 'event[weight]', :with => custom_weight
          click_button 'Save'
        end
      end
    end

env:

* capybara (2.1.0)
* capybara-webkit (0.14.1 0abc7e1)

**Comment by calleerlandsson** [comment]
I'll close this due to the long time of inactivity. Please feel free to re-open this issue if you're still seeing these error messages!

**Comment by JasonThomasData** [comment]
I am seeing these errors, by scraping sites from the same domain. I catch these errors, and the program still works as expected. It's not causing my program to behave any differently, but obviously not desirable.
