### ISSUE TITLE
For `have_selector`, count option is treated as "at least N" instead of "exactly N"

### ISSUE THREAD

**Issue by DivineDominion** [thoughtbot/capybara-webkit#511]
**Situation:** On JavaScript form submission, Rails responds with a `js.erb` template which currently adds an `.error` element to the DOM.  On subsequent form submissions, the elements stack.

Capybara's Selenium JavaScript driver successfully notices the `span.error` duplicates.  Webkit doesn't.  Here's the code:

    submit_the_form "once"   # adds an .error element
    submit_the_form "twice"   # adds another .error element
    find('#edit_event_1').should have_selector('.error', count: 1)   # should fail

Turns out the webkit driver lets the example pass for `count: 2`, too.  Only when I test for `count: 3` or higher does it fail:

    1) Editing Events Ajax editing test shows the error only once
       Failure/Error: find('#edit_event_1').should have_selector('.error', count: 3)
       Capybara::ExpectationNotMet:
         expected to find css ".error" 3 times, found 2 matches: "is not a number", "is not a number"

Seems like `have_selector('.error', count: 1)` isn't testing for _exactly 1_ but _at least 1_ match with the webkit driver.

**Comment by calleerlandsson** [comment]
I'll close this due to the long time of inactivity.
