### ISSUE TITLE
Timeout when loading a URL containing a # hash / fragment identifier

### ISSUE THREAD

**Issue by pete-otaqui** [thoughtbot/capybara-webkit#52]
In a step definition, this:

`visit('/page#do-some-javascript')`

completely fails to load anything, and doesn't even seem to time out (I got bored after > 5 minutes).  Swapping in the :selenium driver makes the page work as expected.  When I did finally kill the test run, I got the rather unhelpful error:

`undefined method `strip' for nil:NilClass (NoMethodError)`

I'm using cucumber 0.10.2, capybara-webkit 0.3.0 and capybara 0.4.1.2 on Ubuntu, but not too sure where to look for any more logging information.

**Comment by SanderMander** [comment]
This visit(campaign_path(campaign,anchor: 'twitter')) dosen't do anything if browser already was launched before and this is a second call of 'visit' function.
E.g. 
```ruby
before { visit(dashboard_path) }
it 'bla bla bla', js: true do
  visit(campaign_path(campaign,anchor: 'twitter')) # this will be ignored if before called
  expect(page).to have_content 'Greetings'
end

```
