### ISSUE TITLE
Webkit server does not seem to honor "Connection: close"

### ISSUE THREAD

**Issue by carrierwrt** [thoughtbot/capybara-webkit#531]
I'm running capybara-webkit against an embedded webserver (uhttpd) that insists on "Connection: close" in all its http replies. Unfortunately its prayers are left unanswered: I'm seeing tcpdumps where webkit_server is making new requests on the same TCP connection anyway (and getting slapped in the face with RST).

I've poked around the source code in /src. I've also compared the behavior with Aurora, but it does not seem to exhibit the same behavior. I've also compared source code between the two, and from what I can see the only real difference is that Aurora does not wrap the QNetworkReply in a "NetworkReplyProxy" or similar, like capybara-webkit does, but instead returns/emits the raw QNetworkReply. Could there by some aspect related to HTTP connection keep-alive that NetworkReplyProxy does not reflect correctly?

Any ideas on how to hunt this down would be greatly appreciated.

**Comment by calleerlandsson** [comment]
I'll close this issue due to the long time of inactivity. Please feel free to re-open it if you're still experiencing these issues.
