### ISSUE TITLE
Possbility to test file upload initiated by javascript

### ISSUE THREAD

**Issue by miks** [thoughtbot/capybara-webkit#546]
I have page to test where actual file upload input is hidden and upload itself is triggered with click event from simple button.
With capybara 2.1.0 and capybara webkit 1.0.0 I have no clue how to test this kind of interface. When test trigger click on UI button within capybara-webkit and save screenshot there is no upload dialog present (unlike in real browser). 
Also "attach_file" method is failing as file upload input is hidden.

**Comment by acrogenesis** [comment]
@miks did you solve this?

**Comment by miks** [comment]
@acrogenesis I just made form and regular file input visible for tests like (here:  https://github.com/cubesystems/releaf/blob/master/releaf-i18n_database/spec/features/translations_spec.rb#L78)

**Comment by acrogenesis** [comment]
Thanks that worked :+1:

**Comment by calleerlandsson** [comment]
I'm closing this issue since it seems to be resolved.
