### ISSUE TITLE
Errno::EPIPE: Broken pipe

### ISSUE THREAD

**Issue by cbunhok** [thoughtbot/capybara-webkit#547]
Dear Everyone,

I got this error with capybara-webkit while running rspec.
My Ubuntu is 13.04 version, capybara-webkit is 1.0.0 version.
Anyone have idea about this problem?

Best Regards & Thanks in advance.
Bunhok

**Comment by calleerlandsson** [comment]
I'll close this due to the long time of inactivity and as a duplicate of #540.
