### ISSUE TITLE
Random failure: Capybara::Webkit::InvalidResponseError: 'undefined' is not an object

### ISSUE THREAD

**Issue by marcgg** [thoughtbot/capybara-webkit#550]
Hello,

Running 1.0.0 with ruby 2.0.0-p247 & qt-4.8.5 I am getting random `Capybara::Webkit::InvalidResponseError` every once in a while. Let's say I run my tests 10 times in a row it might happen twice on 2 different tests.

I tried on various machines and it seems to happen more frequently on the less powerful setups, but even very recent macbook pros run into the issue.

I've spent some time trying to figure out what could be wrong in my code, but there isn't anything out of the ordinary, so I am not sure anymore how to go about this so I figured I'd bring this up here.

This issue seemed to be linked to our recent upgrade to Ruby 2.0, but I could be wrong since - like I said - it's very random.

Thanks

**Comment by redbar0n** [comment]
If it is the same problem I was having, then it's an issue with the Webkit implementation that Qt 4 uses on OSX. The solution is to upgrade to Qt 5 which uses a newer version that doesn't throw these kinds of errors when trying to play MP4 videos, for instance. See this blog post for details about the problem and solution: magnemg.tumblr.com/post/113251336220/how-to-solve-a-capybara-webkit-and-video-js

**Comment by calleerlandsson** [comment]
Thanks @redbar0n. I'll close this issue due to the long time of inactivity. Feel free to re-open it if you're still experiencing these issues.
