### ISSUE TITLE
Capybara-webkit plays HTML5 audio elements.

### ISSUE THREAD

**Issue by foxyblocks** [thoughtbot/capybara-webkit#555]
It is surprising to me that HTML5 audio is audible during tests. Is this the intended behavior? It seems to me that given the nature of a headless browser is to not present the UI, then it should not audibly play audio/video files. They are part of the UI after all.

**Comment by ingolfured** [comment]
I'm definitely hearing audio when playing videos. Any way to disable it?

**Comment by jferris** [comment]
We've never found a way to enable or disable HTML audio. As far as we can tell, Qt doesn't expose this to us.

One option would be to use block the URLs that load videos. It's probably unnecessary to have your videos actually play in your specs. Check out the configuration options here: https://github.com/thoughtbot/capybara-webkit#configuration
