### ISSUE TITLE
[Install problem] - No such file or directory => /bin/sh: line 0: cd: src/:

### ISSUE THREAD

**Issue by wickkidd** [thoughtbot/capybara-webkit#56]
Here's the log from my attempt to get bundler to install the gem after installing Qt.  FYI, my system is osx 10.6.7 with rvm ruby 1.8.7.

less /usr/local/rvm/gems/ruby-1.8.7-p334/gems/capybara-webkit-0.3.0/./gem_make.out

/usr/local/rvm/rubies/ruby-1.8.7-p334/bin/ruby extconf.rb 
cd src/ && /usr/bin/qmake /usr/local/rvm/gems/ruby-1.8.7-p334/gems/capybara-webkit-0.3.0/src/webkit_server.pro -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile.webkit_server
/bin/sh: line 0: cd: src/: No such file or directory
make: **\* [sub-src-webkit_server-pro-qmake_all] Error 1

make
cd src/ && /usr/bin/qmake /usr/local/rvm/gems/ruby-1.8.7-p334/gems/capybara-webkit-0.3.0/src/webkit_server.pro -spec /usr/local/Qt4.7/mkspecs/macx-g++ -o Makefile.webkit_server
/bin/sh: line 0: cd: src/: No such file or directory
make: **\* [src/Makefile.webkit_server] Error 1

**Comment by Jarvishappy** [comment]
@rwilcox  You save me! I compile other project encounter the same problem as yours(I use zsh). Google pointed me here.

**Comment by vishnu-vv** [comment]
Try `/usr/bin/xcodebuild` and you should get the result like 

➜  ~ /usr/bin/xcodebuild
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance


Then try `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

Now try again `/usr/bin/xcodebuild`, you should see something like this.

➜  ~ /usr/bin/xcodebuild
xcodebuild: error: The directory /Users/vishnu_vv does not contain an Xcode project.

Now try `bundle install`

**Comment by shri-hari93** [comment]
@vishnu-vv The above solution worked for me!! Thanks a ton. Could you explain what you actually did?

**Comment by vishnu-vv** [comment]
@shri-hari93 What i did was exactly shown above. Did you mean how did i get there?

**Comment by setempler** [comment]
Had the same issue caused by `CDPATH` in a Makefile and used

    cd ./directory && ...

instead of

    cd directory && ...

Thanks duckduck for pointing me here!

**Comment by k00ka** [comment]
Was just rebuilding ruby after upgrading to Catalina today - 8 years later. Thanks for the suggestion, it worked for me (zsh, homebrew, ruby, rbenv)
