### ISSUE TITLE
Add option to to fail scenario (or raise ruby exception) on any JS error on page

### ISSUE THREAD

**Issue by petRUShka** [thoughtbot/capybara-webkit#562]
The `poltergeist` driver has option to raise ruby error and hence fail scenario on JS error. It would be great if `capybara-webkit` had such option because on significant part of web apps JS error is critical application error.

I know about `page.should_not have_errors` but check it in every JS scenario isn't so comfortable.

**Comment by calleerlandsson** [comment]
@mhoran, @jferris Should this issue be closed or kept open for future reference?

**Comment by jferris** [comment]
This isn't a bug, so I'm going to close it.

I would love to support this, and would certainly accept a pull request which implemented it. I also may take another stab at it myself in the future.
