### ISSUE TITLE
Records created in spec don't show up in server thread

### ISSUE THREAD

**Issue by stewartmatheson** [thoughtbot/capybara-webkit#569]
I can't access any data I create in my specs from the server thread.  I am cleaning my database between my specs. I also tried using a shared connection across threads however this did not resolve the issue.  Am I correct in assuming that out of the box AR does not use transactions. If so there could be an issue with the way capybara-webkit is accessing the database for non rails applications.  Using, ActiveRecord, rspec, sinatra.

**Comment by calleerlandsson** [comment]
I'll close this issue due to the long time of inactivity. Please feel free to re-open it if you're still experiencing these issues.
