### ISSUE TITLE
page.driver.headers Not changing JS document.referrer

### ISSUE THREAD

**Issue by gguerrero** [thoughtbot/capybara-webkit#574]
Using *header* method to change the **Referer**:

```ruby
page.driver.header 'Referer', 'https://www.thoughtbot.com'
```

And then visiting a page:

```ruby
visit "/"
```

You'll only have your new referer at ```request.referer```, but the javascript:

```javascript
document.referrer
```
It returns blank! (the javascript 'referrer' word has 'rr' is not a typo)

**Comment by calleerlandsson** [comment]
I'll close this issue due to the long time of inactivity.
