### ISSUE TITLE
NoResponseError on OSX Mountain Lion with QT 4.8.5

### ISSUE THREAD

**Issue by stianselland** [thoughtbot/capybara-webkit#577]
Hi there.

I'm getting a `NoResponseError` when running my specs. Several capybara specs are passing prior to the one that is failing, and subsequent capybara specs are failing with Broken pipe error.

The spec fails when run alone and when run together with the other specs. I am running the specs using `bundle exec`

Gem versions:

    capybara (1.1.4)
    capybara-webkit (0.13.1)

QT version is 4.8.5

Here is the output from the test with the webkit_debug driver: https://gist.github.com/stianselland/6991391

Here is the crash report from the Console:
https://gist.github.com/stianselland/6991375

Cheers

Stian

**Comment by calleerlandsson** [comment]
I'll close this issue due to the long time of inactivity. Please feel free to re-open it if you're still having these issues.
