### ISSUE TITLE
Add support for disabling localStorage

### ISSUE THREAD

**Issue by justinleveck** [thoughtbot/capybara-webkit#582]
Requesting functionality to allow for testing scenarios where all or some of the following are disabled in the requesting browser:

- cookies
- localStorage
- sessionStorage

This pull request allowed for setting certain WebKit options (https://github.com/thoughtbot/capybara-webkit/pull/171)

And this pull request originally allowed for disabling localStorage
(https://github.com/thoughtbot/capybara-webkit/pull/310)

**Comment by calleerlandsson** [comment]
I'll close this issue due to the long time of inactivity. Pull requests are welcome.
