### ISSUE TITLE
CSS3 animations make capybara-webkit silently miss a button

### ISSUE THREAD

**Issue by betelgeuse** [thoughtbot/capybara-webkit#584]
I had a problem that nothing happened after steps of clicking a button. I deduced this to be due to bootstrap modals and CSS 3 animations. The steps here fixed the problem:

http://blog.crowdint.com/2013/09/20/poltergeist-and-bootstrap-modals.html

Hopefully qt-webkit exposes when animations are running. Then capybara-webkit clicking should be changed to for animations to finish.

**Comment by calleerlandsson** [comment]
Hey @betelgeuse, I'm sorry we haven't responded to this issue. Are you still seeing it using the latest version of capybara-webkit?

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity. Please re-open it if you're still experiencing these issues.

**Comment by betelgeuse** [comment]
@calleerlandsson I tested it now with the workaround removed. I am not sure if it's our test suite or changes in capybara-webkit but a single run could not reproduce. However, NEWS file does not have anything that would indicate a fix. Maybe this can stay closed and reopened if I find to time to do more thorough testing.

**Comment by calleerlandsson** [comment]
Thanks for testing, @betelgeuse. Sounds like a good plan.

**Comment by reustmd** [comment]
@betelgeuse any idea which version of capybara-webkit has the fix?

**Comment by betelgeuse** [comment]
@reustmd not really.
