### ISSUE TITLE
Angular JS rc3 fails with undefined object in error_messages

### ISSUE THREAD

**Issue by HangingClowns** [thoughtbot/capybara-webkit#585]
When I try to login with an ajax call, the JavaScript fails on webkit, but works fine on Chrome and elsewhere without any JS errors. But in webkit, it fails and states some line number in angular.js file (the source for AngularJS framework) has an undefined object.

Any ideas?

**Comment by calleerlandsson** [comment]
Hey @HangingClowns, I'm sorry we haven't responded to this issue. Did you resolve the issue yourself or are you still having it? If so, could you provide a minimal failing example?

**Comment by HangingClowns** [comment]
Moved on. I can't remember if this happens anymore. I guess just close for now.
