### ISSUE TITLE
Failed to click element at specific position (Capybara::Webkit::ClickFailed)

### ISSUE THREAD

**Issue by Loremaster** [thoughtbot/capybara-webkit#592]
In our app we implemented google map, so when we edit specific objects then we fill address and on the fly we get list with addresses and after click on one of suggested address we get marker on our map.

Such code clicks on suggested address:

```ruby
def fill_location_address(address)
  fill_in 'place_autocomplete', with: address
  sleep 3                                                                       # Giving some time to load addresses from remote server.

  unless page.has_css?(".pac-container")                                         # Container should be visible (to be able to click address in dropdown select list).
    page.evaluate_script("$('.pac-container').show();")
    sleep 3
  end

  page.first('.pac-item').click                                                 # Div with data in container with google's addresses. We just click on first address.
  sleep 1.5                                                                     # It should give some time to initialize map with chosen address.
end
```

The problem is that everything works fine with selenium (well, not everything, window with browser should be focused to make test pass). But when i run this test in capybara-webkit then i get such error:

```
Failed to click element /html/body/div[5]/div[1] at position 1067, 911 (Capybara::Webkit::ClickFailed)
./features/support/spec_helper.rb:91:in `fill_location_address'
./features/step_definitions/legal_entity.steps.rb:22:in `/^I field form for legal user$/'
features/legal_entity/new.feature:19:in `When I field form for legal user'
```

You can see html page [here](https://gist.github.com/Loremaster/7528979). I also attached the image of the page.

![img](https://f.cloud.github.com/assets/1028215/1563541/432e225c-5062-11e3-9a3b-d30068eeab4c.png)

**Comment by calleerlandsson** [comment]
Hey @Loremaster, can you confirm whether or not you're still seeing these issues?

**Comment by Loremaster** [comment]
@calleerlandsson I don't work with that project anymore so I can't give you information on that.

**Comment by calleerlandsson** [comment]
Thanks for responding @Loremaster. I'll close this for now.
