### ISSUE TITLE
visit(url) hangs w/ EventSource

### ISSUE THREAD

**Issue by obfusk** [thoughtbot/capybara-webkit#597]
My findings: https://gist.github.com/obfusk/7803381.
PhantomJS issue: ariya/phantomjs#11816.

\- Felix

**Comment by volodymyr-mykhailyk** [comment]
This issue is still reproducible. It dont allow to properly test applications with EventSource functionality :(

**Comment by twalpole** [comment]
Closing due to age and the fact this is probably a Qt limitation
