### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by p-originate** [thoughtbot/capybara-webkit#624]
I am getting this in my test suite results:

<pre>
     Failure/Error: visit url
     Capybara::Webkit::InvalidResponseError:
       Unable to load URL: http://localhost:3000/users/confirmation?confirmation_token=jFsNHzCzhkz-JsJtLGbV because of error loading http://localhost:3000/users/confirmation?confirmation_token=jFsNHzCzhkz-JsJtLGbV: Unknown error
</pre>

Perhaps the real problem is not in capybara-webkit, but I should not be receiving an "unknown error" when attempting to visit a url. Whichever code produces the unknown error should produce an error that describes the reason why page loading failed so that I can address it.

**Comment by Freika** [comment]
Not sure if it could help, but I encountered exactly this error after changing from 
```
    config.action_dispatch.default_headers = {
        'X-Frame-Options' => 'ALLOWALL'
    }
```

to 

```
    config.action_dispatch.default_headers = {
        'X-Frame-Options': 'ALLOWALL'
    }
```

in config/application.rb. Note `=>` vs `:` in hash. This error crashed all tests with `js: true` and when I reverted this change, capybara again started server correctly.
