### ISSUE TITLE
Need an option to disable ClickFailed screenshots, better logging

### ISSUE THREAD

**Issue by bilts** [thoughtbot/capybara-webkit#626]
We ended up with over 14,000 ClickFailed screenshots in our CI /tmp directory, I assume due to some sort of synchronization loop (Capybara::Webkit::ClickFailed is returned by invalid_element_errors, indicating Capybara should retry it), though the test logs do not report an abnormal number of screenshots.

The new ClickFailed screenshot feature should be refined to address this in a couple of ways:

1. There should be a configuration option to disable the screenshot behavior entirely.
2. (Ideally) The driver should avoid taking screenshots repeatedly in sync loops.
3. (Alternatively) Every screenshot taken should be logged, regardless of whether its associated error is thrown, making this sort of problem easier to spot.

**Comment by calleerlandsson** [comment]
@jferris Did you look into reducing the number of screenshots saved? Can this issue be closed?

**Comment by jferris** [comment]
I haven't yet, no.

**Comment by jferris** [comment]
@mhoran any thoughts on this? I don't see a place in the driver API where we would make this change. It may make more sense to remove this auto-screenshot behavior and try to get something more generic into Capybara for saving screenshots for certain errors.

**Comment by mhoran** [comment]
I agree. Let's pull this out of capybara-webkit for now.

**Comment by jferris** [comment]
I opened #800 to resolve this issue.
