### ISSUE TITLE
Could not find mkspecs for your QMAKESPEC

### ISSUE THREAD

**Issue by justinwiley** [thoughtbot/capybara-webkit#627]
I'm using Ubuntu 13.10.  I've verified I'm using > 4 version of QT and QMake.

```
$ qmake -v
QMake version 2.01a
```

Building under ruby 2.1.1 for capybara-webkit 1.1.0 fails:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /home/user1/.rbenv/versions/2.1.1/bin/ruby extconf.rb 
Could not find mkspecs for your QMAKESPEC(linux-g++) after trying:
    /opt/anaconda1anaconda2anaconda3/mkspecs
Error processing project file: /home/user1/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/capybara-webkit-1.1.0/webkit_server.pro
Command 'qmake -spec linux-g++ ' failed

Makefile not found
```

**Comment by hargup** [comment]
@justinwiley I'm also facing the same issue. Can you tell me did you fixed it?

**Comment by justinwiley** [comment]
I think I solved this by bumping ubuntu to 14 and getting the latest version of the library.

**Comment by mjniday** [comment]
I had the same Anaconda Python issue, where it was added to the PATH

**Comment by tristantao** [comment]
The simplest fix is to reinstall qt. My original version was 4.7.4, I opted to go with 4.8.6 while I was reinstalling. In anaconda (this is the approach that required minimal (re)installing):

`conda update conda`
`conda install -c anaconda qt=4.8.6 `

I saw the same issue on OSX 10.10.5, py2.7.11 / 12.
