### ISSUE TITLE
Ability to post screenshots to AWS or other source when using CI

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/capybara-webkit#631]
I have specs that are failing in Travis due to ClickFailed exceptions, but I can't reproduce the problem on my local machine. I think it would be useful to be able to set the destination path of the screenshots that get posted, ideally to be able to upload them to an AWS S3 bucket or something similar, allowing failed builds to record their issues.

**Comment by calleerlandsson** [comment]
I'll close this issue since #632 was closed.
