### ISSUE TITLE
syntax error on unicode keys

### ISSUE THREAD

**Issue by ashanbrown** [thoughtbot/capybara-webkit#640]
It looks like capybara-webkit throws a syntax error on code like `objectWithUnicodeKey = {Ɐ: "A"};`  where Ɐ is a unicode character (2C6F).  It works fine if the key is in quotes, a la `objectWithUnicodeKey = {"Ɐ": "A"};`.  I'm seeing this because when I upgrade uglifier to 2.2.0 in my Gemfile, all my capybara tests break.  However, the tests continue to pass with selenium/firefox.  uglifyJS-2.4.0 apparently stopped wrapping keys with unicode characters in quotes in some situations.    I thought maybe I was failing to specify the character encoding, so I added charset='UTF-8' to the script tag but that didn't help.  It doesn't appear I'm serving any encoding headers with my javascript (I'm not sure how to do that), so maybe I'm just failing to set up the encoding properly for webkit, and firefox has different default encoding than capybara-webkit.  Any help/tips/suggestions would be much appreciated?  Thanks,

Andrew

**Comment by calleerlandsson** [comment]
Hey @ashanbrown, I'm sorry we have not yet responded to this issue. Are you still seeing this? Did you find a fix to it?

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity. Please feel free to re-open it if you're still having these issues.
