### ISSUE TITLE
Broken pipe Errno::ECONNRESET and No response received from the server. (Capybara::Webkit::NoResponseError)

### ISSUE THREAD

**Issue by nritholtz** [thoughtbot/capybara-webkit#643]
I originally tried using Capybara-Webkit 1.1.0, but was getting a `WebkitNoResponseError` and then a `Broken pipe Errno::ECONNRESET` for all subsequent cucumber tests .

Then I downgraded the Capybara to 2.1.0, and updated the Capybara-Webkit to use the latest commit from master 'b7d6be163c3fd6f5f6b6e34fc19200ceeaffd700'.

Now I am getting the `Broken pipe Errno::ECONNRESET`, which spreads to all subsequent tests.

```
QMake Version 2.01a
Using Qt Version 4.8.4
```
Using Ubuntu 13.10 32-bit

I have included the crash report via the Webkit Debug: https://gist.github.com/nritholtz/883477cae35beaa8406b

The test parses a CSV file from a download link to ensure its contents are correct. It seems to be getting this error as soon as the old test finishes and the new one starts.

**Comment by calleerlandsson** [comment]
Can you confirm whether or not you're still having these issues using the latest version of capybara-webkit?

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity. Please feel free to re-open it if you're still having these issues.
