### ISSUE TITLE
Slow capybara_server boot time for some users

### ISSUE THREAD

**Issue by feifanzhou** [thoughtbot/capybara-webkit#653]
This spec takes about 5.5 seconds to load:

    require 'rails_helper'
    
    describe 'Attempt', js: true do
      before :each do
        visit '/blank'
      end
    
      it 'has a thing' do
      end
    end

*Terminal output*

    $ rspec spec/features/test_spec.rb 
    WARN: Unresolved specs during Gem::Specification.reset:
          rspec-expectations (~> 3.0.0)
          rspec-mocks (~> 3.0.0)
    WARN: Clearing out unresolved specs.
    Please report a bug if this causes problems.
    DEPRECATION WARNING: String based terminators are deprecated, please use a lambda. (called from <class:Artist> at /Users/Feifan/Developer/audience/app/models/artist.rb:51)
     1/1 |======================================================================================================== 100 =========================================================================================================>| Time:     00:00:05 
    
    Finished in 5.56 seconds (files took 2.85 seconds to load)
    1 example, 0 failures    

Turning JS off for the suite reduces running time to ~0.03s.

The page itself is as simple as I could make it:

    def blank
        render text: 'blank'
    end

* Ruby 2.1.2p95
* Rails 4.1.3
* OS X 10.10 (14A283o)
* rMBP mid 2012 (2.3GHz/8GB/256GB SSD)

*Addendum*
Ran the same specs on Ubuntu VM (14.04, Parallels 9). ~0.3s for JS vs ~0.02s for non-JS

**Comment by paneq** [comment]
I've been experiencing very similar problem yesterday (very slow `visit`). It turned out to be problem with external javascript. Tests were passing but really extremely slow. It wasn't slow all the time. Just yesterday. It was geographically restricted issue from mixpanel: _We are investigating network issues that are causing some timeouts to a US node for our ingestion API._ Surprisingly locally everything was really fast. That's because in our region mixpanel was working. But CI was in US and it was slow there. So slow that it was timing out.

Example solution for capybara 1.3.1:

```
Capybara.register_driver :webkit_with_blacklist do |app|
  driver = Capybara::Webkit::Driver.new(app)

  # add you external JS here, http vs https seems to apply
  driver.browser.url_blacklist = %w(
    http://player.vimeo.com
    http://maps.googleapis.com
    http://google-analytics.com
  )
  driver
end

Capybara.javascript_driver = :webkit_with_blacklist
```

But instead of continuing with that, we upgraded to `1.4.1` and use `page.driver.block_unknown_urls if page.driver.respond_to?(:block_unknown_urls)`. That fixed the problem for us. And I like that capybara 1.4.1 is very verbose about external JS scripts :)

**Comment by mvz** [comment]
Is the branch with the `test.rb` script still available?

**Comment by jferris** [comment]
@mvz I finally discarded that branch at the end of last year. I don't think it was useful, because we were never able to isolate and reproduce the original issue.

Are you running into a similar issue?

**Comment by mvz** [comment]
@jferris We're getting "webkit_server failed to start after 15 seconds" errors in our CI environment, but only in the first JS-related cucumber scenario.

**Comment by jferris** [comment]
@mvz sounds like you're running into a different issue. Could you open a new issue with some more details about your setup?

**Comment by mvz** [comment]
@jferris sure, I will do that.

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity regarding the original issue. If you're still having theses issues please feel free to re-open this.

**Comment by derosm2** [comment]
@mvz running in to the same issue - were you able to find a solution?

**Comment by mvz** [comment]
Hi @derosm2, no I'm sorry the problem just went away by itself.

**Comment by nhance** [comment]
I'm seeing this and the problem appears to be with the `webkit_server` binary as it takes at least 15 seconds for it to start:

```
➜  capybara-webkit git:(master) ✗ qmake -v
QMake version 2.01a
Using Qt version 4.8.6 in /usr/lib/x86_64-linux-gnu
➜  capybara-webkit git:(master) ✗ cd bin
➜  bin git:(master) ✗ ls -al
total 464
drwxrwxr-x  2 nhance nhance   4096 May  9 13:24 .
drwxrwxr-x 10 nhance nhance   4096 May  9 13:24 ..
-rw-rw-r--  1 nhance nhance    659 May  9 13:23 Info.plist
-rwxrwxr-x  1 nhance nhance 462114 May  9 13:24 webkit_server
➜  bin git:(master) ✗ ./webkit_server
WARNING: The next major version of capybara-webkit will require at least version 5.0 of Qt. You're using version 4.8.6.
Capybara-webkit server started, listening on port: 49592
```

Not shown is the 15+ seconds between the `./webkit_server` command and when `WARNING` appears.

This is happening on a Digital Ocean droplet I use for development

**Comment by nhance** [comment]
Same result on QT5. This is Ubuntu Trusty

**Comment by nhance** [comment]
Turns out this was an issue that's solved when you run behind `xvfb-run`. See the "CI" section in the readme for details

**Comment by Fjan** [comment]
I'll leave this here in case other people stumble into this:

In my case the issue turned out to be that the webbrick instance started by Capybara takes forever to start up, and simply adding ```Capybara.server = :puma``` fixes the slow server boot
