### ISSUE TITLE
sporadic occurrences of Capybara::Webkit::ClickFailed ... because of overlapping element

### ISSUE THREAD

**Issue by jjb** [thoughtbot/capybara-webkit#656]
My large test suite always passes locally. On my CI service (semaphore) it fails about half the time. When it fails, is some number of occurances of the following type of error:

```
Capybara::Webkit::ClickFailed:
  Failed to click element /html/body/div[2]/div[6]/form[@id='new_session']/div[5]/div/input because of overlapping element /html/body/div[2]/div[2]/div[1]/div[@id='slide-4']/img at position 1647, 46; 
```

Sometimes there are a handful of occurrences, sometimes there are dozens or more than 100.

I suspected some sort of inadvertent network dependency in my test suite causing the variation, but I don't think that would result in the inconsistent number of failures. (Also, I know my test suite pretty well and I just can't imagine how that would cause it anyway)

I also suspected some sort of other timing dependency (running on fast vs. slow machine) but experimentation with this has also turned up nothing (it's possible I haven't been thorough here though).

Any ideas? Suggestions for where to look next?

**Comment by calleerlandsson** [comment]
I'll close this issue due to the long time of inactivity.
