### ISSUE TITLE
Broken pipe error occurs when running capybara-webkit with headless and sidekiq gem.

### ISSUE THREAD

**Issue by vuquangtruong** [thoughtbot/capybara-webkit#659]
Hi, I'm writing a scraping application with rails and I'm using headless gem to be able to run on a Ubuntu server 12.04. I also use sidekiq gem to run the scraping code in background process.

The problem is that when I start sidekiq and run the scraping code, it works perfectly for first time but next run is fail and I have to restart sidekiq and it works well for only first run. The error happens on both ubuntu desktop 12.04 and ubuntu server 12.04

This is the error :

2014-08-08T07:00:40Z 11379 TID-uswlo WARN: Broken pipe
2014-08-08T07:00:40Z 11379 TID-uswlo WARN: /home/u/.rvm/gems/ruby-1.9.3-p547/gems/capybara-webkit-1.2.0/lib/capybara/webkit/connection.rb:30:in `write'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/capybara-webkit-1.2.0/lib/capybara/webkit/connection.rb:30:in `puts'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/capybara-webkit-1.2.0/lib/capybara/webkit/connection.rb:30:in `puts'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/capybara-webkit-1.2.0/lib/capybara/webkit/browser.rb:166:in `command'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/capybara-webkit-1.2.0/lib/capybara/webkit/browser.rb:18:in `visit'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/capybara-webkit-1.2.0/lib/capybara/webkit/driver.rb:29:in `visit'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/capybara-2.1.0/lib/capybara/session.rb:193:in `visit'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/capybara-2.1.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
/home/u/tokyo/channel-auth-api/app/workers/twitter_authentication_job.rb:31:in `perform'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/processor.rb:48:in `block (3 levels) in process'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/middleware/chain.rb:115:in `call'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/middleware/chain.rb:115:in `block in invoke'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/middleware/chain.rb:117:in `block in invoke'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/middleware/chain.rb:117:in `block in invoke'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/middleware/chain.rb:117:in `block in invoke'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/middleware/chain.rb:120:in `call'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/middleware/chain.rb:120:in `invoke'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/processor.rb:47:in `block (2 levels) in process'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/processor.rb:102:in `stats'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/sidekiq-2.14.0/lib/sidekiq/processor.rb:46:in `block in process'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `call'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.15.2/lib/celluloid/future.rb:14:in `block in new'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `call'
/home/u/.rvm/gems/ruby-1.9.3-p547/gems/celluloid-0.15.2/lib/celluloid/internal_pool.rb:100:in `block in create'

Can anybody help me ?
Thanks

**Comment by calleerlandsson** [comment]
I'll close this issue due to the long time of inactivity. If you're still seeing these issues, please feel free to re-open this it.
