### ISSUE TITLE
Configure capybara webkit not to render some html tags

### ISSUE THREAD

**Issue by ProGM** [thoughtbot/capybara-webkit#664]
Can you add a configuration to exclude some tags from being rendered?

An example: when a page includes an swf file, capybara webkit is extremely slow to render it. Another example are iframes.
Moreover there is also this issue on mac os:
https://github.com/thoughtbot/capybara-webkit/issues/157

Something like that:

    Capybara.register_driver :webkit do |app|
      driver.browser.ignored_tags = ['object', 'iframe']
      driver
    end

Actually I'm using a workaround (I'm setting the resource in the url_blacklist), but it's quite uncomfortable.

Thank you :)

**Comment by calleerlandsson** [comment]
I'll close this issue due to the long time of inactivity.
