### ISSUE TITLE
Fix ReactJS callbacks

### ISSUE THREAD

**Issue by c-lliope** [thoughtbot/capybara-webkit#666]
ReactJS components that render correctly in the browser aren't being loaded or recognized by capybara-webkit. I've created [a reproduction of this error](https://github.com/graysonwright/reactrails-capybara-test) with [failing specs](https://travis-ci.org/graysonwright/reactrails-capybara-test).

This is most likely a problem on Capybara-Webkit's end, because the components render as expected in Chrome 37.0.2062.94.

Let me know if you can help identify the problem, or if there's anything I can do to help triage this issue further.

Thanks for your help!

**Comment by lpender** [comment]
Just wanted to note, you should also be using a polyfill for `Function.prototype` (an es5-shim should do it).  Make sure it's included before `react` in your JS.

**Comment by devonzuegel** [comment]
I also had a hard time installing Qt on OS X. I ran into a series of issues, but the one that failed most silently when installing with Homebrew was that I had an outdated version of Xcode on my local machine. So as a quick PSA, if you're having issues make sure that your Xcode is up to date!
