### ISSUE TITLE
Choose by clicking `label` if `input` is hidden

### ISSUE THREAD

**Issue by lpender** [thoughtbot/capybara-webkit#668]
Hi!

I'm trying to `choose` a hidden radio input by it's label with Capybara Webkit, but I'm getting `Capybara::Webkit::ClickFailed: Failed to find position for element ... because it is not visible`.

Here is a simple case for reproduction:

```
  <form>
    <input id="one" type="radio" name="form"/>
    <label for="one">Click me!</label>
    <input id="two" type="radio" name="form"/>
    <label for="two">Click me!</label>
  </form>

  <style>
    input {
      display: none;
    }
    input:checked + label {
      color:blue;
    }
  </style>
```

The spec would have a line something like:

`choose 'one'`

Would be great to get this working!  No issues with vanilla Capybara.

Thanks!
-Lee

**Comment by gregblass** [comment]
@mhoran A giant thank you for this sir! Wasted so much time before I finally found this.
