### ISSUE TITLE
`content_type` of uploaded csv file is set to `application/octet-stream`

### ISSUE THREAD

**Issue by mravery** [thoughtbot/capybara-webkit#676]
I am testing an import function; I have the following code in my step definition:

```
file_location = path_to_test_data_files(file_name)
file_selector = find('input#import_file')
page.attach_file(file_selector[:name], file_location)
```

The file attaches correctly. The problem is that I use this logic to determine whether the uploaded file is valid:

```
def import
    file = params[:import_file]
    if file.content_type != 'text/csv'
    ....
```

When using `:webkit` as the javascript driver, the file content type is reported as `application/octet-stream` and my test fails. But using `:selenium` reports the file content type as `text/csv`. I did a manual check of our Rails application against Firefox, Chrome, and Safari and they all exhibit "normal" behavior (i.e. the content type is reported correctly and the upload works).

Because the Gemfile.lock is long, here's a link to a pastebin:: http://pastebin.com/QwgzrNJS

I'm assuming that there is something in capybara-webkit that is causing this issue but I could be mistaken. Thank you for taking the time to look at this issue.

**Comment by hiattp** [comment]
Not sure if capybara-webkit has control over it but upgrading to QT5 fixed this for me. If you are using homebrew on OSX [this](http://stackoverflow.com/a/28509231/949328) will help...don't think homebrew has an official version yet.

**Comment by calleerlandsson** [comment]
@mravery, @wes-r, can you confirm whether this is working or not using the latest version of capybara-webkit?

**Comment by mravery** [comment]
I’ll reply to this by 6/15.

**Comment by mravery** [comment]
It's fixed on my setup.

**Comment by calleerlandsson** [comment]
That's great @mravery! @wes-r If you have time to check whether things are working, that'd be great!
