### ISSUE TITLE
Capybara::Webkit::ConnectionError webkit_server failed to start

### ISSUE THREAD

**Issue by firedev** [thoughtbot/capybara-webkit#678]
After accidentally wiping out the whole brew directory I reinstalled ruby and Homebrew. Now my feature tests are _randomly_ failing with the following:

```
Capybara::Webkit::ConnectionError: /Users/pain/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/capybara-webkit-1.3.1/bin/webkit_server failed to start.
occurred at /Users/pain/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/capybara-webkit-1.3.1/lib/capybara/webkit/connection.rb:75:in `parse_port'
```

Gems and Ruby installed:

```
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]
  * capybara (2.4.4)
  * capybara-webkit (1.3.1)
```

Any ideas?

**Comment by onebree** [comment]
When you say, "add `qt`", do you mean as a gem or as a package?

**Comment by firedev** [comment]
As a package. `brew install qt` I think.

**Comment by justin808** [comment]
This might fix the issue, if you installed qt5:

```
gem uninstall capybara-webkit
QMAKE=/usr/local/Cellar/qt5/5.4.0/bin/qmake bundle install
```

**Comment by watsonbox** [comment]
@justin808 Thanks for the tip. This got `capybara-webkit` installed and working with qt5 for me.

**Comment by 3zcurdia** [comment]
I reinstalled ```qt``` and later ```capybara-webkit ``` and nothing any idea?

**Comment by jferris** [comment]
@3zcurdia can you try starting the `webkit_server` program from the `bin` directory in the installed gem? It may print an error explaining why it can't start.

**Comment by 3zcurdia** [comment]
I got this

      QXcbConnection: Could not connect to display 
      Aborted (core dumped

**Comment by jferris** [comment]
@3zcurdia what system are you on? If you're on a Linux system, do you have X running? If you're running headlessly, you may want xvfb or something similar.

**Comment by 3zcurdia** [comment]
ubuntu 14.04 and I am using xvfb

**Comment by leomayleomay** [comment]
same error here

```ruby
capybara 2.4.4
capybara-webkit 1.3.1
```

once i ran the `webkit_server`, it raised an error saying:
```
 QXcbConnection: Could not connect to display 
 Aborted (core dumped
```

**Comment by leomayleomay** [comment]
turns out the doc has already given out the answer to the problem

```
https://github.com/thoughtbot/capybara-webkit#ci
```

**Comment by indiesquidge** [comment]
System: `OS X 10.11 - El Capitan`
Ruby: `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]`
capybara: `2.5.0`
capybara-webkit: `1.7.1`

---

I was getting the same error as OP.
```sh
/Users/austinwood/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/capybara-webkit-1.7.1/bin/webkit_server failed to start.
```

My fix:
```sh
gem uninstall capybara-webkit
brew install qt5
brew linkapps qt5
brew link --force qt5
gem install capybara-webkit
```

[source](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit) for installing `qt5` and compiling `capybara-webkit` to work with it.

**Comment by olivierlacan** [comment]
Has anyone here tried to use the Headless gem instead of `xvfb-run -a bundle exec rspec spec/`?

Additionally, [the documentation @leomayleomay mentioned](https://github.com/thoughtbot/capybara-webkit#ci) doesn't explain what the `DISPLAY` variable should be used for or set to, that might be helpful.

**Comment by jwg2s** [comment]
@indiesquidge thanks, that worked :+1:

**Comment by yago580** [comment]
@indiesquidge's solution worked for me as well! :+1:

**Comment by dalvizu** [comment]
I saw this error using the headless gem and calling `headless.destroy()` instead of `headless.stop()` at the end of my tests. Changing to `stop()` fixed the issue.

**Comment by henrik** [comment]
Regarding @justin808's fix: to uninstall the gem if it was installed by bundler, do:

```
bundle exec gem uninstall capybara-webkit
```

Sadly this didn't fix the issue for us :D
