### ISSUE TITLE
Not applying css on a <main> tag

### ISSUE THREAD

**Issue by dimascyriaco** [thoughtbot/capybara-webkit#681]
I have something like this:

```html
<header>
    <div class="header-wrapper"></div> <!-- height: 70px, position: fixed -->
</header> 
<main role=main>...</main> <!-- margin-top: 70px -->
```

In normal browsers it works ok, but my tests are failing with a message saying the 'header' is overlapping the 'main'. The png screenshot took with capybara-screenshot shows the 'header' overlapping the 'main', but the html 'screenshot' don't show the overlapping...
If I change 'main' to 'div' the tests pass.

Is that a bug or i'm doing something wrong?

**Comment by jferris** [comment]
I'm going to close this, as it's likely an issue with older versions of Qt. Please reopen if you're still having trouble on the latest Qt.
