### ISSUE TITLE
g++: error: unrecognized command line option '-Xarch_x86_64'

### ISSUE THREAD

**Issue by u007** [thoughtbot/capybara-webkit#682]
hi,
im having problem installing on osx 10.10 yosemite,
running with gcc4.9.2
qt 4.8.6 install via brew

gem install capybara-webkit
Building native extensions.  This could take a while...
ERROR:  Error installing capybara-webkit:
    ERROR: Failed to build gem native extension.

```
/usr/local/var/rbenv/versions/2.1.4/bin/ruby extconf.rb
```

cd src/ && /usr/local/bin/qmake /usr/local/rbenv/gem/gems/capybara-webkit-1.3.1/src/webkit_server.pro -spec /usr/local/Cellar/qt/4.8.6/mkspecs/macx-g++ -o Makefile.webkit_server
cd src/ && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.webkit_server 
g++ -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Cellar/qt/4.8.6/mkspecs/macx-g++ -I. -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtNetwork.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtNetwork.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtWebKit.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtWebKit.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/include -Ibuild -F/usr/local/Cellar/qt/4.8.6/lib -x c++-header -c stable.h -o build/webkit_server.gch/c++
g++: error: unrecognized command line option '-Xarch_x86_64'
make[1]: **\* [build/webkit_server.gch/c++] Error 1
make: **\* [sub-src-webkit_server-pro-make_default-ordered] Error 2
Command 'make' failed

urgent need fix,
thank you :)

**Comment by MatthewRalston** [comment]
Hello there, I found a workaround that I want to put somewhere for posterity and this was the closest to my situation. @jferris, I was encountering the same error as above issues related to ggc/llvm as you suggested. After adjusting my path as below, I was able to install successfully. I unlinked gcc with brew to be sure. I hope this helps someone in the future!
```
export PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:$PATH
```

**Comment by johnyf** [comment]
Another option is to find `mkspecs` and edit `g++-macx.conf` to remove `-Xarch_x86_64`. In my case (OS X 10.8.5) it was at `/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-macx.conf`. This worked for a build using an Python 2.7.10 built from source.
