### ISSUE TITLE
visit method throws wrong number of arguments (2 for 0)

### ISSUE THREAD

**Issue by jbrodie** [thoughtbot/capybara-webkit#687]
For some reason this is blowing up on a test run with Ubuntu 14.04 but passes on Ubuntu 12.04.
I have done exhaustive searches on the internet with no solution.

It appears the visit call is not parsing paths as it does on 12.04?

Any suggestions / solutions would be appreciated.

```
Failure/Error: visit some_page_path(@val1, @val2, @val3, :token => @token)
     ArgumentError:
       wrong number of arguments (2 for 0)
```
Gems are as follows:
capybara (2.4.4)
capybara-webkit (1.3.1)

**Comment by jferris** [comment]
I'm going to close this, as it doesn't seem to be an issue for other users. Please reopen if you're still having issues.
