### ISSUE TITLE
Proxy doesn't forward OPTIONS requests

### ISSUE THREAD

**Issue by rupurt** [thoughtbot/capybara-webkit#688]
I'm trying to get capybara-webkit working with puffing-billy and it works for the most part.

We're using the [`webkit_billy`](https://github.com/oesmith/puffing-billy/blob/master/lib/billy.rb#L44) driver which is the `webkit` driver with a proxy. We see requests getting proxied into puffing billy for `CONNECT`, `GET`, `POST`, `PUT` & `DELETE`, however we never see `OPTIONS` requests. So far it's been a bit of a challenge to debug the issue, do you have any tips/ideas for how we can get insight into the network requests generated by the `webkit_server` binary?

**Comment by jferris** [comment]
@rupurt is there any way you could put together a test case to demonstrate this?

**Comment by rupurt** [comment]
@jferris I'll see if I can put something together for next week.

**Comment by twalpole** [comment]
Closing due to lack of response
