### ISSUE TITLE
Localhost isn't properly whitelisted

### ISSUE THREAD

**Issue by leppert** [thoughtbot/capybara-webkit#699]
The whitelisting of localhost introduced [here](https://github.com/thoughtbot/capybara-webkit/commit/3804dd54060e7d2c3e96560b4b52cc74259b349d#diff-470fce27a79450cb7ecad3b9bcd30c70R10):

```cpp
m_allowedUrls.append(QString("127.0.0.1"));
m_allowedUrls.append(QString("localhost"));
```

doesn't seem to whitelist the entire host. Whitelisting in Ruby, before each test, behaves as expected:

```ruby
page.driver.allow_url("127.0.0.1")
page.driver.allow_url("localhost")
```

**Comment by mhoran** [comment]
Great catch! I just pushed a fix in e5d840d4be94f8631ac17b558f5ab63102ad9955.
