### ISSUE TITLE
MutationObserver support

### ISSUE THREAD

**Issue by malroc** [thoughtbot/capybara-webkit#702]
I get this error in `page.driver.error_messages` when trying to test app that uses MutationObserver:
`{:line_number=>0, :message=>"ReferenceError: Can't find variable: MutationObserver", :source=>"undefined"}`
Is it a known issue? I know that PhantomJS doesn't support MutationObserver, but I thought everything should be ok with capybara-webkit since it uses native WebKit codebase.

**Comment by jferris** [comment]
I haven't seen `MutationObserver` before, and I'm not sure when it made its way into WebKit. We use your system's Qt, which will bundle a specific version of WebKit in the Qt port. You can figure out what versions you're running with this:

``` ruby
puts page.driver.version
```

You'll need to look through change logs and releases for your WebKit and QtWebKit versions to figure out which JavaScript features are supported. This is a pain, but it's necessary given the development process for WebKit.
