### ISSUE TITLE
`type` property of file field is empty

### ISSUE THREAD

**Issue by dougal** [thoughtbot/capybara-webkit#704]
When a file is selected using a file field, the type of that field is empty. Tested by outputting to the console the type, after the file is selected.

Safari:

```
ContentType: video/mp4
```

Webkit-Capybara:

```
ContentType: 
```

If it is helpful I can put together a minimal failing example application that shows this behaviour.

**Comment by jferris** [comment]
@dougal a minimal failing example would be very helpful.

**Comment by dougal** [comment]
Example application with failing spec demonstrating the above: https://github.com/dougal/capybara-webkit-issue-704

Quick-start:

    git clone https://github.com/dougal/capybara-webkit-issue-704.git && cd capybara-webkit-issue-704.git && bundle install && bundle exec rake spec

Thanks.

**Comment by calleerlandsson** [comment]
Using @dougal's example, I can reliably reproduce this.

**Comment by twalpole** [comment]
Closing due to age. We can reopen if this is still an issue with current releases.

**Comment by dougal** [comment]
Tested with `capybara-webkit 1.14.0`. Issue is now fixed.

Thanks to whoever fixed this issue either here, in Capybara, or Webkit. :)
