### ISSUE TITLE
Socks5 proxy support

### ISSUE THREAD

**Issue by addicted2sounds** [thoughtbot/capybara-webkit#705]
Is it possible to use socks proxy instead of http proxies?

**Comment by jferris** [comment]
We currently only support HTTP proxies, but Qt does support Socks5, so I think we'd just need new configuration options. I would merge a tested, well-factored pull request which adds Socks5 support.

Here's Qt's documentation: http://qt-project.org/doc/qt-4.8/qnetworkproxy.html#socks5
