### ISSUE TITLE
Upgrading to 1.3.1 from 0.14.2 resulted in some failing tests (but not in Selenium)

### ISSUE THREAD

**Issue by andrewhavens** [thoughtbot/capybara-webkit#708]
I recently upgraded from capybara-webkit 0.14.2 to 1.3.1 and some of my tests are now failing. The strange thing is that they are not failing when I run with the selenium driver. I'm wondering if there was some sort of API change which caused this.

Here is a sample of my test:

    Given I am checking out
    When I fill out my payment information
    Then I should see the order confirmation page

It fails to go the order confirmation page:

```ruby
When /^I fill out my payment information$/ do
  within '.step-2.wrapper' do
    fill_in 'Card number', with: '4111111111111111'
    fill_in 'Name on card', with: 'First Last'
    select '1', from: 'order_payment_attributes_exp_month'
    select (Date.today + 1.year).year, from: 'order_payment_attributes_exp_year'
    fill_in 'Card verification', with: '123'
    check 'Use shipping address'
    fill_in 'Email', with: 'email@example.com'

    # expect to make external request to order server
    stub_request(:post, "http://test-order-server.example.com/order")
    click_on 'Place Order'
  end
  page.current_path.should == '/order/confirmation' # <== fails for capybara-webkit but not selenium
end
```

**Comment by andrewhavens** [comment]
I've narrowed it down to the `check 'Use shipping address'` line. It appears that capybara-webkit is not checking the box, causing the form validation to fail.

**Comment by andrewhavens** [comment]
It sounds like #669 is related to the same issue.

**Comment by andrewhavens** [comment]
This issue seems to be related to some JavaScript shenanigans. The checkbox is not visible until the user fills out their shipping address and clicks the "next" button.

Indeed, I found a workaround that involved regaining focus prior to checking the checkbox:

    find(:xpath, '//body').click

**Comment by mhoran** [comment]
In capybara-webkit 1.0.0, we switched to using native events for clicks and text entry. This was required for Qt 5 file uploads, but in general is more realistic for testing Web interactions.

There's not much we can do about clicking invisible elements, as they cannot be located and cannot be clicked by our virtual mouse. I'd recommend ensuring that your test steps are triggering visibility as expected.

**Comment by netwire88** [comment]
Does this apply thing things like Bootstrap modal windows? I'm getting:

```
Capybara::Webkit::ClickFailed:
       Failed to click element /html/body/div[5]/div[2]/div/form[@id='form-1']/div[4]/input because of overlapping element /html/body/div[5]/div[1] at position 1061, 406;
```

**Comment by calleerlandsson** [comment]
Since there's not much we can of about clicking invisible elements, I'll close this issue for now.
