### ISSUE TITLE
Inconsistent cache behavior between Qt 4.8 and 5.4

### ISSUE THREAD

**Issue by Intrepidd** [thoughtbot/capybara-webkit#713]
Hi,

I'm running latest capybara-webkit on OSX Yosemite with qt 5.4 (``brew install qt5``)

Some specs that passed with qt 4.8 seem to fail with qt5.2 due to a cache problem.

Requests that were not cached with 4.8 seem to be cached now.

It's an ajax POST request that does not set an expiry date, my specs ensure that it's called twice, but it's only called once.

I've searched for a way to disable webkit cache via capybara-webkit but did not find one.

Is there another solution ?

Thanks

**Comment by Intrepidd** [comment]
updated title & body

**Comment by jferris** [comment]
Is there any way you could put together a small test case to show this behavior? I'm not aware of new caching behavior in Qt 5, and I haven't run into this issue, so I'm not sure how to reproduce the problem.

**Comment by Intrepidd** [comment]
Alright I'll set up a minimal repo to try and reproduce the issue and I'll
keep you posted

**Comment by mhoran** [comment]
Fixed in master.
