### ISSUE TITLE
webkit_server process steals focus on OS X Yosemite and Qt5

### ISSUE THREAD

**Issue by bforma** [thoughtbot/capybara-webkit#715]
Hi,

First off, great gem! 

However, whenever I run specs with rspec that are marked with `:js`, the spawned `webkit_server` process(es) seem to be 'stealing' the focus away from my terminal (iterm2). I've been Googling to find a solution, as it's quite annoying, having to command-tab back to my terminal while specs are running. But alas, I haven't found a fix yet.

Do you have any suggestions on how to fix this?

I'm using:

capybara-webkit 1.3.0
capybara 2.44
rspec 2.14.1
Mac OS X Yosemite (10.10.1)
Qt 5.3.2

Thanks!
Bob

**Comment by derekkraan** [comment]
I have also been having this problem. Only it's not just in the terminal, it's for all apps. I've lost keyboard focus a few times already just writing this comment.

**Comment by mhoran** [comment]
Thanks for looking into this. I don't run OS X myself but have seen the issue on coworkers machines. It's certainly quite annoying -- but we now have a fix! I'll be releasing 1.4.1 shortly with some additional fixes.

**Comment by bforma** [comment]
Great, thanks! And glad to help.
