### ISSUE TITLE
Crash in Qt 4.8.6 after Yosemite upgrade

### ISSUE THREAD

**Issue by dougo** [thoughtbot/capybara-webkit#720]
Hi, I've been getting Qt crashes in capybara-webkit and I'm not sure what to do about them. Our CI server runs our app tests on a Mac Mini, which I just upgraded to Yosemite. I reinstalled Qt 4.8.6 (via brew), and reinstalled the capybara-webkit gem (1.4.1), but we're still getting the crash. The tests run fine on my MacBook Pro, which I also upgraded to Yosemite a few weeks ago, and I can't figure out what is different in the two environments that would cause this... Anyway, here's the crash output. Any help debugging this would be greatly appreciated!
```
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
2015-02-02 18:07:59.524 webkit_server[60362:6996041] *** -[__NSArrayI objectAtIndex:]: index 0 beyond bounds for empty array
2015-02-02 18:07:59.526 webkit_server[60362:6996041] (
	0   CoreFoundation                      0x00007fff97bb566c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8b6d876e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff97a8e7de -[__NSArrayI objectAtIndex:] + 190
	3   QtGui                               0x0000000101c43035 _ZN28QDesktopWidgetImplementation8onResizeEv + 123
	4   QtGui                               0x0000000101c42f50 _ZN28QDesktopWidgetImplementationC2Ev + 54
	5   QtGui                               0x0000000101c432f4 _ZL28qdesktopWidgetImplementationv + 60
	6   QtGui                               0x0000000101c437c3 _ZNK14QDesktopWidget14screenGeometryEi + 13
	7   QtGui                               0x0000000101c3fb8f _Z29qt_mac_getTargetForMouseEventP7NSEventN6QEvent4TypeER6QPointS4_P7QWidgetPS6_ + 140
	8   QtGui                               0x0000000101c1e30b _Z20qt_mac_update_cursorv + 143
	9   QtGui                               0x0000000101c45ceb _ZN26QEventDispatcherMacPrivate14firstLoopEntryEP19__CFRunLoopObservermPv + 15
	10  CoreFoundation                      0x00007fff97ad2da7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	11  CoreFoundation                      0x00007fff97ad2d00 __CFRunLoopDoObservers + 368
	12  CoreFoundation                      0x00007fff97ac483f CFRunLoopRunSpecific + 271
	13  HIToolbox                           0x00007fff8ae6caef RunCurrentEventLoopInMode + 235
	14  HIToolbox                           0x00007fff8ae6c76e ReceiveNextEventCommon + 179
	15  HIToolbox                           0x00007fff8ae6c6ab _BlockUntilNextEventMatchingListInModeWithFilter + 71
	16  AppKit                              0x00007fff8f2dff81 _DPSNextEvent + 964
	17  AppKit                              0x00007fff8f2df730 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 194
	18  AppKit                              0x00007fff8f2d3593 -[NSApplication run] + 594
	19  QtGui                               0x0000000101c44f18 _ZN19QEventDispatcherMac13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE + 1522
	20  QtCore                              0x000000010288c6f1 _ZN10QEventLoop13processEventsE6QFlagsINS_17ProcessEventsFlagEE + 77
	21  QtCore                              0x000000010288c870 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 370
	22  QtCore                              0x000000010288f51f _ZN16QCoreApplication4execEv + 199
	23  webkit_server                       0x0000000100007386 main + 390
	24  webkit_server                       0x0000000100002fd4 start + 52
	25  ???                                 0x0000000000000001 0x0 + 1
)
```

**Comment by dougo** [comment]
By the way, I have also tried upgrading to qt5, in the past and recently, and I've never gotten it to work...  I can file a separate issue if you think that's my best avenue of progress.

**Comment by mhoran** [comment]
Thanks for the detailed crash report, @dougo. It looks like something went wrong inside of Qt itself. I'd like to see if we can get Qt 5 working, as this issue may have been addressed in a newer release of Qt.

The easiest way to get up and running is by downloading the installer from http://www.qt.io/download-open-source/. I've found Brew packages always have some issue or another, but I've had good luck with the official binaries. Once installed, all you need is the path to the `qmake` binary. Once you have that, simply set `QMAKE=$PATH_TO_QMAKE_BINARY`, and install. You'll only need to set the environment variable when installing/upgrading capybara-webkit. The loader should be able to find the libraries on its under normal circumstances.

**Comment by jferris** [comment]
At this point, I really think we should require Qt 5 in the next major release. It's widely available, and there are consistent complaints of issues with Qt 4.

**Comment by mhoran** [comment]
Sounds good to me. I just verified that our CI provider supports Qt 5, and we already know how to install it on Travis. Unfortunately it seems some of the distro packages for Qt 5 are busted, so I'd continue to recommend users install from the official binaries at qt.io.

**Comment by jferris** [comment]
@dougo have you had any luck with Qt 5? If Qt 5 isn't working, can you create a separate issue?

We're going to be dropping support for Qt 4 soon, so I don't plan on debugging any further issues with it.
