### ISSUE TITLE
Qt version not detected on windows (in webkit_server.pro)

### ISSUE THREAD

**Issue by weedySeaDragon** [thoughtbot/capybara-webkit#726]
I'm unable to build the gem. I'm not able to get through a make yet.  The first error is that the code in `webkit_server.pro` is not picking up my version of QT. 
I'm running on Windows 7.
I'm using Qt version 4.8.5

When I put the following into webkit_server.pro and then just run `ruby extconf.rb`
```message("QT major =$$QT_MAJOR_VERSION"=)

message("QT minor =$$QT_MINOR_VERSION"=)```

I get:
```
cd src/ && c:/Qt/qt-4.8.5-x86-mingw/bin/qmake.exe c:/rubys/ruby-2.0.0-p598-i386-mingw32/lib/ruby/gems/2.0.0/gems/capybara-webkit-1.4.1/src/webkit_server.pro -spec c:/Qt/qt-4.8.5-x86-mingw/mkspecs/win32-g++ -o Makefile.webkit_server
Project MESSAGE: QT major ==
Project MESSAGE: QT minor ==
Project ERROR: At least Qt 4.8.0 is required to run capybara-webkit.
Command 'make qmake' failed
make: *** [sub-src-webkit_server-pro-qmake_all] Error 2
```

If I delete the lines that check the version of QT, the build continues past this point. (Then fails later.<sigh>) 

I suspect that because I'm running on windows, the version of QT isn't getting detected correctly.  Where and how are the values for QT_MAJOR_VERSION and $QT_MINOR_VERSION detected and set?

**Comment by mhoran** [comment]
Hey @weedySeaDragon. It can be a bit difficult to get capybara-webkit running on Windows, but it's possible. I just confirmed that master successfully compiles on Windows 7.

First off, you'll need a working Ruby install, which it seems you've already got. On top of that, you'll need the RubyInstaller [DevKit](http://rubyinstaller.org/downloads/). The DevKit will get you a working mingw compiler.

I've got Qt 4.8.1 installed on my system, but anything from 4.8 on (5.3 preferred) should work. With Ruby, DevKit, and the Qt bin directory in your PATH, installing the gem should "just work". There is a file called 'devkitvars.bat' in the DevKit directory which should set up just about everything required to get the compiler working. Then you just need to add the Qt bin directory to your PATH.

**Comment by weedySeaDragon** [comment]
Hi @mhoran -- thanks for the quick response. I was able to get it working.  Short version: I found a problem with my Qt install: although it was in my path and qmake would run (I could do `qmake -v` and get output), *that wasn't enough.*  The variables that Qt uses for paths (e.g. QT_INSTALL_HEADERS, etc.) were not correct.  I had to run the Qt configuration program **configure.exe**.   That correctly set all of the Qt variables and all was fixed.

I figured that it must be some kind of issue on my end, since I saw that others have installed it successfully.  I went through each of the components required to verify the installation and setup -- and found the problem. I've been able to compile gems just fine using just DevKit, so suspected that it had something to do with Qt. (and it did)  In case it's helpful to others, here's what I did to check and verify each component:
 -  DevKit: made sure it was installed in the ruby versions needed, and verified that it worked:
    1. checked '<devkit install dir>/devkit/config.yml' to make sure it listed each of different installed ruby versions, and then
    2. re-ran the DevKit install script (`ruby dk.rb install`) to be sure that DevKit had installed the right files into each of those ruby versions.
    3.  I verified that DevKit was working using the recommendation on the DevKit page [https://github.com/oneclick/rubyinstaller/wiki/Development-Kit]:  I installed the json gem.  It was able to build the native version so that verified that DevKit was installed and working properly.

- Qt: I downloaded the Qt files (I used 4.8.5; glad to know I can upgrade). I ran the .exe file downloaded to install them.
    1. made sure that Qt directories were in my path (see the list below).  
    2. made sure that the environment variable `QMAKESPEC` was defined:` QMAKESPEC=win32-g++`
    3. ran `qmake -version` to verify that qmake would run and to verify the version
    4. ran `qmake -query` to verify the set-up for Qt.  This is where I saw the problem with my Qt install: the paths were all wrong.
    5. ran the Qt `configure.exe` program to fully configure my Qt install. **This was the key step.**  *(I thought that the initial installation program would have configured things, but obviously it didn't.)* Running this will build *all of the demos and examples* and so takes a while.  But when it completed, all was well.
    6. ran `qmake -query` to verify that the Qt settings and been fixed and were correct.  (success!)

- system path and ENV variables: the following need to be in your path:
    - [devkit dir] (ex: `C:\rubys\devkit-mingw64-32-4.7.2`)
    - [devkit dir]\mingw\bin;
    - [devkit dir]\bin;
    - [qt dir] (ex: `C:\Qt\qt-4.8.5-x86-mingw')
    - [qt dir]\bin;
    - [ruby version]\bin (ex: `C:\rubys\ruby-2.0.0-p598-i386-mingw32\bin`)
    - [ruby version]\lib\ruby\gems\<version> 
    - define the environment (system) variable `QMAKESPEC=win32-g++`  (If you don't give qmake/Qt the specification about which  system to build for, it will look for this ENV.)
