### ISSUE TITLE
Reset Basic Authentication within same driver lifespan

### ISSUE THREAD

**Issue by nritholtz** [thoughtbot/capybara-webkit#735]
I'm currently using basic authentication using:
```
 page.driver.browser.authenticate(username, password)
```

However, when I want to change credentials within the same driver duration, I can't simply recall the method. When I do so, visiting the page is still using the previous credentials.

Is there some way to do so using Capybara Webkit? A workaround in Selenium I've used was by calling `Capybara.current_session.driver.quit` within my hooks, however, in my opinion even that is inefficient.

Also, I have tried using `page.driver.browser.manage.delete_all_cookies`,  although I'm fairly sure Basic Auth isn't using cookies.

**Comment by jferris** [comment]
This seems like a glitch from how we interact with Qt.

We save the username and password given in `authenticate`. Qt will trigger [`authenticationRequired`](http://qt-project.org/doc/qt-4.8/qnetworkaccessmanager.html#authenticationRequired) when it hits a page that needs credentials, but it looks like it only asks once:

> QNetworkAccessManager will cache the credentials internally and will send the same values if the server requires authentication again, without emitting the authenticationRequired() signal. If it rejects the credentials, this signal will be emitted again.

We could try:

* [Clearing the cache](http://qt-project.org/doc/qt-4.8/qabstractnetworkcache.html#clear) after setting a new username and password.
* Creating a new `NetworkAccessManager` whenever the username and password are changed.

@nritholtz are you interested in trying your hand a pull request to fix this?

**Comment by nritholtz** [comment]
Hey @jferris 
I tried my hand at using the clear cache method, but for some reason it always crashed the webkit server when called during authenticate. I have a feeling because other request related information was stored in there, but I'm not 100% sure. I also tried to get a new `NetworkAccessManager`, however I couldn't get it working, mostly because I'm new to this framework.

I did however notice, that there was a method introduced in QT5, [clearAccessCache](http://doc.qt.io/qt-5/qnetworkaccessmanager.html#clearAccessCache). I haven't tried it against QT4.8, but I assume it was only introduced in QT5, so it won't work. However, this is exactly what I needed and it also passed all specs (including my new one for this scenario).

I have it committed to my fork, https://github.com/nritholtz/capybara-webkit/, however I'm sure you won't want to merge it until QT4 support is dropped. Please let me know if there's anything I can do, or if someone else wants to take a shot at making a modification with QT4 support as well.

**Comment by jferris** [comment]
@nritholtz thanks a bunch for digging into this! If you can add `#if QT_VERSION >= QT_VERSION_CHECK(5, 0, 0)` around that line to keep it compiling on Qt 4 for now, I think this would b e a good fix to merge.

**Comment by nritholtz** [comment]
Hey @jferris, is there a way to check the QT version inside the driver_spec.rb? I want to make sure the spec doesn't fail if ran against QT4 on Travis.

**Comment by jferris** [comment]
We don't currently run the specs against Qt 4 on Travis (https://github.com/thoughtbot/capybara-webkit/blob/master/.travis.yml). There isn't an obvious way to check in the specs (we could inspect `driver.version`).

Maybe we should just add `skip_on_qt4: true` to that spec, and we can pass that flag to rspec if we want to run th e specs on Qt 4?

I think we're very close to only supporting Qt 5, anyway.

@mhoran any thoughts?

**Comment by mhoran** [comment]
@jferris, we do actually build against Qt 4 on Travis, though it's not apparent. The default Qt install is still 4, and the `include` configuration overrides that for two builds. See `before_install` as well.

`skip_on_qt4` seems like a reasonable option. We could check the Qt version via `%x(#{CapybaraWebkitBuilder.qmake_bin} -v).match(/Using Qt version 4/)`, which should give us an accurate Qt version, at least on CI.

**Comment by nritholtz** [comment]
Thanks @mhoran and @jferris for your help. PR #762 was created for this issue.

**Comment by jferris** [comment]
Thanks again! As mentioned on #762, this was merged into master as e49176b.
