### ISSUE TITLE
all font-families rewritten to 'Arial' breaks Foundation modals closing

### ISSUE THREAD

**Issue by Masa331** [thoughtbot/capybara-webkit#736]
We had problems with testing Foundation modals because with capybara-webkit they would never close although it works with selenium for example.

We'v tracked it down through Foundation where we found that on some event(`'closed.fndtn.reveal'`) it  closes all opened reveals which it finds by some css selector `'[data-reveal].open'`. Now the data attribute can be namespaced so it prevents collision with some other frameworks etc. If it is namespaced then the selector looks like this: `'[data-namespace-reveal].open'`.

The problem is that Foundation's javascript gets the namespace from css where it is set in html meta tag's css font-family.
Foundation's js: https://github.com/zurb/foundation/blob/master/js/foundation/foundation.js#L385

But capybara-webkit sets all font-families to `Arial` here: https://github.com/thoughtbot/capybara-webkit/blob/86e422f94422d39e537329d64d7bfe8f6360bd8b/src/WebPage.cpp#L113

So Foundation asumes that there is a namespace `Arial` and it's css matchers for modal looks like this `'[data-Arial-reveal].open'` which selects nothing and then no modal is closed...

Fortunately we don't need namespace data attributes so we set `Foundation.global.namespace = ''` in Foundatiion's js configuration but i'm not sure it's really kosher

So i'm thinking, why it is that all font-families are set to `Arial` in capybara-webkit and shouldn't it be at least configurable if you want to rewrite all font-families or not?

**Comment by mhoran** [comment]
Hey @Masa331. Please see #728. Due to a bug in Qt 4.8 on Mac OS X, all font families are overridden. This is handled via a user stylesheet in `WebPage.cpp`.

Until support for Qt 4.8 is dropped, this user stylesheet will remain in place. You may work around this by forking the project and removing the user stylesheet from `WebPage.cpp`.

**Comment by Masa331** [comment]
Ah ok i see. Thank you for reply. I will close this as we have our solution. We will wait for next version.

**Comment by wrzasa** [comment]
I'm not sure If I get it right. Could you confirm/correct?

You simply made all other fonts (like e.g. font awsome) not available in tests for all OSes and QT versions (and thus cause false `ClickFailed` errors rendering capybara tests unreliable) just to workaround a bug on a specific QT version on a specific OS? And hardocoded this workarround not trying to detect if running on this specific OS and not giving a option to easily turn this off?

**Comment by mhoran** [comment]
Yes.

On May 30, 2017 8:49:17 AM EDT, wrzasa <notifications@github.com> wrote:
>I'm not sure If I get it right. Could you confirm/correct?
>
>You simply made all other fonts (like e.g. font awsome) not available
>in tests for all OSes and QT versions (and thus cause false
>`ClickFailed` errors rendering capybara tests unreliable) just to
>workaround a bug on a specific QT version on a specific OS? And
>hardocoded this workarround not trying to detect if running on this
>specific OS and not giving a option to easily turn this off?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/thoughtbot/capybara-webkit/issues/736#issuecomment-304867718

-- 
Sent from my mobile device.

**Comment by wrzasa** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/3/3b/Paris_Tuileries_Garden_Facepalm_statue.jpg)
