### ISSUE TITLE
Silence unknown URL warning

### ISSUE THREAD

**Issue by nritholtz** [thoughtbot/capybara-webkit#744]
As part of the blocked URL feature, we added a [warning](https://github.com/thoughtbot/capybara-webkit/commit/3804dd54060e7d2c3e96560b4b52cc74259b349d#diff-470fce27a79450cb7ecad3b9bcd30c70R22) by default if the user never sets a block mode. 

As part of my project, I make alot of calls to remote sites, so I don't want to use this feature. However, my logs become extremely messy when updating capybara-webkit, since it becomes filled with these warning messages.

Is it possible to add a call to silence these warnings? I haven't tried it out yet, but I guess a work-around for now is to use a wild-card, i.e. `driver.allow_url("*")`. I'm just not sure this is the best approach.

**Comment by jferris** [comment]
I think using `driver.allow_url("*")` is the way to go. If this is a problem for enough people, I'd be fine having a `driver.allow_any_url` method around.
