### ISSUE TITLE
Tests with `js: true` fail, even with threading monkey patch applied

### ISSUE THREAD

**Issue by onebree** [thoughtbot/capybara-webkit#745]
**Rails 4.2.0, RSpec 3.1, Capybara 2.4.4, Capybara Webkit 1.5.0**

**ISSUE**: On specs without `js: true`, calling `click_link "Access Numbers"` (from navigation bar) works just fine. On specs with that flag, it cannot find the link to click. We need this to work, as doing so tests that our navigation bar works (permissions-based view), since calling `visit access_numbers_path` does not exercise that.

**DEGUB GIST**: https://gist.github.com/onebree/dfe2033eb17cb1bc67e3

I updated from gem version 1.3.1 today, and am still experiencing the issue. We use Spring when running our tests. We have the monkey patch below applied in `config/spring.rb`, as well as one of mysql's gem files modified. If any test includes `js: true`, it fails. We think it is because of threading issues with database querying, but our backtrace does not include such error.

**Comment by jferris** [comment]
@onebree it looks like the link you're trying to click on is invisible. Although rack-test will click on these (because it doesn't understand CSS), most JavaScript drivers can only click on links which are visible. If you look at the debug log, you can see that it repeatedly looks for a link, finds one, and then discovers that it's not visible.

**Comment by onebree** [comment]
@jferris Since I posted this issue, I have modified my tests and some helper methods. I will get back to you whether there are any changes. (I have been working on a different task since then.)

**Comment by jferris** [comment]
I'm going to close this for now, as it doesn't seem like a bug in capybara-webkit. Please report back if you're still running into this issue.

**Comment by onebree** [comment]
I completely forgot about this issue, because I fixed it I guess. Thanks for closing it!
