### ISSUE TITLE
Global block_unknown_urls and allow_url configuration

### ISSUE THREAD

**Issue by greggroth** [thoughtbot/capybara-webkit#747]
Is there an intended way to use `block_unknown_urls` and `allow_url` without crowding the tests with repeated use?  I'd expect to be able to configure this for the driver globally in the spec helper, but that doesn't appear to be the intended use.  What are your thoughts on this?

**Comment by firedev** [comment]
Just wanted to ask this as well. How do I put it into my `rails_helper` ?

**Comment by mhoran** [comment]
Check out #717. Closing this out, and we'll try to kickstart the other conversation. Thanks!
