### ISSUE TITLE
Driver performance degradation on Rails 4.2

### ISSUE THREAD

**Issue by rwz** [thoughtbot/capybara-webkit#748]
Our test suite runs in 19 minutes instead of 3 since we've upgraded to Rails 4.2.1 from 4.1.9

The javascript driver performance is the main culprit here. For instance, on 4.1.9 the first css selector find returns in 0.7 seconds, but on 4.2.1 it returns in 11+ seconds. Sometimes the RJS request takes longer than 5 seconds to evaluate on the capybara-webkit client (Rails actually renders and returns it in under 10ms).

We were able to reliably recreate this performance degradation across multiple OS X machines.

We're using Ruby 2.2.1

**Comment by jferris** [comment]
Is this problem reproducible using Selenium or another JavaScript driver?

Can you attach a `:webkit_debug` log of a slow scenario?

**Comment by rwz** [comment]
Poltergeist behaves pretty much the same. It's originally a little slower on 4.1 and an order of magnitude slower on 4.2. 

Our benchmark cucumber story runs in 1 minute seconds on 4.1 and in 4 minutes 27 seconds on 4.2

Here's the debug log for both runs: https://gist.github.com/rwz/baedf8d802ad7e14c82d

**Comment by jferris** [comment]
@rwz I just released 1.5.2. The 1.5 series includes some cache changes which may improve performance. Can you give the latest release a try?

**Comment by jferris** [comment]
I'm going to close this, as I believe the performance issues will be resolved by caching improvements. Please comment again if you're still seeing a regression between versions.
