### ISSUE TITLE
Centos 7 - qtwebkit-devel not available

### ISSUE THREAD

**Issue by mowat27** [thoughtbot/capybara-webkit#749]
Hi,

I'm trying to install capybara-webkit on centos 7 as per the instructions at https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#centos-7 but I'm getting an error 

```
$ who am i
root     pts/1        2015-04-03 13:11 (192.168.33.1)
$ yum install qtwebkit-devel
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.bytemark.co.uk
 * extras: mirror.simwood.com
 * updates: centos.openitc.uk
No package qtwebkit-devel available.
Error: Nothing to do
```

## Steps to reproduce
```
mkdir capybara-webkit-issue
cd capybara-webkit-issue
vangrant box add chef/centos-7.0 
vagrant init
vim Vagrantfile # enable the chef/centos-7.0  box
vagrant up
vagrant ssh

sudo su -
yum install qtwebkit-devel
```

**Comment by jferris** [comment]
I'm not familiar with the Centos mirror/package system, but I see a number of search results under "Centos 7" for "qtwebkit" - http://pkgs.org/search/qtwebkit

Unfortunately, the maintainers don't have the resources to debug Qt install issues for every system, and none of us use Centos, so there isn't much we can do to help you debug this.

If you do discover a better way to install on Centos 7, it would be helpful to future users if you could update the wiki. We rely on members from the community to document the install steps for each system.

**Comment by ericenns** [comment]
Don't mean to drag up an old thread but the fix for this is to install epel-release first, since the package qtwebkit-devel is from epel.

```bash
yum install -y epel-release
yum -y update
```

**Comment by mowat27** [comment]
@ericenns thanks!  I've been building from source, but this could be handy
