### ISSUE TITLE
Not working with Devise login_as helper

### ISSUE THREAD

**Issue by collimarco** [thoughtbot/capybara-webkit#751]
I'm using Rails 4.2, Rspec 3.2.2, Capybara 2.4.4 and **Devise** 3.4.1 (i.e. the latest versions).

I have a feature test that works with selenium while it fails with capybara-webkit. Even manually everything works fine.

The problem is with authentication.

Following the instructions in Devise wiki (https://github.com/plataformatec/devise/wiki/How-To:-Test-with-Capybara#capybara-webkit) I have written this test:

```
feature "Skills" do
  given(:user) { create(:user) }
  scenario "Add some skills", js: true do
    login_as user, scope: :user, run_callbacks: false
    visit '/'
    # user is logged in
    click_link 'Add skill'
    # after following the link the user is no longer logged in
    fill_in 'Name', with: 'Web development'
    # error: instead of the form with the name field there is the login form
    ...
  end
end
```

When I say that the user is logged out, is because it gets redirected to the login page (I can verify that using `print page.html`).

I've notice that the user is logged in after the first `visit '/'` (or any other page), but is **no longer logged in after a second `click_link`or `visit`**.

**Comment by mhoran** [comment]
Have you tried the latest version of capybara-webkit (1.5.0)? There was an issue with caching in previous versions which would cause issues like this.

**Comment by collimarco** [comment]
Oops, sorry it's my fault. The same issue seems to occur with Selenium (probably with Selenium I had tested a slightly different version). The problem is with transactional fixtures. Maybe I'll investigate further, but for now I close this issue as it seems to be my fault.
