### ISSUE TITLE
Re-enable custom fonts

### ISSUE THREAD

**Issue by jferris** [thoughtbot/capybara-webkit#761]
I've been assuming that we'll allow custom fonts once we fully move to Qt 5. It seems like a good idea to enable this for Qt 5 users ahead of the big switch to make sure this is actually going to work, and then just enable it unconditionally in the 2.0 release.

@mhoran any thoughts?

**Comment by mhoran** [comment]
I'd prefer to defer until a release candidate, as I'm a bit uneasy about introducing differences between identical c-w versions based on Qt version. We've been careful to minimize those differences to date, but it's also possible users won't install the RC and would then be surprised in the final release regardless.

**Comment by jferris** [comment]
Alright, I moved it to the 2.0.0 milestone. I'm mostly interested in proving that the crash is fixed on Qt 5.

**Comment by mhoran** [comment]
I'm almost positive I tested this out back when I had access to an OS X machine. I also found that the text rendering implementation changed significantly between Qt 4 and 5 and could not reproduce the crash.
