### ISSUE TITLE
Change event has incorrect event.target on <select>

### ISSUE THREAD

**Issue by jakecraige** [thoughtbot/capybara-webkit#763]
The `event.target` on a select's change event is the option element you selected rather than the select itself. This differs from how modern browsers have it implemented.

In capybara-webkit, using `page.driver.console_messages` we get this:

```js
$(".selector").change(function(e) {
  console.log(e.target); // [object HTMLOptionElement]
  console.log(this);       // [object HTMLSelectElement] 
});
```

In chrome/firefox you can run this snippet in the console and see it's different:

```js
var select = $("<select />");
select.change(function(e) {
  console.log("e.target: " + e.target); // [object HTMLSelectElement] 
  console.log("this: " + this);              // [object HTMLSelectElement] 
}).change();
```

**Comment by jferris** [comment]
Can you include the output from `puts page.driver.version`?

Is there a small rspec example you can put together which fails using capybara-webkit but passing using Selenium?

**Comment by mockdeep** [comment]
I just ran into this too. Looks like [poltergeist has the same problem](https://github.com/teampoltergeist/poltergeist/issues/204). The test runs fine in selenium but breaks in capybara webkit. I'll work on a simple repro.

**Comment by mockdeep** [comment]
Okay, I think I have a repro. I added it to the specs [here](https://github.com/mockdeep/capybara-webkit/commit/7dedaa2d97ddf216481ec883842fee412caba3fd). @jferris let me know if you want me to pull request that or something.

**Comment by jferris** [comment]
@mockdeep thanks!

If you're interested in trying to get the failing spec passing, I'd certainly take a pull request for that. If not, I'll dig into it when I can and I can use your specs as a starting point.

**Comment by mockdeep** [comment]
@jferris I'll take a look, but I suspect it's over my head (and availability).

**Comment by jferris** [comment]
@mockdeep no worries. The code to select an option is here: https://github.com/thoughtbot/capybara-webkit/blob/master/src/capybara.js#L325

It's possible we'll have to switch to using some kind of native events to make it work correctly.

**Comment by mockdeep** [comment]
Ha, I was just looking at that. I was thinking it might be in C, but JS is a little less intimidating. I'll see what I can come up with.

**Comment by mockdeep** [comment]
@jferris I spent a while at this but haven't had any luck. Poltergeist [just merged a pull](https://github.com/teampoltergeist/poltergeist/pull/581) that fixes their implementation for me, so I thought I'd try to emulate that, but not seeing any changes in the events. Here's an unpolished cut of what I was trying:

```js
  selectOption: function(index) {
    var node = this.getNode(index);
    var parentNode = node.parentNode;
    if (parentNode.value === node.value) {
      return false;
    }
    var eventObject = document.createEvent("HTMLEvents");
    eventObject.initEvent('focus', true, true);
    node.dispatchEvent(eventObject);
    node.selected = true;

    eventObject = document.createEvent("HTMLEvents");
    eventObject.initEvent('changed', true, true);
    parentNode.dispatchEvent(eventObject);

    eventObject = document.createEvent("HTMLEvents");
    eventObject.initEvent('blur', true, true);
    node.dispatchEvent(eventObject);

    return true;
  },
```

Any thoughts?

**Comment by jferris** [comment]
@mockdeep did you make sure to re-compile the driver after modifying the JavaScript? That `capybara.js` file gets compiled into the server binary.

**Comment by mockdeep** [comment]
Ah, that would explain why I was getting absolutely no change in the test output. Let me play around with that for a bit.
