### ISSUE TITLE
webkit_server may crash on premature click

### ISSUE THREAD

**Issue by eiseneker** [thoughtbot/capybara-webkit#765]
Hi all,

Couldn't tell if this was related to an outstanding issue. I've been running into a problem when getting our test suite loaded onto a new CI server:

Mac Pro / Yosemite
Ruby 2.1.2
capybara-webkit v. 1.5.0
Qt 5.4.1 (from brew)

We have a certain spec which works fine under most conditions, but fails in a Jenkins shell. The test case is to assert that a user can open a "collapsible" div, and then click a link inside of it. What we're finding is that the process crashes if we try to click the link too soon, perhaps before the CSS transition has finished.

**Debug log:**

Received "FindXpath(//h2[contains(text(),'Dress Details')])"
Started "FindXpath(//h2[contains(text(),'Dress Details')])"
Finished "FindXpath(//h2[contains(text(),'Dress Details')])" with response "Success(5)"
Wrote response true "5"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success(6)"
Wrote response true "6"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "Node.leftClick"
Started "Node.leftClick"
Finished "Node.leftClick" with response "Success()"
Wrote response true ""
Received "FindXpath(.//a[./@href][(((./@id = 'Ball Gown' or normalize-space(string(.)) = 'Ball Gown') or ./@title = 'Ball Gown') or .//img[./@alt = 'Ball Gown'])])"
Started "FindXpath(.//a[./@href][(((./@id = 'Ball Gown' or normalize-space(string(.)) = 'Ball Gown') or ./@title = 'Ball Gown') or .//img[./@alt = 'Ball Gown'])])"
Finished "FindXpath(.//a[./@href][(((./@id = 'Ball Gown' or normalize-space(string(.)) = 'Ball Gown') or ./@title = 'Ball Gown') or .//img[./@alt = 'Ball Gown'])])" with response "Success(7)"
Wrote response true "7"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "Node.leftClick"
Started "Node.leftClick"

An error occurred in an after hook
  Errno::EPIPE: Broken pipe
  occurred at /Users/Shared/Jenkins/.rvm/gems/ruby-2.1.2/gems/capybara-webkit-1.5.0/lib/capybara/webkit/connection.rb:30:in `write'

**Rspec error (slightly different):**

  1) Wedding Dress Detail Page (Mobile) 
     Failure/Error: click_link 'Ball Gown'
     EOFError:
       end of file reached
     Shared Example Group: "a wedding dress detail page" called from ./spec/features/mobile/wedding_dress_detail_spec.rb:4
     # ./spec/support/shared_examples/features/product_pages/a_wedding_dress_detail_page.rb:36:in `block (3 levels) in <top (required)>'

**Implementation:**

```ruby
node = page.all(:xpath, "//h2[contains(text(),'#{text}')]").first 
node_parent = node.find(:xpath, '../..') 
node_parent.click #click collapsible element

click_link 'Ball Gown' #click inner element, causes crash
```

Inserting a sleep before that second click appears to help, which supports the idea that it needs to wait for the animation to complete, even though it can see the second link.

I hope this is useful. Please let me know if there is anything else I can provide.

Thanks!

Eric

**Comment by mhoran** [comment]
Hey @eiseneker. Would you be able to extract a test case which triggers this crash? Hopefully that will make it easier to reproduce and debug.

When encountering issues with animations in the past, I've disabled all animations in the test environment.

**Comment by eiseneker** [comment]
Hey all. Tested again vs. the latest gem, and no problems now. Thanks!
