### ISSUE TITLE
Cookie/session problem with AJAX requests

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/capybara-webkit#766]
I am having a problem that I've narrowed down to some kind of issue with Capybara-webkit not remaining logged in when making requests. The spec works with Selenium-webdriver, but fails with Capybara-webkit. Here's what's happening:

1. Visit page that requires authentication (using Clearance's backdoor `as: user`)
2. Page makes AJAX requests
3. With `webkit_debug`, I see that the user successfully ends up on the correct page (page returns 200 when requested), but all the AJAX requests (which require authentication) come back with 401 errors. In the application log, Clearance is blocking the AJAX API requests with `Filter chain halted as :require_login rendered or redirected`

My app uses Rails 4.2.1, Clearance 1.9.0, Capybara-webkit 1.5.0, and Qt 5.4.1.

*Update:*
If I attempt the same spec but try to sign in manually, despite filling in the correct credentials, Clearance redirects me back to the sign-in page (because it thinks I'm not signed in), and this happens only with Capybara-webkit, not Selenium-webdriver.

**Comment by jferris** [comment]
Is it possible that capybara-webkit and Selenium are sending different `Content-Type` or `Accept` headers?

**Comment by geoffharcourt** [comment]
@jferris, wish I had thought to look there, but that doesn't seem to be the cause. `HTTP_ACCEPT` and `Content-Type` appear to be the same in the headers on both browsers.

Selenium headers:
```ruby
"HTTP_ACCEPT"=>"application/json, text/javascript, */*; q=0.01"
"Content-Type"=>"text/html"
"HTTP_USER_AGENT"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:33.0) Gecko/20100101 Firefox/33.0"
```

Capybara-webkit headers:
```ruby
"HTTP_ACCEPT"=>"application/json, text/javascript, */*; q=0.01",
"Content-Type"=>"text/html"
"HTTP_USER_AGENT"=>"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) capybara-webkit Safari/538.1"
```

**Comment by jferris** [comment]
Could you attach a log from `:webkit_debug` and any relevant `test.log` entries?

**Comment by geoffharcourt** [comment]
@jferris, I've altered the test to make the things it's checking for as simple as possible (removing as much dependency on d3 behavior, just keeping it related to the content rendering). The Rails log, webkit_debug output, and RSpec file (just in case I'm missing something really, really obvious) are all here: https://gist.github.com/geoffharcourt/6d8c58cb3769d7ef2411

I'm continuing to investigate on my end, but if you have any further ideas as to why these specs might be failing, it would be an enormous boost.

**Comment by geoffharcourt** [comment]
Quick bump here. I've tried making some changes to my tests not to use the Clearance backdoor, and I'm finding that when I log in manually with the correct credentials that I am still being redirected back to the sign_in page. I'm continuing to investigate possible causes.

**Comment by geoffharcourt** [comment]
@jferris, I updated from 1.5.0 to 1.7.0 today, and the issue has gone away. I can't tell from the commit record what change solved the problem, but I'll post back here if I do figure it out.

Thanks for the help with the issue earlier, this was incredibly weird.
