### ISSUE TITLE
Allow urls across sessions?

### ISSUE THREAD

**Issue by iastazach** [thoughtbot/capybara-webkit#770]
I just upgraded to 1.5.1 (from 1.3.1) and was put off by the verbosity of the URL warnings.  Similar to the user in issue #744 I make a lot of remote calls, so I'd like to silence everything.  `page.driver.allow_url('*')` seems to work, unless I'm using multiple sessions within a test.  As soon as I spin up a new session (`Capybara::Session.new(Capybara.javascript_driver)`), the warnings start up again.  Is there any way to silence this globally without having to call `allow_url('*')` from within each session?

**Comment by jferris** [comment]
We recently accepted a pull request which allows for silencing all the warnings for a session: https://github.com/thoughtbot/capybara-webkit/commit/6e485ca45db7f3c559d647f15fd7863ac5ae4bbd

We're in the process of working through a global (all sessions) way of doing configuration: https://github.com/thoughtbot/capybara-webkit/pull/756

Currently, you'll need to call `allow_url` for each session. In RSpec, you can use a `before` block for this.
