### ISSUE TITLE
Feature request: Detect missing images

### ISSUE THREAD

**Issue by Fjan** [thoughtbot/capybara-webkit#776]
It would be great if capybara-webkit could report any missing or broken assets it encounters. Assuming it downloads the images already anyway, it would seem possible to create `page.driver.network_messages` similar to the already existing `page.driver.error_messages` which reports javascript errors, or perhaps simply extend `error_messages` to include network errors. 

Another way to go would be like Poltergeist which has a method `network_traffic` which returns a complete list of retrieved assets and status codes.

**Comment by jferris** [comment]
You can use the `:webkit_debug` driver, which will print a list of requests and responses.

I'm not sure this is a common enough use case that it would be useful to programatically access a list of requests. I could maybe see an option to print warnings when a server returns unacceptable response codes like 404 or 500. If we did add something like that, I'd prefer for it to be part of the official Capybara API. Let me know if you'd be interested in taking on that work, and I can walk you through it.

I'm going to close this issue, as there isn't any action for the maintainers to take. However, feel free to discuss further.

**Comment by Fjan** [comment]
Ok, thanks, I'll experiment with the webkit_debug driver. With regards to your question whether it's use is common enough, I would think that if the option exists to warn of 4XX / 5XX codes without a performance penalty then almost everyone would want it enabled by default, I can't think of many cases where you would not want to know about those in your tests.

I also agree it would be better to have that configurable at the Capybara level, but that's a bit of chicken/egg, as they probably won't create an option unless there is a driver that can handle it.

**Comment by jferris** [comment]
> With regards to your question whether it's use is common enough, I would think that if the option exists to warn of 4XX / 5XX codes without a performance penalty then almost everyone would want it enabled by default, I can't think of many cases where you would not want to know about those in your tests.

It's not uncommon for Ajax requests to expect responses in the 400 range when testing validations and other interactions. It's also part of the normal basic authentication workflow to get a 401 response.

> I also agree it would be better to have that configurable at the Capybara level, but that's a bit of chicken/egg, as they probably won't create an option unless there is a driver that can handle it.

Yeah, that's fair. If you're interested in putting together a pull request, I think it could potentially be useful. Any feelings on how the configuration would look? I think you'd want to be able to silence warnings for specific URLs and response codes, probably including wildcards.

**Comment by Fjan** [comment]
You're right, I was only thinking assets such images and stylesheets, you probably don't want it for Ajax requests. I'm not familiar at all with the code base, so creating this myself would take me more time than I'm willing to invest right now.
