### ISSUE TITLE
Does capybara-webkit support `vh` or `vw`?

### ISSUE THREAD

**Issue by Andychen41** [thoughtbot/capybara-webkit#785]
I have try to use these units in css, but it seems not work in capybara-webkit.

**Comment by mhoran** [comment]
What version of Qt are you using? We recommend at least Qt 5.3. It's possible that you're using a Qt with an outdated WebKit.

**Comment by Andychen41** [comment]
@mhoran  thank you very much. I am using Qt 4.x , and I could not upgrade to Qt 5.x.
