### ISSUE TITLE
Tests failing intermittently against 1.5.1 on CiricleCI - Broken Pipe

### ISSUE THREAD

**Issue by alexauritt** [thoughtbot/capybara-webkit#787]
Mentor
 
Mary_113 Mentor

 Offline 
Mary_113 M
"
Received "Visit(http://127.0.0.1:42821/programs/242/meetings/new?as=321)"
Started "Visit(http://127.0.0.1:42821/programs/242/meetings/new?as=321)"
Received 0 from "http://127.0.0.1:42821/pusher/auth"
http://127.0.0.1:42821/assets/application.js|23533|Pusher : Couldn't get auth info from your webapp : 0
Load started
"Visit(http://127.0.0.1:42821/programs/242/meetings/new?as=321)" started page load
Started request to "http://127.0.0.1:42821/programs/242/meetings/new?as=321"
Finished "Visit(http://127.0.0.1:42821/programs/242/meetings/new?as=321)" with response "Success()"
Started request to "http://127.0.0.1:42821/assets/application.css"
Started request to "http://gravatar.com/avatar/996588d919d91165ceffd8c8d5199a76.png?s=31&d=http://127.0.0.1:42821/images/avatars/l2.png"
Started request to "http://127.0.0.1:42821/assets/application.js"
Started request to "http://127.0.0.1:42821/assets/fake_filepicker.js"
Received 200 from "http://127.0.0.1:42821/programs/242/meetings/new?as=321"
Started request to "http://gravatar.com/avatar/b4fbbe2391b1f02c84ee3197e7bcf240.png?s=50&d=http://127.0.0.1:42821/assets/avatars/mm.png"
Started request to "http://gravatar.com/avatar/b4fbbe2391b1f02c84ee3197e7bcf240.png?s=50&d=http://127.0.0.1:42821/assets/avatars/mm.png"
Started request to "http://127.0.0.1:42821/assets/skilledup-logo-s-only.png"
Started request to "http://127.0.0.1:42821/assets/avatars/emma.png"
Started request to "http://127.0.0.1:42821/assets/spinner.gif"
Received 200 from "http://127.0.0.1:42821/assets/application.css"
Started request to "http://127.0.0.1:42821/assets/application.js"
Received 302 from "http://gravatar.com/avatar/996588d919d91165ceffd8c8d5199a76.png?s=31&d=http://127.0.0.1:42821/images/avatars/l2.png"
Started request to "http://i0.wp.com/127.0.0.1/images/avatars/l2.png"
Received 200 from "http://127.0.0.1:42821/assets/application.js"
Received 302 from "http://gravatar.com/avatar/b4fbbe2391b1f02c84ee3197e7bcf240.png?s=50&d=http://127.0.0.1:42821/assets/avatars/mm.png"
Started request to "http://i1.wp.com/127.0.0.1/assets/avatars/mm.png"
Received 302 from "http://gravatar.com/avatar/b4fbbe2391b1f02c84ee3197e7bcf240.png?s=50&d=http://127.0.0.1:42821/assets/avatars/mm.png"
Started request to "http://i1.wp.com/127.0.0.1/assets/avatars/mm.png"
Received 200 from "http://127.0.0.1:42821/assets/skilledup-logo-s-only.png"
Received 200 from "http://127.0.0.1:42821/assets/avatars/emma.png"
Received 200 from "http://127.0.0.1:42821/assets/fake_filepicker.js"
Received 404 from "http://i0.wp.com/127.0.0.1/images/avatars/l2.png"
Received 200 from "http://127.0.0.1:42821/assets/spinner.gif"
Received 200 from "http://127.0.0.1:42821/assets/application.js"
Received 404 from "http://i1.wp.com/127.0.0.1/assets/avatars/mm.png"
Received 404 from "http://i1.wp.com/127.0.0.1/assets/avatars/mm.png"
Started request to "http://127.0.0.1:42821/assets/fake_filepicker.js"
Received 200 from "http://127.0.0.1:42821/assets/fake_filepicker.js"
Started request to "http://127.0.0.1:42821/pusher/auth"
Page finished with true
Load finished
Page load from command finished
Wrote response true ""
Received "FindCss(.program-schedule #schedule_Mon)"
Started "FindCss(.program-schedule #schedule_Mon)"
Finished "FindCss(.program-schedule #schedule_Mon)" with response "Success(1)"
Wrote response true "1"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "Node.findXpathWithin"
Started "Node.findXpathWithin"
Finished "Node.findXpathWithin" with response "Success(2)"
Wrote response true "2"
Received "Node.attribute"
Started "Node.attribute"
Finished "Node.attribute" with response "Success(false)"
Wrote response true "false"
Received "Node.tagName"
Started "Node.tagName"
Finished "Node.tagName" with response "Success(input)"
Wrote response true "input"
Received "Node.attribute"
Started "Node.attribute"
Finished "Node.attribute" with response "Success(true)"
Wrote response true "true"
Received 401 from "http://127.0.0.1:42821/pusher/auth"
http://127.0.0.1:42821/assets/application.js|23533|Pusher : Couldn't get auth info from your webapp : 401
Received "Reset()"
Started "Reset()"
    learner views and selects from program's meetings (FAILED - 1)

  An error occurred in an after hook
    Errno::EPIPE: Broken pipe
    occurred at /home/ubuntu/skilledup-academy/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.5.1/lib/capybara/webkit/connection.rb:30:in `write'

    learner selects meetin

**Comment by alexauritt** [comment]
@jferris realize this is probably a duplicate of #777. Posting in case the logs are helpful. We'll try reverting to 1.5.0. Thanks!

**Comment by jferris** [comment]
I just released 1.5.2 which may help with this.

**Comment by alexauritt** [comment]
@jferris - awesome, thanks, indeed it did.
