### ISSUE TITLE
allow_unknown_urls is only in master branch, not in 1.5.2

### ISSUE THREAD

**Issue by andriytyurnikov** [thoughtbot/capybara-webkit#790]
Driver#allow_unknown_urls is only in master branch, not in 1.5.2

**Comment by TheTeaNerd** [comment]
This may have been deliberate, but :+1: for getting `allow_unknown_urls` into our hands asap please! I'm using `HEAD` for now on a feature branch or three, but would very much prefer an official numbered release before releasing this into our `master`s.

**Comment by jferris** [comment]
This was deliberate.

I try to restrict patch level releases to only bugfixes that I'm reasonably sure won't cause other bugs. Even in those cases, we've accidentally introduced new bugs, as was the case with 1.5.1.

The remaining changes on master will be released in 1.6.0.

I'm going to close this, as I don't think there's a bug here. Please let me know if I'm missing something.
