### ISSUE TITLE
Faulty deprecation message for Capybara::Webkit::Driver#resize_window

### ISSUE THREAD

**Issue by betelgeuse** [thoughtbot/capybara-webkit#792]
https://github.com/thoughtbot/capybara-webkit/blob/9fabb9b73ddbe144ba91878ac2502cc8153aa7f4/lib/capybara/webkit/driver.rb#L118

The replacement Capybara::Window#resize_to does not exist.

**Comment by mhoran** [comment]
Hey @betelgeuse. Check out http://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FWindow%3Aresize_to. This was introduced in Capybara 2.3.0. Our gemspec requires 2.3.0 or greater, so I'm not sure what your issue is.

**Comment by betelgeuse** [comment]
@mhoran closing as invalid. I was searching for that in capybara-webkit code base.

**Comment by betelgeuse** [comment]
sorry about the noise
