### ISSUE TITLE
Can't install gem after upgrading to QT5 on OSX Yosemite

### ISSUE THREAD

**Issue by gregblass** [thoughtbot/capybara-webkit#793]
I tried upgrading my QT from 4 to 5 to silence the warning that capybara-webkit was giving me every time I ran my tests.

Big mistake.

I can't get the gem to install now for the life of me. If I do it manually, it says that the gem installs fine, however, if I run bundle install, it fails again (makes no sense)?

If I run bundle install, I'm getting:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/gregblass/.rvm/rubies/ruby-2.2.2/bin/ruby -r ./siteconf20150612-11055-6tqbcq.rb extconf.rb
cd src/ && ( test -e Makefile.webkit_server || /usr/local/bin/qmake /Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/bundler/gems/capybara-webkit-7bedbc050d00/src/webkit_server.pro LIBS\ +=\ -L/usr/local/opt/libyaml/lib\ -L/usr/local/opt/readline/lib\ -L/usr/local/opt/libksba/lib\ -L/usr/local/opt/openssl/lib -o Makefile.webkit_server ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.webkit_server 
make[1]: *** No rule to make target `/usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++/qmake.conf', needed by `Makefile.webkit_server'.  Stop.
make: *** [sub-src-webkit_server-pro-make_first-ordered] Error 2
Command 'make' failed

make "DESTDIR=" clean
cd src/ && ( test -e Makefile.webkit_server || /usr/local/bin/qmake /Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/bundler/gems/capybara-webkit-7bedbc050d00/src/webkit_server.pro LIBS\ +=\ -L/usr/local/opt/libyaml/lib\ -L/usr/local/opt/readline/lib\ -L/usr/local/opt/libksba/lib\ -L/usr/local/opt/openssl/lib -o Makefile.webkit_server ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.webkit_server clean
make[1]: *** No rule to make target `/usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++/qmake.conf', needed by `Makefile.webkit_server'.  Stop.
make: *** [sub-src-webkit_server-pro-clean-ordered] Error 2

make "DESTDIR="
cd src/ && ( test -e Makefile.webkit_server || /usr/local/bin/qmake /Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/bundler/gems/capybara-webkit-7bedbc050d00/src/webkit_server.pro LIBS\ +=\ -L/usr/local/opt/libyaml/lib\ -L/usr/local/opt/readline/lib\ -L/usr/local/opt/libksba/lib\ -L/usr/local/opt/openssl/lib -o Makefile.webkit_server ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.webkit_server 
make[1]: *** No rule to make target `/usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++/qmake.conf', needed by `Makefile.webkit_server'.  Stop.
make: *** [sub-src-webkit_server-pro-make_first-ordered] Error 2

make failed, exit code 2

Gem files will remain installed in /Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/bundler/gems/capybara-webkit-7bedbc050d00 for inspection.
Results logged to /Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/bundler/gems/extensions/x86_64-darwin-14/2.2.0/capybara-webkit-7bedbc050d00/gem_make.out
An error occurred while installing capybara-webkit (1.5.0), and Bundler cannot continue.
Make sure that `gem install capybara-webkit -v '1.5.0'` succeeds before bundling.

Then as I said, if I run gem install capybara-webkit -v '1.5.0', it actually succeeds. But then bundle install fails again.

I uninstalled QT and installed QT5, and it looks like something is still trying to reference my old qt/4.8.6. I have no idea where to update that reference that appears to be causing the problem here. I tried installing with homebrew and also installing with the .dmg installer.

Anyone have any ideas here? I've been googling for 3 hours and I'm going crazy at this point.

**Comment by gregblass** [comment]
Solution was to

    rm -rf /Users/gregblass/.rvm/gems/ruby-2.2.2@brewlog/bundler/gems/capybara-webkit-7bedbc050d00/

Then retart my terminal and try again. No idea why. Such is the life of a web developer.

**Comment by lgcantarelli** [comment]
@gregblass after around 2 hours trying to solve this bug, your solution led me to it. Thanks!
