### ISSUE TITLE
How to globally allow_unknown_urls?

### ISSUE THREAD

**Issue by rahilsondhi** [thoughtbot/capybara-webkit#797]
I don't want the chatty `Request to unknown URL:` messages.

Since `allow_unknown_urls` is an instance method on the driver, that would mean I'd have to do `before { page.driver.allow_unknown_urls }` in each feature spec, and that's tedious.

Is there a way I can do it globally, something like in spec_helper.rb `Capybara.javascript_driver.allow_unknown_urls`

Thanks!

**Comment by nritholtz** [comment]
There is an open PR #756 for this exact functionality.

You'd add it as a line in your `Capybara::Webkit.configure` block.

**Comment by jferris** [comment]
Thanks, @nritholtz.

I'm going to close this, as the issue will be addressed by #756 and should be included in the next release.
