### ISSUE TITLE
Can't install > 1.3.1 with JRuby 1.7.19

### ISSUE THREAD

**Issue by reustmd** [thoughtbot/capybara-webkit#803]
I am using jruby 1.7.19 and qt 4.8.6. I cannot install capybara-webkit, above 1.3.1, on OSX 10.10.3 (yosemite).

For example, with `gem install capybara-webkit -v '1.4.0'` I get the following

```
Fetching: capybara-webkit-1.4.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing capybara-webkit:
	ERROR: Failed to build gem native extension.

    /opt/rubies/jruby-1.7.19/bin/jruby -r ./siteconf20150701-3372-74hg69.rb extconf.rb
/opt/rubies/jruby-1.7.19/lib/ruby/shared/mkmf.rb:14: Use RbConfig instead of obsolete and deprecated Config.
mkmf.rb can't find header files for ruby at /opt/rubies/jruby-1.7.19/lib/native/include/ruby/ruby.h

extconf failed, uncaught signal 1

Gem files will remain installed in /opt/rubies/jruby-1.7.19/lib/ruby/gems/shared/gems/capybara-webkit-1.4.0 for inspection.
Results logged to /opt/rubies/jruby-1.7.19/lib/ruby/gems/shared/extensions/universal-java-1.7/1.9/capybara-webkit-1.4.0/gem_make.out
```

**Comment by mhoran** [comment]
Hey @reustmd. It looks like something is wrong with your JRuby install. We use `mkmf` to prepare our source for compilation, though we don't actually compile a C extension. This has some weird interactions with some JRuby versions, which may have C extension compilation disabled by default. Unfortunately this is a side effect of how the `mkmf` library has been implemented in JRuby. You may want to try reinstalling JRuby, and ensuring that the Ruby header files are in place.

As you can see on [Travis](https://travis-ci.org/thoughtbot/capybara-webkit/jobs/68653572#L100), the tests run just fine against JRuby 1.7.19.

**Comment by reustmd** [comment]
Thanks for the reply mhoran. Might be specific to qt on macs too. Nonetheless, i got the tests working using poltergeist for now.
