### ISSUE TITLE
html5 drag and drop not supported

### ISSUE THREAD

**Issue by betelgeuse** [thoughtbot/capybara-webkit#804]
The drag and drop support uses mouse events and does not currently trigger html5 dnd events. If I were to submit a pull request integrating https://github.com/andywer/drag-mock, would it be accepted?

**Comment by jferris** [comment]
We generally try to respect the events triggered by the Selenium driver. If there's a case where we fire different events than Seleinum, we'd happily accept a tested pull request which brings us back in line.
