### ISSUE TITLE
Appropriate usage of accepting JS confirmation alerts?

### ISSUE THREAD

**Issue by sublimecoder** [thoughtbot/capybara-webkit#811]
I apologize if this is not the place for this but, I just upgraded to the latest capybara webkit and previous to this upgrade I was able to use this syntax for javascript confirmation boxes. 
``` ruby
page.driver.browser.accept_js_confirms
```

However this syntax appears that it is being deprecated. 

The deprecation message says 
 [DEPRECATION] Capybara::Webkit::Driver#accept_js_confirms
 is deprecated. Please use Capybara::Session#accept_confirm instead.

which should mean that I can swap the original code for this

``` ruby
page.accept_confirm
```
but that code appears to take a block and errors when you do not have one. 

``` ruby
page.accept_confirm { }
```
What is the block used for in this case, or how should it be used?

**Comment by mhoran** [comment]
Hey @sublimecoder. You should provide a block which triggers a modal dialog. For example, if `visit '/'` would trigger a confirm dialog, you'd want to do the following:

```ruby
page.accept_confirm { visit ('/') }
```

**Comment by sublimecoder** [comment]
@mhoran Oh ok! That make sense! Just applied that and it worked!

Thank you so much!

**Comment by ramugogurla** [comment]
@mhoran ... I have tried the same but it didn't work.
getting error  `rescue in find_modal': Unable to find modal dialog (Capybara::ModalNotFound)
I have tried all the options like....
page.driver.browser.evaluate_script('window.confirm = function() { return true; }')
page.driver.browser.switch_to.window(popup)

also  send keys 

builder = page.driver.browser.action
builder.send_keys(:escape).perform

But none of them work.


I need to click ok or cancel  button  of the dialog window.Please help

**Comment by mhoran** [comment]
Hey @ramugogurla. Are you sure you're using capybara-webkit? You're using some Selenium driver methods there and those are not compatible with capybara-webkit.

I'm going to close this out now as the original issue is solved. Please open a new issue if you are indeed using capybara-webkit.

**Comment by TeTiRoss** [comment]
How to reject js dialog window?

**Comment by nritholtz** [comment]
Checkout this comment https://github.com/thoughtbot/capybara-webkit/issues/84#issuecomment-111632554
