### ISSUE TITLE
Regression: No ability to do test by test allowed url configuration

### ISSUE THREAD

**Issue by sgringwe** [thoughtbot/capybara-webkit#814]
It seems that test based configuration of allowed urls is no longer possible due to recent deprecation of allow_url on the driver. It was replaced with
```
Capybara::Webkit.configure do |config|
  config.allow_url()
end
```
which is fine - but that is configuring for the whole suite. Is there a way to configure test by test?

An example use case is allowing google maps related assets on certain specs but turning it off on all the other ones.

**Comment by mhoran** [comment]
Hey @sgringwe. Check out the related discussion in #756. I brought this up but after discussing with @jferris, I agree that the global configuration should be fine for most cases. We may look into a `reconfigure` block, which would make something like this possible, but I have doubts as to whether there'd actually be a benefit here.

The case that I originally brought up had disallowed certain assets for certain tests in the interest of "performance". However, simply configuring the whitelist globally didn't slow down the tests, so the point was moot. If you've found that performance is really an issue with the global whitelist, or have some other test setup that wold necessitate per-test tweaks, please let us know.

**Comment by sgringwe** [comment]
@mhoran Thanks for the response. I will watch for changes in performance and close if there is no difference.

**Comment by jferris** [comment]
Re: performance: if we can avoid per-test configuration, I think we can actually improve performance, because we can stop sending configuration after every `reset!`.
