### ISSUE TITLE
Capybara allow unknown urls not behaving as expected.

### ISSUE THREAD

**Issue by renegadeandy** [thoughtbot/capybara-webkit#816]
I have a problem with allowing specific URLs in capybara webkit - please help : http://stackoverflow.com/questions/31329419/capybara-webkit-allow-unknown-urls-is-not-being-set?noredirect=1#comment50737905_31329419

**Comment by jferris** [comment]
The configuration you pasted looks to me like it should work. Nothing jumps out at me.

Do you have any other Capybara or capybara-webkit configuration in `spec/support` or `config`?

Are you able to reproduce this in a smaller example or something you can give us access to?

**Comment by pramodthammaiah** [comment]
I'm having a similar issue and it seems to only affect stripe urls as well. In my rails_helper file I have:
`Capybara.default_wait_time = 5
Capybara.javascript_driver = :webkit
Capybara::Webkit.configure do |config|
  config.allow_unknown_urls
  config.allow_url("q.stripe.com")
end`

It seems to only cause a test failure 10% of the time. The times it does I get the following output:
`Request to unknown URL: https://q.stripe.com/?event=stripejs-error&type=empty_response&key=pk_test_7OOwWXNLjsfNAF0tpW0UxWx2&timestamp=1438828579&payment_user_agent=stripe.js%2F8a1a466
To block requests to unknown URLs:
  page.driver.block_unknown_urls
To allow just this URL:
  page.driver.allow_url("https://q.stripe.com/?event=stripejs-error&type=empty_response&key=pk_test_7OOwWXNLjsfNAF0tpW0UxWx2&timestamp=1438828579&payment_user_agent=stripe.js%2F8a1a466")
To allow requests to URLs from this host:
  page.driver.allow_url("q.stripe.com")
Request to unknown URL: https://api.stripe.com/v1/tokens?key=pk_test_7OOwWXNLjsfNAF0tpW0UxWx2&payment_user_agent=stripe.js%2F8a1a466&card[name]=Example+User&card[number]=4242+4242+4242+4242&card[cvc]=123&card[exp_month]=12&card[exp_year]=25&callback=sjsonp1438828578651&_method=POST
To block requests to unknown URLs:
  page.driver.block_unknown_urls
To allow just this URL:
  page.driver.allow_url("https://api.stripe.com/v1/tokens?key=pk_test_7OOwWXNLjsfNAF0tpW0UxWx2&payment_user_agent=stripe.js%2F8a1a466&card[name]=Example+User&card[number]=4242+4242+4242+4242&card[cvc]=123&card[exp_month]=12&card[exp_year]=25&callback=sjsonp1438828578651&_method=POST")
To allow requests to URLs from this host:
  page.driver.allow_url("api.stripe.com")`

Were you able to resolve the issue? Any ideas of what I'm doing wrong? Thanks!

**Comment by lucasklaassen** [comment]
Same issue here. Capybara 2.4.4, Capybara Webkit 1.7.1.

**Comment by ChrisCPO** [comment]
Same issue, though I am running everything in an Rails Engine. Using stripe as well. 

Capybara 2.5
Capybara Webkit 1.7.1

**Comment by jferris** [comment]
There are recent changes in Capybara (2.7 waits for requests to finish) and capybara-webkit (1.10 aborts requests before resetting). If you're still having issues with this, can you make sure you're on the latest version of each gem?

**Comment by tmock12** [comment]
Running into the same issue with braintree url

Capybara 2.7.1
Capybara Webkit 1.11.1

**Comment by jferris** [comment]
@tmock12 can you paste your debug log and Capybara configuration?

**Comment by twalpole** [comment]
Closing due to age and lack of response
