### ISSUE TITLE
"Unknown error" on travis-ci.org

### ISSUE THREAD

**Issue by lxsameer** [thoughtbot/capybara-webkit#821]
Hi folks. At first thanks for your great work.

I'm using capybara webkit for just two specs in my project. All the specs pass locally but not on travis-ci server. I use `:webkit_debug` driver but I can't find the problem. So please take a look at this output and help me with that. I also included my `.travis.yml` content.

https://gist.github.com/lxsameer/179474460ee76d810436

**Comment by lxsameer** [comment]
After some investigation I found out that capybara can not run the application in background.

**Comment by jferris** [comment]
It looks as though the tests are trying to visit `localhost:3000`, which is generally what your development server runs on. Capybara boots a background thread and runs your application on a random, local port.

How are you telling Capybara to visit URLs? I'd check `app_host` for Capybara and `default_url_options` for Rails to make sure you don't have `3000` anywhere in the test configuration.

**Comment by twalpole** [comment]
Closing due to lack of response
