### ISSUE TITLE
Allow setting logger in config

### ISSUE THREAD

**Issue by CamJN** [thoughtbot/capybara-webkit#826]
Right now config.debug dumps a lot of valuable but messy info to stdout, it'd be nice to be able to specify a logger to use so that I can redirect that info to a log file.

**Comment by jferris** [comment]
I don't have a need for this, so I don't plan on implementing it myself. However, if you're willing to try it yourself, I'd be open to a tested pull request, assuming it doesn't introduce too much complexity.

I'm going to close this issue, as I don't plan to do anything right now, but feel free to continue discussing if you have further thoughts.
