### ISSUE TITLE
webkit_server throws an error if 32-bit plugin is available

### ISSUE THREAD

**Issue by CamJN** [thoughtbot/capybara-webkit#828]
I was setting up some tests for my Google Analytics integration, and started getting the following error. I know that GA tries to determine which plugins are available and that's why the plugin is now being poked at whereas before it wasn't; but I thought I'd let you know. I don't need the plugin to work, but the error is annoying.

The plugin mentioned is a Mach-O dynamically linked shared library (i386) as that's all osx provides.

```
2015-08-02 18:50:03.723 webkit_server[37439:1716598] Error loading /Library/Internet Plug-Ins/QuickTime Plugin.plugin/Contents/MacOS/QuickTime Plugin:  dlopen(/Library/Internet Plug-Ins/QuickTime Plugin.plugin/Contents/MacOS/QuickTime Plugin, 265): no suitable image found.  Did find:
    /Library/Internet Plug-Ins/QuickTime Plugin.plugin/Contents/MacOS/QuickTime Plugin: mach-o, but wrong architecture
```

**Comment by CamJN** [comment]
It also seems to make communication with webkit_server unreliable. So I guess it is a legitimate problem.

**Comment by CamJN** [comment]
In trying to quantify just how much less reliable the connection becomes I noticed that the connection isn't actually very reliable at all to begin with.

10 runs with GA:  1 failure, 21 errors
10 runs w/o GA: 10 failures (GA test failing), 11 errors

Running test suite manually once usually passes with no errors. I'm not sure how long capybara-webkit needs between runs to make this evaluation fair.

**Comment by twalpole** [comment]
Closing due to age, if this is still an issue with current versions and a way to replicate is provided we can reopen
