### ISSUE TITLE
Capybara 2.5.0 is not supported

### ISSUE THREAD

**Issue by TheTeaNerd** [thoughtbot/capybara-webkit#831]
Capybara 2.5.0 has just been released with [several new features](https://github.com/jnicklas/capybara/blob/master/History.md#version-250) that could be excellent to use with Capybara-webkit. However, this project's Gemspec is locked to '< 2.5.0' which limits adoption of the new Capybara as Bundler cannot manage conflicting dependencies. 

(Okay so I'm in real need of one of the 2.5.0 changes to solve an issue I have, so I'll have a go at getting a PR in for the upgrade, but it looks like `master` has red tests right now so I'm not confident in my changes just yet.)

**Comment by achempion** [comment]
sorry for 2 PR, the first was from removed branch

I think that we should not introduce max capybara gem version for a latest version of this gem.

**Comment by mhoran** [comment]
Closing in favor of https://github.com/thoughtbot/capybara-webkit/tree/capybara-2.5. We'll release a new gem once the tests pass. Thanks for your PR!

**Comment by mhoran** [comment]
Released capybara-webkit 1.7.0 to address this. Thanks!
