### ISSUE TITLE
#default_wait_time is deprecated, please use #default_max_wait_time

### ISSUE THREAD

**Issue by Fjan** [thoughtbot/capybara-webkit#834]
After upgrading to the latest Capybara I get a deprecation warning caused by Capybara webkit:

DEPRECATED: #default_wait_time is deprecated, please use #default_max_wait_time instead

I traced it to the file ```lib/capybara/webkit/driver.rb``` line 338. Should be a simple fix, but if we fix it we would probably need to lock to the latest Capybara. I'll leave it to the maintainers to decide how to proceed.

(A simple workaround to suppress the warning is to manually add a ":wait" option to any calls that work on a modal)

**Comment by mhoran** [comment]
Fixed by #842. Will be included in capybara-webkit 1.7.1.
