### ISSUE TITLE
Ability to close and reopen browser

### ISSUE THREAD

**Issue by hgani** [thoughtbot/capybara-webkit#844]
Hi,

May I request the ability to close and reopen a browser/window?

My use case is I'd like to test my website's login session behaviour. I'd like to ensure that the login session gets destroyed after closing/reopening the browser.

This is similar to a past request (https://github.com/thoughtbot/capybara-webkit/issues/393) but if we make the window reopens right after closing, then we won't have the complexity described in that discussion (in regards to window focus).

Thanks

**Comment by mhoran** [comment]
Simply calling `Capybara::Webkit::Browser#reset!`, which will happen automatically when utilizing Capybara via rspec and Test::Unit, will do what you want. The [`WebPageManager::Reset`](https://github.com/thoughtbot/capybara-webkit/blob/e9bd20a184d7e3c3b1aeebdceeaa66b2905afca2/src/WebPageManager.cpp#L147) method will clear the cookie jar, close all open windows, and open a new one, among other things.

**Comment by hgani** [comment]
@mhoran 

Thanks for the response.

Sorry I didn't explain clearly, but I wanted this closing/reopening browser behaviour *within* a particular test, not between tests.

Another example is to test "remember me" feature in which case we want to simulate closing/reopening a browser while still retaining the login session.

Based on your explanation, WebPageManager::Reset almost does it except that it shouldn't simply clear the cookie jar, because this will destroy the "remember me" cookie.

**Comment by simoniong** [comment]
Hey, @mhoran @hgani 

I am facing the same issue, need to test a "remember me" feature. just wonder if you guys come up a good solution for that?

**Comment by mhoran** [comment]
Hey @simoniong. If you're simply trying to check that a user is logged-out after cookies are cleared (or local storage), try `Capybara::Webkit::Browser#reset!`.

**Comment by simoniong** [comment]
Hey @mhoran, thanks for reply!

I think calling `Capybara::Webkit::Browser#reset!` will clear all cookies in current session, including a important `remember_token` settle in cookies, and this `remember_token` need to be used in next session for login.

For more detail, what i want to do is to test two scenario.

Scernario A:
1. User access login page
2. User input email & password, uncheck "Remember Me"
3. User successfully login, then redirect to a protected page, such as "Profile page"

**Comment by simoniong** [comment]
Oh, I found out a gem, (show_me_the_cookie)[https://github.com/nruth/show_me_the_cookies], provided method `expire_cookies`,  it is a perfect fit for simulate close browser & open browser! 

This is a simple feature test case for Scenario A.
``` ruby
sign_in_as user
expect(current_path).to eql profile_path

# restart browser, clear out session, except cookies
expire_cookies

visit profile_path
expect(current_path).to eql profile_path
```

**Comment by hgani** [comment]
@simoniong This looks exactly what I need. Thanks for the info.

**Comment by mhoran** [comment]
Glad you found a solution, @simoniong. That is the approach I would recommend (for scenario A). A reset should handle scenario B.

Please note that closing and reopening capybara-webkit would not achieve what you're looking for in scenario A. When capybara-webkit exits, all cookies, local storage, etc. are cleared. This is consistent with the other Capybara drivers, e.g. Selenium.
