### ISSUE TITLE
How to configure version of QT, 5.5 gives error

### ISSUE THREAD

**Issue by justin808** [thoughtbot/capybara-webkit#847]
After updating to El Capitan and all brew dependencies, I get this error:

```
Command '/usr/local/Cellar/qt5/5.4.0/bin/qmake ' not available
```

Seems that I have qt newer 5.5 version
```
ls -l /usr/local/Cellar/qt5                                                                                                                                                                      5.5.0_1
```

Docs say: "capybara-webkit requires Qt version 4.8 or greater."

Any advice?

**Comment by justin808** [comment]
Working around the issue temporarily with a symlink from the old, missing directory to the latest one.

```
/usr/local/Cellar/qt5 (master) ln -s 5.5.0_1 5.4.0
```

**Comment by justin808** [comment]
FWIW, I copied the full error message here: http://forum.shakacode.com/t/el-capitan-upgrade-tips/375

**Comment by jferris** [comment]
Do you have a `QMAKE` variable set in your shell? The installer will try to use that if it's set. Otherwise, it looks for `qmake` on your `PATH` on OS X.

You can see the logic for finding `qmake` here: https://github.com/thoughtbot/capybara-webkit/blob/master/lib/capybara_webkit_builder.rb

**Comment by khoan** [comment]
brew search qt
brew install qt5
brew link qt5 --force

#852

**Comment by jferris** [comment]
This doesn't look like a bug in capybara-webkit, and the original reporter hasn't updated in a while. I'm going to close this issue.
