### ISSUE TITLE
Does not support ES6

### ISSUE THREAD

**Issue by kiddrew** [thoughtbot/capybara-webkit#849]
We have a test that executes a `page.execute_script` command to populate a credit card form.  That test worked just fine until we added an ES6 template in a separate file.  The `execute_script` command does not even interact with the offending template, but simply adding the backticks within a JS file that gets loaded in the test causes the failure.

    Failure/Error: page.execute_script '$("input.number").val("4242 4242 4242 4242")'
     Capybara::Webkit::InvalidResponseError:
       Javascript failed to execute

**Comment by jferris** [comment]
In terms of JavaScript features, we're limited by what QtWebKit supports. It's really hard to figure out what version of WebKit started supporting template strings, but it doesn't seem to have been included in Qt 5.5, which is unfortunately will be the last release to include QtWebKit.

Out of curiosity, what versions are you using? You can see some versions by using `puts page.driver.version`.

**Comment by kiddrew** [comment]
I'm on older versions, but it sounds like upgrading won't fix my issue anyway.

capybara-webkit 1.3.1
qt 4.8.6

**Comment by jferris** [comment]
Okay. I don't think any features from ES6 were added until 2015. I think the version of WebKit in Qt 4.8 is from 2012.

You should upgrade to Qt 5 as soon as possible, as Qt 4 is pretty unstable, especially if you try and use any newer HTML5 features.

**Comment by neoinvest** [comment]
i am trying in the latest version of QT, but ES6 calls are failing

Capybara: 2.6.2                                                                
capybara-webkit: 1.9.0
Qt: 5.5.1             
WebKit: 538.1         
QtWebKit: 5.5.1     

[{:line_number=>21,                                                                           │                                        
  :message=>     "TypeError: undefined is not a constructor (evaluating 'Object.assign({}, state, { age: action.value })')",

**Comment by mhoran** [comment]
Hey @neoinvest. QtWebKit 5.5.1 likely vendors a version of JavaScriptCore that does not support ES6. Unfortunately, there's not much we can do about that, and QtWebKit has been dropped from Qt 5.6.

**Comment by TheNotary** [comment]
So ultimately, if we're using ES6 features like classes, we can't test them using Capybara without transpiling them?
