### ISSUE TITLE
Qt deprecation warning

### ISSUE THREAD

**Issue by obromios** [thoughtbot/capybara-webkit#851]
In regard to the following warning:
```WARNING: The next major version of capybara-webkit will require at least version 5.0 of Qt. You're using version 4.8.6.```
I have posted a question, http://stackoverflow.com/questions/33121490/upgrading-qt-on-mac-osx-10-10-5 about the best way to upgrade to Qt 5.  However, no one has answered the question in three weeks, indeed it has been downvoted. You have extensive information on installing Qt, but none that I can find on upgrading. Is it possible to answer my stackoverflow question, or add some information on your page dealing with installing capybara-webkit and Qt?

**Comment by jferris** [comment]
Do you know how Qt was installed? It doesn't come with OS X, so you must have installed it some point, possibly as a dependency of something else. The way you'd upgrade it depends on how you installed it.

Using `which qmake` will hopefully tell you *where* it's installed, which can sometimes be revealing.

The two most common ways to install it are through the official packages and through Homebrew. If you used the official installer, I think you can just run the latest official installer. If you used Homebrew, you can use `brew upgrade`.

**Comment by obromios** [comment]
It turned out it was installed with Homebrew.  After an El Capitan problem causing an issue with brew update, ```brew upgrade qt``` worked fine.

Thank you
