### ISSUE TITLE
Unable to test JS Flash Messages

### ISSUE THREAD

**Issue by rjrobinson** [thoughtbot/capybara-webkit#853]
I switched over to web-kit because Firefox kept loading with selenium. 

I have growl like flash notifications with my app, and they don't seem to get parsed when loaded in the DOM. 

Not really sure how to trouble shoot this. Any help would be great.

**Comment by jferris** [comment]
Some more information would be helpful:

* What does the failure message look like?
* What does your test look like?
* What does the markup look like for the flash notifications?
* What does the CSS look like for the flash notifications?
* What does `save_and_open_screenshot` look like on a page where you think the flash notifications should be appearing?

**Comment by twalpole** [comment]
Closing due to lack of response
