### ISSUE TITLE
CSS calc with vw and px

### ISSUE THREAD

**Issue by nehalita** [thoughtbot/capybara-webkit#854]
Tried to run tests with css:

```
width: calc(100vw - 40px)
height: calc((100vw - 40px) * 0.75)
```

with a screen size of 480x640 and got random numbers where the height was larger than the width (which doesn't make sense). 

Reran the test where I replaced 100vw with 480px and it passed fine, leading me to think there might be some issues around calc and vw. I have another test using vw which works fine. It might also be related to doing conversions between two sets of units.

**Comment by twalpole** [comment]
Closing this due to it being a Qt limitation
