### ISSUE TITLE
Opal transpiler causes webkit crash

### ISSUE THREAD

**Issue by msp** [thoughtbot/capybara-webkit#855]
When including the Opal 'runtime' and a JS file that's been transpiled from Ruby, it causes the crash. The test runs fine in Selenium and before the transpired code was included.

Crash log under webkit-debug:

https://gist.github.com/msp/f35fbff610fcd63ea5e2

Thanks

**Comment by twalpole** [comment]
Closing due to age and lack of way to replicate
