### ISSUE TITLE
Script hangs when calling test with have_errors

### ISSUE THREAD

**Issue by alaghu** [thoughtbot/capybara-webkit#859]
Any help would be greatly appreciated. 

Firstly, I think I might be hitting issue#623 and/or issue#670, which in turn could lead to my observation of hanging. I have quarantined all the tests that quite consistently fail into https://github.com/alaghu/learn_jquery/blob/webkit_tests_have_error_failing/spec/features/to_not_have_errors_spec.rb

Next, here are my configurations.

Mac : 10.11.1 (15B42)
qt5 5.5.1

Gems installed
gem 'rspec-rails', '3.3.3' 
gem 'capybara', '2.5.0' 
gem 'capybara-webkit', '1.7.1'

Thirdly, it is hanging quite consistently in my mac but have never seen it hang in travis-ci (https://travis-ci.org/alaghu/learn_jquery/builds/91538832). 

hanging.

You can view my changes https://github.com/alaghu/learn_jquery/compare/webkit_tests_have_error_failing. When I run 

Anand:learn_jquery/ (webkit_tests_have_error_failing) $ rspec spec/features/to_not_have_errors_spec.rb                                              [22:44:57]
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "Visit(http://127.0.0.1:49740/)"
Started "Visit(http://127.0.0.1:49740/)"
Load started
"Visit(http://127.0.0.1:49740/)" started page load
Started request to "http://127.0.0.1:49740/"
Finished "Visit(http://127.0.0.1:49740/)" with response "Success()"
Started request to "http://127.0.0.1:49740/assets/application.css"
Started request to "http://127.0.0.1:49740/assets/home_index.css"
Started request to "http://127.0.0.1:49740/assets/application.js"
Started request to "http://127.0.0.1:49740/assets/home_index.js"
Received 200 from "http://127.0.0.1:49740/"
Received 200 from "http://127.0.0.1:49740/assets/application.css"
Received 200 from "http://127.0.0.1:49740/assets/application.js"
Received 200 from "http://127.0.0.1:49740/assets/home_index.css"
Received 200 from "http://127.0.0.1:49740/assets/home_index.js"
Page finished with true
Load finished
Page load from command finished
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Reset()"
Started "Reset()"
Finished "Reset()" with response "Success()"
Wrote response true ""
Received "EnableLogging()"
Started "EnableLogging()"
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "FindXpath(/html/body/_)"
Started "FindXpath(/html/body/_)"
Finished "FindXpath(/html/body/_)" with response "Success()"
Wrote response true ""
.Received "Visit(http://127.0.0.1:49740/)"
Started "Visit(http://127.0.0.1:49740/)"
Load started
"Visit(http://127.0.0.1:49740/)" started page load
Started request to "http://127.0.0.1:49740/"
Finished "Visit(http://127.0.0.1:49740/)" with response "Success()"
Received 304 from "http://127.0.0.1:49740/"
Started request to "http://127.0.0.1:49740/assets/application.css"
Started request to "http://127.0.0.1:49740/assets/home_index.css"
Started request to "http://127.0.0.1:49740/assets/application.js"
Started request to "http://127.0.0.1:49740/assets/home_index.js"
Received 304 from "http://127.0.0.1:49740/assets/application.css"
Received 304 from "http://127.0.0.1:49740/assets/home_index.css"
Received 304 from "http://127.0.0.1:49740/assets/application.js"
Received 304 from "http://127.0.0.1:49740/assets/home_index.js"
Page finished with true
Load finished
Page load from command finished
Wrote response true ""
Received "FindXpath(.//a[./@href][(((./@id = 'Can you book my intro?' or normalize-space(string(.)) = 'Can you book my intro?') or ./@title = 'Can you book my intro?') or .//img[./@alt = 'Can you book my intro?'])] | .//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'Can you book my intro?' or ./@value = 'Can you book my intro?') or ./@title = 'Can you book my intro?')] | .//input[./@type = 'image'][./@alt = 'Can you book my intro?'] | .//button[(((./@id = 'Can you book my intro?' or ./@value = 'Can you book my intro?') or normalize-space(string(.)) = 'Can you book my intro?') or ./@title = 'Can you book my intro?')] | .//input[./@type = 'image'][./@alt = 'Can you book my intro?'])"
Started "FindXpath(.//a[./@href][(((./@id = 'Can you book my intro?' or normalize-space(string(.)) = 'Can you book my intro?') or ./@title = 'Can you book my intro?') or .//img[./@alt = 'Can you book my intro?'])] | .//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'Can you book my intro?' or ./@value = 'Can you book my intro?') or ./@title = 'Can you book my intro?')] | .//input[./@type = 'image'][./@alt = 'Can you book my intro?'] | .//button[(((./@id = 'Can you book my intro?' or ./@value = 'Can you book my intro?') or normalize-space(string(.)) = 'Can you book my intro?') or ./@title = 'Can you book my intro?')] | .//input[./@type = 'image'][./@alt = 'Can you book my intro?'])"
Finished "FindXpath(.//a[./@href][(((./@id = 'Can you book my intro?' or normalize-space(string(.)) = 'Can you book my intro?') or ./@title = 'Can you book my intro?') or .//img[./@alt = 'Can you book my intro?'])] | .//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'Can you book my intro?' or ./@value = 'Can you book my intro?') or ./@title = 'Can you book my intro?')] | .//input[./@type = 'image'][./@alt = 'Can you book my intro?'] | .//button[(((./@id = 'Can you book my intro?' or ./@value = 'Can you book my intro?') or normalize-space(string(.)) = 'Can you book my intro?') or ./@title = 'Can you book my intro?')] | .//input[./@type = 'image'][./@alt = 'Can you book my intro?'])" with response "Success(1)"
Wrote response true "1"
Received "Node.visible"
Started "Node.visible"
Finished "Node.visible" with response "Success(true)"
Wrote response true "true"
Received "Node.tagName"
Started "Node.tagName"
Finished "Node.tagName" with response "Success(a)"
Wrote response true "a"
Received "Node.leftClick"
Started "Node.leftClick"
Started request to "http://127.0.0.1:49740/book/intro"
Finished "Node.leftClick" with response "Success()"
Wrote response true ""
Received "ConsoleMessages()"
Started "ConsoleMessages()"
Finished "ConsoleMessages()" with response "Success([])"
Wrote response true "[]"
Received "Reset()"
Started "Reset()"
Aborting request to "http://127.0.0.1:49740/book/intro"
Received 0 from "http://127.0.0.1:49740/book/intro"
Finished "Reset()" with response "Success()"
Wrote response true ""
Load started
Started request to "http://127.0.0.1:49740/book/intro"
Started request to "http://127.0.0.1:49740/book/intro"
Received 0 from "http://127.0.0.1:49740/book/intro"
Received "EnableLogging()"
Started "EnableLogging()"
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "FindXpath(/html/body/_)"
Started "FindXpath(/html/body/_)"
Finished "FindXpath(/html/body/_)" with response "Success()"
Wrote response true ""
.Received "Visit(http://127.0.0.1:49740/)"
Started "Visit(http://127.0.0.1:49740/)"
Started request to "http://127.0.0.1:49740/"
Finished "Visit(http://127.0.0.1:49740/)" with response "Success()"
Wrote response true ""
Received "FindXpath(.//a[./@href][(((./@id = 'A selection of books!' or normalize-space(string(.)) = 'A selection of books!') or ./@title = 'A selection of books!') or .//img[./@alt = 'A selection of books!'])] | .//input[./@type = 'submit' or ./@type = 'reset' or ./@type = 'image' or ./@type = 'button'][((./@id = 'A selection of books!' or ./@value = 'A selection of books!') or ./@title = 'A selection of books!')] | .//input[./@type = 'image'][./@alt = 'A selection of books!'] | .//button[(((./@id = 'A selection of books!' or ./@value = 'A selection of books!') or normalize-space(string(.)) = 'A selection of books!') or ./@title = 'A selection of books!')] | .//input[./@type = 'image'][./@alt = 'A selection of books!'])"
"TimeoutCommand" waiting for load to finish
Received 304 from "http://127.0.0.1:49740/"
Started request to "http://127.0.0.1:49740/assets/application.css"
Started request to "http://127.0.0.1:49740/assets/home_index.css"
Started request to "http://127.0.0.1:49740/assets/application.js"
Started request to "http://127.0.0.1:49740/assets/home_index.js"
Received 304 from "http://127.0.0.1:49740/assets/application.css"
Received 304 from "http://127.0.0.1:49740/assets/home_index.css"
Received 304 from "http://127.0.0.1:49740/assets/application.js"
Received 304 from "http://127.0.0.1:49740/assets/home_index.js"
Page finished with true

**Comment by alaghu** [comment]
Hi ,
Any updates?

**Comment by jferris** [comment]
Is there anything in your development server log that indicates the requests are finishing?

I can try and clone the application and poke around, but I'm not sure when I'll have time to do so.

**Comment by alaghu** [comment]
Hi,
I have pushed changes to https://github.com/alaghu/learn_jquery/tree/webkit_tests_have_error_failing that now only has three tests. Each of these tests have "have_errors" check. 

Failure case
-----------------
here is the output for a failure case for rpsec https://gist.github.com/alaghu/b6e4a6bf7e3c42a37108
here is the log file of the same run https://gist.github.com/alaghu/28fb1c58c2d8cc315207

Pass Case
---------------
here is the output for a pass case for rpsec https://gist.github.com/alaghu/1af08ffe153c737be7a7
here is the log file of the same run https://gist.github.com/alaghu/dcfaaa986e9f75479ea4

Thank you in advance to look into this. Appreciate your help.

**Comment by jferris** [comment]
@alaghu thanks for putting together those test cases. I'll take a look at those as soon as I can. Unfortunately, my schedule is pretty packed right now, and I can't promise I'll be able to look at them for another week or so.

**Comment by alaghu** [comment]
Hi @jferris , not a problem. Thank you for looking into this.

**Comment by twalpole** [comment]
Closing due to age - if this is still an issue with current releases we can reopen
