### ISSUE TITLE
Test Passing, but throwing `webkit_server[34400] <Error>: CGContextSetLineDash`

### ISSUE THREAD

**Issue by fu1two** [thoughtbot/capybara-webkit#860]
Configuration:
Mac OS 10.11

Qt 4.8.7

Gems:
'rspec-rails', '3.4.3' 
'capybara', '2.5.0' 
'capybara-webkit', '1.7.1'

I have a basic feature test that is testing an action and it passes with no problems, but throws the error below when using capybara-webkit. I originally thought it was having some issue with some AJAX or JS, but really have no idea. I am able to rid of the error by eliminating any clicks after the rails action occurs. 

Error:
`Nov 19 08:40:50  webkit_server[34400] <Error>: CGContextSetLineDash: invalid dash array: negative lengths are not allowed.`

**Comment by jferris** [comment]
Could you try with Qt 5? Qt 4 is very old and a large number of bugs have been fixed by then.

**Comment by fu1two** [comment]
Ah! Thank you, sir!
