### ISSUE TITLE
Can't click_link in Bootstrap 3 navbar with capybara-webkit, can with Poltergeist & Selenium

### ISSUE THREAD

**Issue by aguynamedben** [thoughtbot/capybara-webkit#861]
The test:

``` ruby
    it "can navigate to business development deals from left sidebar" do
      within "nav.navbar-firstround-header" do
        click_link "COMMUNITY"
      end

       expect(current_path).to eq(business_development_deals_path)
    end
```

Test Output:

```
Failure/Error: click_link "COMMUNITY"
Capybara::ElementNotFound:
  Unable to find link "COMMUNITY"
```

The anchor element I'm attempting to click is is inside a standard Bootstrap 3 header (inside a li from an unordered list)...

``` erb
        <div class="col-sm-13">
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="navbar-collapse-header">
            <ul class="nav navbar-nav navbar-left navbar-firstround-features">
              <li<% if @navbar_menu_selection == "Community" %> class="active"<% end %>><%= link_to "COMMUNITY", community_path %></li>
            </ul>
          </div>
        </div>
```

This test passes when I use Poltergeist and Selenium as my webdrivers. I'm also able to find various element via the JavaScript console as well. I don't understand why capybara-webkit cannot find the element. I've been using capybara-webkit for a few years now, and this seems like a bug. I also tried other methods of finding the element (giving the anchor tag an ID and finding by ID, etc.) but it seems that capybara-webkit can somehow not see "into" the Bootstrap 3 navbar.

Any ideas?

**Comment by chrise86** [comment]
@aguynamedben did you solve this? Facing something similar 😕

**Comment by twalpole** [comment]
This is likely to be a window size or CSS issue - what size do you have set for your window? Have you taken a screenshot to see what capybara-webkit thinks the page looks like? From the CSS side, what version of Qt did you build capybara-webkit with?

**Comment by twalpole** [comment]
Closing due to age and lack of response
