### ISSUE TITLE
can not access the root path

### ISSUE THREAD

**Issue by dunake** [thoughtbot/capybara-webkit#862]
I get this error when i run my specs (this shows after the first scenario)
 Failure/Error: sign_in_as!(user)
     Capybara::Webkit::ConnectionError:
       /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/capybara-webkit-1.7.1/bin/webkit_server failed to start after 15 seconds.
     # ./spec/support/authentication_helpers.rb:3:in `sign_in_as!'
     # ./spec/features/creating_houses_spec.rb:14:in `block (2 levels) in <top (required)>'

This shows when the second scenario is run 

 Failure/Error: Unable to find matching line from backtrace
     ActionController::RoutingError:
       No route matches [GET] "/javascripts/defaults.js"
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/web-console-2.1.3/lib/web_console/middleware.rb:37:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/capybara-2.4.4/lib/capybara/server.rb:19:in `call'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
     # /home/duncan/.rbenv/versions/2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

My guess is this happens when i try to access the root route

module AuthenticationHelpers
  def sign_in_as!(user)
    visit "/"
    click_link "Sign in"
    fill_in "Email",with: user.email
    fill_in "Password",with: user.password
    click_button "Log in"
    expect(page).to have_content("Signed in successfully.")
  end
end

RSpec.configure do |config|
  config.include AuthenticationHelpers # ,:type => :feature,:controller
end

**Comment by mhoran** [comment]
It looks like your app is taking a long time to start up, causing the first failure. The timeout can be raised, but realistically you shouldn't be hitting that timeout under normal circumstances. Given the second error, it does look like there are issues with assets and / or the asset pipeline, which could be causing the slowdown. It's hard to tell without example code what could be causing the issue, but I'd start there.

**Comment by dunake** [comment]
thank you the issue was with my assets No route matches [GET] "/javascripts/defaults.js"
