### ISSUE TITLE
Ubuntu qt5 support

### ISSUE THREAD

**Issue by jwg2s** [thoughtbot/capybara-webkit#863]
I noticed the documentation says capybara-webkit fails to build against qt5 on ubuntu 14.04.  Is this still the case?

https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit
![image](https://cloud.githubusercontent.com/assets/832769/11480409/5329b30a-9765-11e5-9f11-181a1d659760.png)

Is there a timeline to fix?  We are noticing inconsistencies running capybara-webkit on Mac qt4 vs ubuntu 14.04 qt4 which is naturally very frustrating from a CI perspective.

Please let me know if I can provide more details.

**Comment by mhoran** [comment]
I'm not sure where that note came from, but Qt 5 is now recommended over Qt 4. With the packages defined in our `.travis.yml`, you should have no trouble getting set up.

**Comment by jwg2s** [comment]
@mhoran it's from the wiki of this repo (link in OP)

**Comment by jferris** [comment]
@jwg2s anybody can edit the Wiki without approval, which is both awesome and terrifying. It's the best source for install directions, because we can't personally test on every system, but it's also completely user-contributed without any kind of editorial process.

I'll take a pass through to try and clean out the Qt 4 info. I know the project builds properly on Ubuntu's Qt 5 packages, so that note is incorrect.

**Comment by jferris** [comment]
I removed a number of recommendations for Qt 4 and deleted instructions for some older systems that only support insanely old versions.

You should be able to use the same instructions as Debian. Please report back if it doesn't work with those packages. I've seen reports that you also need gstreamer on Ubuntu, but this doesn't seem consistent.

**Comment by jwg2s** [comment]
@jferris agree with you there!  Can't that setting be changed though?  Anyways, thanks for the update and I'll take another crack at it.

**Comment by jferris** [comment]
> Can't that setting be changed though?

Hmm, we can change it so that only maintainers have the ability to change the wiki, but then I don't see a way for the community to contribute.

**Comment by jwg2s** [comment]
Just a matter of deciding which one is worse, slow but correct information or easily editable but possibly incorrect information :)
