### ISSUE TITLE
find(".hidden-checkbox", visible: false).set(true) fails due to visibility error

### ISSUE THREAD

**Issue by knoopx** [thoughtbot/capybara-webkit#864]
`find(".hidden-checkbox", visible: false).set(true)` fails due to visibility error fails even when explicitly setting `visible: false`. My guess is that the inner calls `set` performs do not forward `visible: false` option.

**Comment by twalpole** [comment]
This is as expected - A User can't check a non-visible box so neither will capybara-webkit

**Comment by knoopx** [comment]
Well the second argument supposedly overrides that behaviour... Otherwise what's the point of it?

**Comment by twalpole** [comment]
@knoopx It allows to find a hidden element, verify its presence in the page, query its attributes/value - but you can't change it because a user couldn't - If you need to set the checkbox do what user would have to do to set the checkbox, otherwise you're not actually testing your app.
