### ISSUE TITLE
Segmentation fault in connection

### ISSUE THREAD

**Issue by jwg2s** [thoughtbot/capybara-webkit#866]
We are getting this error on master with Circle CI.  It's killing our productivity and seems to be happening intermittently :(.  Any suggestions?

We are running on linux, ruby 2.2.3, capybara-webkit 1.7.1, capybara 2.5.0.

```
....****.............../home/ubuntu/enforcery/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.7.1/lib/capybara/webkit/connection.rb:40: [BUG] Segmentation fault at 0x00000000000000
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0088 p:---- s:0350 e:000349 CFUNC  :write
c:0087 p:---- s:0348 e:000347 CFUNC  :print
c:0086 p:0013 s:0344 e:000343 METHOD /home/ubuntu/enforcery/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.7.1/lib/capybara/webkit/connection.rb:40
c:0085 p:0031 s:0340 e:000339 BLOCK  /home/ubuntu/enforcery/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.7.1/lib/capybara/webkit/browser.rb:209 [FINISH]
c:0084 p:---- s:0337 e:000336 CFUNC  :each
c:0083 p:0036 s:0334 e:000333 METHOD /home/ubuntu/enforcery/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.7.1/lib/capybara/webkit/browser.rb:207
c:0082 p:0017 s:0328 e:000327 METHOD /home/ubuntu/enforcery/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.7.1/lib/capybara/webkit/browser.rb:236
c:0081 p:0079 s:0322 e:000321 METHOD /home/ubuntu/enforcery/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.7.1/lib/capybara/webkit/driver.rb:274
c:0080 p:0035 s:0317 e:000316 METHOD /home/ubuntu/enforcery/vendor/bundle/ruby/2.2.0/gems/capybara-2.5.0/lib/capybara/session.rb:672
```

**Comment by jferris** [comment]
It looks like it's happening in Ruby and not in `webkit_server`. Is that correct?

We don't actually have any C extensions in the gem. We compile a separate binary and connect to it over a socket. From your paste, it looks like Ruby is segfaulting while trying to write to the socket, which is...surprising!

Are there any native extensions you have that could be causing this? I've seen segfaults before with ruby-debug/byebug, particularly with async code.

**Comment by jwg2s** [comment]
Interesting -- I'll go ahead and close this issue.  I'm going to try not including byebug when pushing to Circle and see if that helps.  Thanks!  I'll post here with my results in case anyone else finds this.

**Comment by jwg2s** [comment]
So far this has had very positive impact - thanks for the tip!

**Comment by jferris** [comment]
Glad to hear it!
