### ISSUE TITLE
Testing CodeMirror with CapybaraWebkit

### ISSUE THREAD

**Issue by tansaku** [thoughtbot/capybara-webkit#870]
We're writing some tests to check the operation of a site using [codemirror](https://github.com/codemirror/CodeMirror). We're using capybara webkit, but it's not clear how to simulate entering text into the editor.

I've found some mention of a solution online that involves making an editor variable global which feels like a bit of a hack:

http://stackoverflow.com/questions/30376526/fill-in-editor-textarea-using-capybara-webkit

Does anyone know of a good way we can use to enter code into codemirror using Capybara Webkit or similar that's a bit less hacky?

**Comment by jferris** [comment]
I think the most standard way would be to use `send_keys` from Capybara:

``` ruby
page.find('#codemirror-element').send_keys("hello")
```

Unfortunately, we haven't implemented `send_keys` in capybara-webkit yet. It should be possible using QtWebkit, but we haven't gotten around to it. You could use the `selenium` driver for those tests for now.

**Comment by tansaku** [comment]
thanks @jferris - great suggestion.
