### ISSUE TITLE
Support for HTML5 validation?

### ISSUE THREAD

**Issue by attilagyorffy** [thoughtbot/capybara-webkit#879]
Hi,

I'm trying to test my HTML5-based application that has a few input and select fields that have a `require` attribute. I was wondering whether capybara-webkit supports this functionality. I'd expect my form not to be submitted if a required field is left blank.

I'd like to ideally use and test the browser's built-in feature without having to write a polyfill in javascript for this.

Thanks in advance.

**Comment by twalpole** [comment]
Web features are determined by the version of QtWebkit used -- Capybara-webkit can't implement this.
