### ISSUE TITLE
Capybara::Webkit::InvalidResponseError when working with subdomains.

### ISSUE THREAD

**Issue by apux** [thoughtbot/capybara-webkit#881]
I am using capybara-webkit with RSpec to test a Rails 3 project, but I am getting a Capybara::Webkit::InvalidResponseError.

The project runs with this software:

Linux (chakra linux) and Mac (el capitan)
Ruby 1.9.3
Rails 3.2.22
RSpec 3.3.2
Capybara 2.6.2
capybara-webkit 1.8.0
Qt 4.8.1

It seems like the problem happens only when working with subdomains. I created an empty project to show the issue.

The project is very simple, in routes:

```ruby
match "/" => "home#index_admin", :constraints => { :subdomain => 'admin' }
match "/" => "home#index_guest"
```

The views are:

For home/index_admin
```erb
<h1>Welcome Admin</h1>
```

For home/index_guest
```erb
<h1>Welcome Guest</h1>
```

The tests are very simple too (I'm using example.com for localhost):

```ruby
require 'rails_helper'

feature "test subdomain" do
  scenario "shows a page with no subdomain with no js" do
    visit "/"
    expect(page).to have_content("Welcome Guest") # PASS
  end

  scenario "shows a page with no subdomain with js", js: true do
    visit "/"
    expect(page).to have_content("Welcome Guest") # PASS
  end

  scenario "shows a page with subdomain with no js" do
    visit "http://admin.example.com/"
    expect(page).to have_content("Welcome Admin") # PASS
  end

  scenario "shows a page with subdomain with js", js: true do
    visit "http://admin.example.com/"
    expect(page).to have_content("Welcome Admin") # FAIL
  end
end
```

In spec/rails_helper:
```ruby
Capybara.javascript_driver = :webkit_debug

Capybara::Webkit.configure do |config|
  config.allow_url("admin.example.com")
end
```

You can see the tests in travis, where I used webkit_debug as driver: https://travis-ci.org/apux/cwebkit_js_test

As you can see, the only failing test is the one with `js: true` and subdomain. The other combinations pass.

Any ideas about this issue? Are there any other information you need?

**Comment by jferris** [comment]
Most of the JavaScript drivers, including capybara-webkit, perform actual network requests when hitting your application. This means it needs to be able to resolve a DNS lookup for your URLs and access the given address.

When you configure `admin.example.com` as an allowed URL, that means capybara-webkit will try to actually visit that URL instead of immediately returning a fake response. However, that still needs to be a real, accessible URL. Capybara spins up a server in a background thread on a random port and uses that URL when you don't specify a domain, which is why it works when subdomains aren't part of the equation.

You could use something like `lvh.me` or custom DNS entries if you need to access specific subdomains during tests.

I'm going to close this issue, as I don't believe it's a bug, but feel free to keep commenting and asking questions if you need more help.

**Comment by apux** [comment]
Thanks for the answer.

I found that by adding this configuration

```ruby
Capybara.configure do |config|
  config.always_include_port = true
end
```

I am able to run the tests locally (all tests pass), but the last one is still failing in travis.

I'm wondering how `lvh.me` impacts in the speed. Does it slow down the tests too much?

**Comment by jferris** [comment]
> Does it slow down the tests too much?

I haven't tried this personally, so you'd have to benchmark for a 100% answer. However, I believe it should be a minimal overhead. The browser will do a DNS lookup for `lvh.me` and find out it resolves to `127.0.0.1`. The DNS lookup should be cached at several layers, so it should perform similarly to a test which references `127.0.0.1` in the URL, which is what Capybara is doing by default.

**Comment by apux** [comment]
Thanks again. Using `lvh.me` make the tests pass even in travis.

**Comment by Xosmond** [comment]
Same problem for me and solved same way 😄. Thank you and thanks to the issues history.

**Comment by flapjackfritz** [comment]
I too had a similar issue.

When running the tests, I would get the error (only sometimes):
```ruby
     Capybara::Webkit::InvalidResponseError:
       Unable to load URL: http://es.example.com/newest because of error loading http://es.example.com/newest: Unknown error
```

and my capybara-webkit debug output was telling me:
```
Finished "Visit(http://es.example.com/newest)" with response "Success()"
Received 0 from "http://es.example.com/newest"
Page finished with false
Load finished
Page load from command finished
Wrote response false "{\"class\":\"InvalidResponseError\",\"message\":\"Unable to load URL: http://es.example.com/newest because of error loading http://es.example.com/newest: Unknown error\"}"
Received "CurrentUrl()"
Started "CurrentUrl()"
Finished "CurrentUrl()" with response "Success(about:blank)"
Wrote response true "about:blank"
Received "CurrentUrl()"
Started "CurrentUrl()"
Finished "CurrentUrl()" with response "Success(about:blank)"
Wrote response true "about:blank"
Received "Reset()"
Started "Reset()"
undefined|1|SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
```

I was able to solve it by adding to my /etc/hosts file:
`127.0.0.1 es.example.com`

And then in my spec_helper
```ruby
Capybara.configure do |config|
  config.always_include_port = true
end
```

Hope this helps someone.
