### ISSUE TITLE
Link in the "Need Help?" section of the README is broken

### ISSUE THREAD

**Issue by Florent2** [thoughtbot/capybara-webkit#886]
The "Get in touch" links point to https://thoughtbot.com/rails/?utm_source=github but this page returns "Page Not Found".

**Comment by jferris** [comment]
Thanks for pointing that out. I removed the bad links in https://github.com/thoughtbot/capybara-webkit/commit/109f063812e53eedda0ea2d801ec1e4389f4a91c.

If you'd like to get in touch with thoughtbot, you can do so via email, phone or a contact form on our [locations page](https://thoughtbot.com/locations).
