### ISSUE TITLE
Unable to fill in input field using capybara-webkit

### ISSUE THREAD

**Issue by gregblass** [thoughtbot/capybara-webkit#888]
I have javascript feature specs that are working fine with selenium, but I'd like to switch to capybara-webkit for a number of reasons (CI, not popping up a browser window, etc).

I'm trying to switch over from selenium, but something is preventing my code from working correctly. I have the following helper:

    def capybara_login(user)
      visit login_path
      fill_in "email", with: user.email
      fill_in "password", with: user.password
      click_button "Log in"
    end

Here's my input field that is being outputted:

    <input type="email" name="email" id="email" value="" class="form-control" placeholder="you@domain.com" autocomplete="off">

I've tested that user.email is not nil. For some reason when I use capybara-webkit, this fails and nothing is filled in (I'm checking by doing a save_and_open_page). However, this code works fine if I use regular capybara(non js) or selenium for js.

Am I missing something? Any ideas as to what could be preventing capybara webkit from filling in these fields?

**Comment by gregblass** [comment]
I removed all the content in my <head> and it worked. And I now realize that save and open page will not actually show any values. I'm going to continue debugging/removing things (probably some type of js conflict).

**Comment by gregblass** [comment]
This was not an issue at all with capybara-webkit, but some javascript that was running in my specific project only for webkit that was causing a delay - hence it happening only in that case.

**Comment by jferris** [comment]
Glad to hear everything worked out. I've found that `save_and_open_screenshot` is generally more useful than `save_and_open_page`.
