### ISSUE TITLE
getting no javascript in pages

### ISSUE THREAD

**Issue by MaxPleaner** [thoughtbot/capybara-webkit#889]
I am using this gem with my Rails app. My `config/initializers/capybara.rb` file is as follows:

``` ruby
require 'capybara/rails'
Capybara.default_driver = :webkit
Capybara.javascript_driver = :webkit
HttpAgent = Capybara.current_session
```

I am running the server with Rails, so `config.ru` hasn't been changed.

When I get a page with `HttpAgent.visit("https://www.crunchbase.com/search")`,
I receive a no-javascript version of the page. There are no errors in my console. 

By the way, I am using this in my `development` environment, not `test`.

**Comment by twalpole** [comment]
Closing due to lack of response
