### ISSUE TITLE
JS Date objects not returned like Selenium

### ISSUE THREAD

**Issue by jasonkarns** [thoughtbot/capybara-webkit#892]
With Selenium, a JavaScript Date object can be serialized back to Ruby (as a Ruby string):

```sh
irb(main):006:0> Capybara.current_driver = :selenium
=> :selenium
irb(main):007:0> Capybara.current_session.evaluate_script "new Date()"
=> "2016-03-25T19:24:59.484Z"
irb(main):008:0> Capybara.current_session.evaluate_script "new Date().toString()"
=> "Fri Mar 25 2016 15:25:04 GMT-0400 (EDT)"
```

However, with capybara-webkit, a JavaScript Date object comes back as `nil`:
```sh
irb(main):003:0> Capybara.current_driver = :webkit
=> :webkit
irb(main):004:0> Capybara.current_session.evaluate_script "new Date()"
WARNING: The next major version of capybara-webkit will require at least version 5.0 of Qt. You're using version 4.8.7.
=> nil
irb(main):005:0> Capybara.current_session.evaluate_script "new Date().toString()"
=> "Fri Mar 25 2016 15:24:35 GMT-0400 (EDT)"
```

**Comment by jferris** [comment]
We generally try to be compatible with Selenium when it makes sense, so I think this could be classified as a bug. However, this seems like a pretty strange case to me: it doesn't make a ton of sense to evaluate something that returns an object and expect a string in return. The Selenium behavior is even stranger given that the string it returns looks different than just calling `toString` on the object.

If you're interested in submitting a pull request that changes this to work like Selenium, I'd merge it. However, I don't think this is a big enough issue that I'll ever have time to fix it.

I'm going to close this issue, but feel free to keep commenting if you have further thoughts or would like help on starting a pull request.

**Comment by jasonkarns** [comment]
I believe, but haven't confirmed, that the string representation from
selenium is the toUTC variant, thus making date parsing in ruby trivial. I
agree that the expected behavior would be to get a DateTime, back. However,
the selenium behavior at least allows the application to do the parsing
itself so the result isn't lost entirely. I can hopefully tackle a pr for
this. Do you mind pointing me to where current handling of response values
is done and I can go from there?

**Comment by jferris** [comment]
The call stack for evaluating a JavaScript values looks roughly like:

* The Ruby driver calls [`Browser#evaluate_script`](https://github.com/thoughtbot/capybara-webkit/blob/master/lib/capybara/webkit/browser.rb#L226).
* That dispatches an [`Evaluate` command](https://github.com/thoughtbot/capybara-webkit/blob/master/src/Evaluate.cpp) in the C++ driver.
* The command calls `evaluateJavaScript` on the current web frame.
* The command uses our [JSON serializer](https://github.com/thoughtbot/capybara-webkit/blob/master/src/JsonSerializer.cpp#L7) to create a JSON string from the evaluated result.
* The Ruby driver receives the JSON string and parses it into native Ruby objects.

We could add a special case to the JSON serializer for handling dates, although I'm not sure what the actual result is that we get back from QtWebKit in that case.
