### ISSUE TITLE
centos 6.7 qt 5.6

### ISSUE THREAD

**Issue by yairgo** [thoughtbot/capybara-webkit#904]
Using centos 6.7, I just followed the instructions here:

https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit

And qt 5.6 was installed. I don't have any outside repositories enabled. 
The documentation might need to be updated to reflect this. I have not been able to do any digging to see if manually compiling the source works yet, I need to remove all of the qt packages that were installed first.

**Comment by ibnc** [comment]
I'm experiencing the same issue, and it looks like qt 5.5 is no longer available for centos 6.7.

I'd really rather not have to build qt 5.5 from source. Does anyone have any work arounds or fixes?

**Comment by mhoran** [comment]
Please see #885. Qt 5.6 is not supported as QtWebKit has been dropped from the distribution. Unfortunately there are few options for distributions that have dropped Qt 5.5.

**Comment by mhoran** [comment]
Re: documentation, please feel free to edit the wiki page if you manage to find instructions for Qt 5.5. The maintainers of capybara-webkit don't know the intricacies of all the available Linux distributions (in addition to OS X, Windows, etc.) and we rely on the community to keep the instructions up to date.

**Comment by yairgo** [comment]
@mhoran If I get it working I will gladly update the documentation. I wanted to post the issue incase other people experience the same thing. Trying to install from source now.

**Comment by anthonypenner** [comment]
For the record, the [instructions for CentOS 6.5/6.6](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#centos-6566) worked for me on CentOS 6.7. Just switch out qt for the correct version of 5.5 obviously.
