### ISSUE TITLE
have_xpath not working after v1.9.0

### ISSUE THREAD

**Issue by benthorner** [thoughtbot/capybara-webkit#919]
For example, running

   expect(page).to have_xpath("//input[@value='ifName' and contains(@disabled, '')]")

gives the following error

   wrong number of arguments (given 0, expected 1) (ArgumentError)

**Comment by twalpole** [comment]
@benthorner Can you provide a stacktrace?

**Comment by benthorner** [comment]
Hmmm...can't reproduce this now. Closing as not reproducible - sorry for the trouble :-)
