### ISSUE TITLE
#visit is not triggering events.

### ISSUE THREAD

**Issue by alestuber** [thoughtbot/capybara-webkit#927]
My problem is the following: we use some external libraries like typeahead.js (twitter's one for autocomplete funcionality) and on every page load I have to initialize the search form object (this is done through the "turbolinks:load" event (turbolinks 5).

Image of the file that initializes the typeahead (it's also included on application.js):
![image](https://cloud.githubusercontent.com/assets/7633046/16890505/ad01c9e4-4ac5-11e6-9370-26f2cba507bc.png)

It works well on development but when I was writing a feature spec to get this behavior it started failing and when I got into it (binding.pry and open in the browser) I saw that none of the events were triggered after the visit page method. This is preventing the initialization of the library and the functionality is not working on the spec (and I can't test the autocomplete then).

The JS files are also not initialized (they're within a gem).

I made sure of it by putting inside my view a script tag with a) the full code from typeahead (not the gem), directly from the original repository and b) this initialize code without binding it to anything (just running it once).

After doing this it worked (proving that the gem code and . I searched a lot trying to find some ways to solve this and found nothing so I guess I should be doing something really stupid on the configuration options or something like this.

Any clues?

**Comment by seandilda** [comment]
I'm running into a similar problem.  What was the resolution to this?
