### ISSUE TITLE
1.11.1 OOM on CircleCI

### ISSUE THREAD

**Issue by eric-hu** [thoughtbot/capybara-webkit#930]
Hi there!

I work in support at CircleCI, and we've had customers facing an OOM issue because Capybara-Webkit takes up multiple gigabytes of memory on CircleCI's Ubuntu 14 container.

I believe this has something to do with CircleCI's QT version.  It's 5.2, which is a couple of years old.  It's not clear to me which version of QT would be best to upgrade the image to.  On this project's [wiki](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#homebrew) 5.5 is said to be the last supported version of QT, since 5.6 ships without qt-webkit.  On the other hand, [the recent release notes](https://github.com/thoughtbot/capybara-webkit/blob/master/NEWS.md) say there's support for 5.6 with the QTwebkit module.

Can you make a suggestion as to which would be better?

P.S. If there's any debug information you would like to see, please share and I'll see what I can gather.

P.P.S.  Thank you for making this fine tool.  :)

**Comment by mhoran** [comment]
Hey @eric-hu. Qt 5.5 is the most recent recommended version. QtWebKit has been removed from the binary distribution of Qt 5.6+ and is no longer maintained. We initially disabled compiling against Qt 5.6 but later discovered that some Linux distributions were including the QtWebKit module in their 5.6 distribution.

There's now a project to revive the QtWebKit module as well, but I think it's in early stages. So my recommendation for now would be to upgrade Qt to 5.5 at least, and see if that helps with the memory issue. I've also been investigating porting capybara-webkit to Chromium, but the effort is stalled at the moment.

**Comment by eric-hu** [comment]
Great, I'll suggest Qt 5.5 to the image maintainer.  Thank you for the quick response!
