### ISSUE TITLE
Capybara::Webkit with xvfb / Headless gem test.log output cut off

### ISSUE THREAD

**Issue by gtd** [thoughtbot/capybara-webkit#932]
This is a weird one.  I'm running rails 4.0.13, minitest 4.7.5, capybara 2.7.1, capybara-webkit 1.11.1, headless 2.2.3 on ubuntu 14.04.

What happens is when I run a test, I get the usual output in `log/test.log` until the first page request thorugh capybara-webkit completes.  Then the test.log is silent until the next test run.  I've simplified the setup down to be very sure that no logs are escaping after the first request by the headless browser completes.  The last line is always a very tidy Rails success message:

```
Completed 200 OK in 533ms (Views: 471.7ms | ActiveRecord: 5.0ms)
```

Note that tests continue to run after this with their usual success/failure, but no more output is logged.

I've tried this with the headless gem, and also running `xvfb-run -a ruby -Itest ...` on the command-line and the symptom is the same.  If I change to the default driver then there is no issue on the very same tests.

I've Googled pretty deeply and not been able to find anyone else experiencing the same issue.  Any ideas?

**Comment by twalpole** [comment]
Is this still an issue with current versions of things?

**Comment by twalpole** [comment]
Closed due to lack of response
