### ISSUE TITLE
Anchored Top Nav On Top of Clickable Elements

### ISSUE THREAD

**Issue by nartz** [thoughtbot/capybara-webkit#934]
My site 'anchors' the top nav as the user scrolls down the page (pretty standard). The issue is when using capybara to test a button click (click_button 'Save') or otherwise, it seems that capybara tries to scroll to the button and click it, however, often the top nav covers up where capybara is trying to click.

Are there any recommended ways to counter this in capybara?

My current workaround is to execute javascript 'scrollToView(false)' which scrolls until the bottom of the object is at the bottom of the viewable window (and thus is not covered by a top nav).

```
def scroll_to(element)
    script = <<-JS
      arguments[0].scrollIntoView(false);
    JS
    Capybara.current_session.driver.browser.execute_script(script, element.native)
end
```

However, I imagine anchoring the top nav scenario is pretty common, and that possibly this affects others?

**Comment by twalpole** [comment]
One option is to resize the window so scrolling isn't necessary

**Comment by cyrilchampier** [comment]
is there any way to add the center parameter to this call ?
`.scrollIntoView({block: 'center'})` would solve this problem

**Comment by twalpole** [comment]
@cyrilchampier It's not supported by QtWebkit (basically a 5-6 year old browser at best)
