### ISSUE TITLE
Incorrect input data using Capybara-webkit

### ISSUE THREAD

**Issue by Xosmond** [thoughtbot/capybara-webkit#935]
Im using devise for authentication and when i login with no javascript, everything works well, but when i add capybara-webkit as javascript engine, i get an error saying that the login information is incorrect.

When i did "save_and_open_screenshot" i saw that the fields were filled before click on login button.
code
```ruby
describe "process", :type => :feature do
  let(:valid_attributes) { attributes_for(:user, rol: 'Administrador') }

  before :each do
    User.create(valid_attributes)
    visit '/users/sign_in'
    within(".form-inputs") do
      fill_in 'user[login]', :with => valid_attributes[:email]
      fill_in 'user[password]', :with => valid_attributes[:password]
    end
    click_button 'Ingresar'
  end

  it 'go to page', :js => true do
    click_link 'personal'
  end
end
```
What could be the problem here?

PD: When i do this:
```ruby
    puts valid_attributes[:email]
    puts find_field('user[login]').value
    puts valid_attributes[:password]
    puts find_field('user[password]').value
```
Im getting these:
```
alf_smitham@yahoo.com
alf_smitham@yahoo.com
misteriolopmg32
misteriolopmg32
```

So the fill action is working correctly.
PD2: getting same problem with Poltergeist now.

**Comment by twalpole** [comment]
Usually this means you're still using transactional testing so the records created in your test aren't visible to the app - see  https://github.com/jnicklas/capybara#transactions-and-database-setup

**Comment by jferris** [comment]
I'd also recommend using `FactoryGirl.create` or calling `User.create!` so that you see a failure message when a record fails to save.

This doesn't look like a bug in capybara-webkit, so I'm going to close this issue. However, feel free to continue commenting and asking for help.

**Comment by Xosmond** [comment]
Alright, twaddle was correct, i had to use database_cleaner to use truncation.
