### ISSUE TITLE
"ReferenceError: Can't find variable: Promise"

### ISSUE THREAD

**Issue by Xosmond** [thoughtbot/capybara-webkit#936]
Im use some libraries that use Promises, and im getting this error:
"ReferenceError: Can't find variable: Promise". How i solve this? Now i have no idea.

PD: I have Qt55.

**Comment by twalpole** [comment]
Promise is an ES6 feature and ES6 is not support by QtWebKit - https://github.com/thoughtbot/capybara-webkit/issues/849 - you need to either transpile or use a polyfill to use Promise with capybara-webkit

**Comment by Xosmond** [comment]
I have no idea how to do that, but since this it's known as a non bug, i close this.
