### ISSUE TITLE
Possible to silence "Attempt to select disabled option"?

### ISSUE THREAD

**Issue by gkop** [thoughtbot/capybara-webkit#941]
In the course of my tests, I am asserting that a disabled option cannot be selected, by using capybara's `choose` method on the option. Is there a way to accomplish this without triggering the warning in the console "Attempt to select disabled option"?

(On v1.11.1, testing against qt 4.8.1 and 5.3.2)

**Comment by twalpole** [comment]
This message comes from Capybara not capybara-webkit, and there's no way to disable it if you're calling choose.  Rather than try and choose it you could just verify the option is disabled with something like

    expect(page).to have_selector(:option, 'The option', disabled: true)

**Comment by gkop** [comment]
That sounds good, thanks for the quick reply!
