### ISSUE TITLE
Qt 55 install issues

### ISSUE THREAD

**Issue by mjfaga** [thoughtbot/capybara-webkit#942]
Hey guys, I attempted to follow the wiki instructions [here](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit), but am noticing some issues when executing the `sudo port install qt5` command. It looks like it's pulling the latest package from macports, which is now 5.6.1:

``` bash
sudo port install qt5
--->  Computing dependencies for qt5
--->  Fetching archive for qt5
--->  Attempting to fetch qt5-5.6.1_0.darwin_15.noarch.tbz2 from https://packages.macports.org/qt5
--->  Attempting to fetch qt5-5.6.1_0.darwin_15.noarch.tbz2.rmd160 from https://packages.macports.org/qt5
--->  Installing qt5 @5.6.1_0
--->  Activating qt5 @5.6.1_0
--->  Cleaning qt5
--->  Updating database of binaries
--->  Scanning binaries for linking errors
--->  No broken files found.
```

Any idea how to work around this? I've already uninstalled all other versions of Qt, and run through the wiki commands for OS X El Capitan 10.11:

``` bash
brew tap homebrew/versions
brew install qt55
brew link --force qt55
which qmake # returns correct directory
sudo port install qt5 # installs qt5-5.5.1
```

**Comment by timdiggins** [comment]
@mjfaga This looks like an old post which you've probably solved by now. But just for the record, I think you're trying to mix and match homebrew (which is in the wiki) with macports. Just running one is enough. I've added a line in the wiki to clarify. 

Suggest this issue is closed now.

**Comment by twalpole** [comment]
Closing as per suggestion
