### ISSUE TITLE
OSX 10.11 qt55 qmake error

### ISSUE THREAD

**Issue by Judahmeek** [thoughtbot/capybara-webkit#948]
Having successfully installed qt55,...
```
brew tap homebrew/versions
brew install qt55
brew link --force qt55
which qmake # returns correct directory
```
...I get the following error when attempting to bundle capybara-webkit: `Command 'qmake LIBS\ \+\=\ -L/usr/local/opt/libyaml/lib\
-L/usr/local/opt/readline/lib\ -L/usr/local/opt/libksba/lib\
-L/usr/local/opt/openssl/lib' failed`

I've checked `/usr/local/opt/` and `libyaml`, `readline`, `libska`, and `openssl` are all there. Running  `qmake LIBS\ \+\=\ -L/usr/local/opt/libyaml/lib\ -L/usr/local/opt/readline/lib\ -L/usr/local/opt/libksba/lib\ -L/usr/local/opt/openssl/lib` directly from the terminal opens help like there's some sort of syntax error.

Anyone run into a similar issue?

**Comment by jferris** [comment]
Is there any other output when you try `gem install capybara-webkit`? Do you know which version you're trying to install?

**Comment by Judahmeek** [comment]
Here is all the error output:```Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/judahmeek/.rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.11.1
/Users/judahmeek/.rvm/rubies/ruby-2.3.1/bin/ruby -r
./siteconf20160914-484-138wg7q.rb extconf.rb
Project ERROR: Xcode not set up properly. You may need to confirm the license
agreement by running /usr/bin/xcodebuild.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/judahmeek/.rvm/rubies/ruby-2.3.1/bin/$(RUBY_BASE_NAME)
	--with-gl-dir
	--without-gl-dir
	--with-gl-include
	--without-gl-include=${gl-dir}/include
	--with-gl-lib
	--without-gl-lib=${gl-dir}/lib
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
Command 'qmake LIBS\ \+\=\ -L/usr/local/opt/libyaml/lib\
-L/usr/local/opt/readline/lib\ -L/usr/local/opt/libksba/lib\
-L/usr/local/opt/openssl/lib' failed

extconf failed, exit code 1

Gem files will remain installed in
/Users/judahmeek/.rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.11.1 for
inspection.
Results logged to
/Users/judahmeek/.rvm/gems/ruby-2.3.1/extensions/x86_64-darwin-15/2.3.0/capybara-webkit-1.11.1/gem_make.out

An error occurred while installing capybara-webkit (1.11.1), and
Bundler cannot continue.
Make sure that `gem install capybara-webkit -v '1.11.1'` succeeds before
bundling.```

**Comment by Judahmeek** [comment]
@jferris I do have XCode 8.0, so this may be a duplication of https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#macos-sierra-1012. However, if so, it requires a slightly different solution since I'm not sure what my equivalent of `Qt_install_folder/[Qt-version]/clang_64/mkspecs/features/mac/default_pre.prf` is.

**Comment by jferris** [comment]
Glad to hear you've solved it. Installing Qt can be rough.

**Comment by seanlinsley** [comment]
I also ran into this problem.

The wiki link above is no longer valid. Here's what it is now: https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#xcode-80

**Comment by RemyMaucourt** [comment]
@Judahmeek I have the exact same problem, and I can't find the solution you mention in the link. Can you elaborate a little?

**Comment by Judahmeek** [comment]
Yeah, link rot is an issue with wiki pages. Fortunately, you can scan the revisions. Here is [my solution.](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit/db9ce9a086205b0177012a2e8808c4ba0d289f76#xcode-80)

@aripollak is there any particular reason you [removed that section](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit/_compare/db9ce9a086205b0177012a2e8808c4ba0d289f76...677f0e56a377ce7bba501019ff76910773c40cce#diff-b00901b164a7d0c2dad00cadca26a956L72) when you updated the wiki?

**Comment by aripollak** [comment]
Yeah, I thought that issue was fixed with newer versions of the Homebrew package. Is that not the case?

**Comment by vassilevsky** [comment]
I have just upgraded to macOS High Sierra 10.13.1 and Command Line Tools 9.1 and I have the same problem 💖

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/vassilevsky/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/capybara-webkit-1.14.0
/Users/vassilevsky/.rbenv/versions/2.4.2/bin/ruby -r ./siteconf20171114-22943-zeyu64.rb extconf.rb
Project ERROR: Xcode not set up properly. You may need to confirm the license agreement by running /usr/bin/xcodebuild.
*** extconf.rb failed ***
```

**Comment by seanlinsley** [comment]
@vassilevsky it looks like you just need to accept the Xcode license. You can do that with: 
```
sudo xcode-select -r
```

**Comment by vassilevsky** [comment]
I have installed and launched Xcode and then it worked.

**Comment by yunixon** [comment]
```
cd /Applications/Xcode.app/Contents/Developer/usr/bin/
sudo ln -s xcodebuild xcrun
```

**Comment by elgreco** [comment]
If you're on MacOS and have installed QT 5.5+ with Brew, make sure that the binary is linked correctly. You can tell it is pointing to the qmake binary correctly by running:

`$ which qmake` 

and seeing that it returns something like /usr/local/opt/qt@5.5/bin/qmake. If it doesn't return anything, it needs to be linked. To link it run this: 

`$ echo 'export PATH="$(brew --prefix qt@5.5)/bin:$PATH"' >> ~/.bashrc`
