### ISSUE TITLE
Installing capybara-webkit 1.1.0 with native extensions

### ISSUE THREAD

**Issue by RajnikRails** [thoughtbot/capybara-webkit#954]
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/kushal/.rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.1.0
/home/kushal/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20160927-23636-xrsrmb.rb extconf.rb
Command 'qmake -spec linux-g++ ' not available

Makefile not found

Gem files will remain installed in /home/kushal/.rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.1.0 for inspection.
Results logged to /home/kushal/.rvm/gems/ruby-2.3.1/extensions/x86_64-linux/2.3.0/capybara-webkit-1.1.0/gem_make.out

An error occurred while installing capybara-webkit (1.1.0), and Bundler cannot continue.
Make sure that `gem install capybara-webkit -v '1.1.0'` succeeds before bundling.

**Comment by RajnikRails** [comment]
I have ubuntu 14.04
rvm 2.3.1
When i am install this gem got above errors.

**Comment by mike-burns** [comment]
Did you follow [the installation instructions from the wiki](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#ubuntu-trusty-1404)?

**Comment by jferris** [comment]
> `Command 'qmake -spec linux-g++ ' not available`

This likely means you need to install Qt. The instructions @mike-burns linked to should help you there.

> capybara-webkit 1.1.0

This is a very old version of capybara-webkit. We have limited resources to dedicate towards support, so we're focused on supporting recent versions.

This doesn't appear to be a bug in capybara-webkit and is related to an older version, so I'm going to close this issue.
