### ISSUE TITLE
Support @media CSS queries

### ISSUE THREAD

**Issue by dkniffin** [thoughtbot/capybara-webkit#960]
As far as I can tell, capybara-webkit doesn't currently support @media queries. These are needed in order to properly test mobile workflows.

Here's someone else that has the same issue: http://stackoverflow.com/questions/37768656/capybara-webkit-not-acknowledging-media-query-for-min-width-in-css

**Comment by twalpole** [comment]
This is most likely an issue with the version of Qt used.
