### ISSUE TITLE
[-] Errno::EPIPE Broken pipe - SSL_accept

### ISSUE THREAD

**Issue by retriple333** [thoughtbot/capybara-webkit#963]
Werid error. I am using the windows/meterpreter/reverse_tcp payload.

Help Please!!

Info:

OS: macOS

Memory: 8 GB

Mac Book Pro

Help me out!!

**Comment by 999jay999** [comment]
I'm having the same issue, can anyone help?

**Comment by twalpole** [comment]
There's not enough info here to even begin to diagnose this.
