### ISSUE TITLE
Mocking a web request like webmock.

### ISSUE THREAD

**Issue by majioa** [thoughtbot/capybara-webkit#967]
How can I mock requests to the external web-sites similar to it is done in webmock?

I saw the access to external resources is allowing/denying by call to the proper method in the config like:

    Capybara::Webkit.configure do |config|
        config.allow_url("www.sandbox.paypal.com")
    end

I wish to use something like:

    Capybara::Webkit.configure do |config|
        config.mock_url("www.sandbox.paypal.com").with(PaypalFake)
    end

where `PaypalFake` is the fake sinatra app. Is it there something like this in `capybara-webkit`?

**Comment by mhoran** [comment]
You'll need to use something like [Puffing Billy](https://github.com/oesmith/puffing-billy) to intercept the request and proxy it to a fake. `Capybara.javascript_driver = :webkit_billy` will set that all up for you, or you can manually set the proxy for capybara-webkit to point to puffing-billy.

**Comment by majioa** [comment]
@mhoran how to set proxy from webkit to puffing-billy?

**Comment by mhoran** [comment]
```ruby
Capybara::Webkit.configure do |config|
  # Use a proxy
  config.use_proxy(
    host: Billy.proxy.host
    port: Billy.proxy.port
  )
end
```

You may also want to set other options as documented here: https://github.com/thoughtbot/capybara-webkit#configuration.
