### ISSUE TITLE
Pasteboard errors with tmux and macOS Sierra

### ISSUE THREAD

**Issue by nickrivadeneira** [thoughtbot/capybara-webkit#968]
I recently got set up on a fresh '16 MBP and have been receiving this error when running Javascript feature tests from within tmux:
```
PasteBoard: Error creating pasteboard: com.apple.pasteboard.clipboard [-4960]
PasteBoard: Error creating pasteboard: com.apple.pasteboard.find [-4960]
```
I've tested with non-JS tests, and with a different JS driver (Poltergeist) and did not receive those errors.

When using `spring`, if the spring server was started from within a tmux session, I'd get the errors regardless of whether the test is called in or out of a tmux session. Conversely, if the spring server was started outside of the tmux session, no error would occur whether in or out of a tmux session.

Additionally, the errors only occurred on the first test that was run in a series of tests. So, if I ran `rspec spec/` and there were a ton of javascript capybara tests, I'd only see those errors once.

The output with debug turned on didn't seem too helpful. I've included 3 lines of generalized Capybara output to show that these errors were rendered before any debug output.
```
Randomized with seed 46479

Some feature test
  It does a thing
PasteBoard: Error creating pasteboard: com.apple.pasteboard.clipboard [-4960]
PasteBoard: Error creating pasteboard: com.apple.pasteboard.find [-4960]
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetUnknownUrlMode(block)"
Started "SetUnknownUrlMode(block)"
Finished "SetUnknownUrlMode(block)" with response "Success()"
...
```

Other details:
- I'm on qt v5.7 installed by Homebrew as per [these instructions](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#macos-sierra-1012)
- tmux v2.3
- macOS v10.12.1
- iterm v3.0.12

If this is actually a qt issue and I'm barking up the wrong tree, feel free to close this out.

**Comment by noplay** [comment]
It's not specific to Capybara. It's an issue with how tmux and OSX interact solutions are available here:
https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard
