### ISSUE TITLE
No package qt5-qtwebkit-devel available.

### ISSUE THREAD

**Issue by loganathan-s** [thoughtbot/capybara-webkit#971]
I'm trying to install capybara-webkit on rhel 6.8 as per the instructions at https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit but I'm getting an error
```

sudo yum install epel-release
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main/latest                | 2.1 kB     00:00     
amzn-updates/latest             | 2.3 kB     00:00     
3729 packages excluded due to repository priority protections
Package epel-release-6-8.9.amzn1.noarch already installed and latest version
Nothing to do
```

```
sudo yum install qt5-qtwebkit-devel
Loaded plugins: priorities, update-motd, upgrade-helper
3729 packages excluded due to repository priority protections
No package qt5-qtwebkit-devel available.
```

**Comment by ZASMan** [comment]
I had the same problem with it not being updated. I ran the following command:
`sudo apt-get install libqt4-dev libqtwebkit-dev build-essential`
Then I ran `sudo apt-get update`.
Used this for reference: https://askubuntu.com/a/314194
