### ISSUE TITLE
Drag_to with google maps markers

### ISSUE THREAD

**Issue by Xosmond** [thoughtbot/capybara-webkit#973]
I have a model that need user to move the marker to get the coordinates of a location. Does exists some way that capybara-webkit can do it? I have tried with `drag_to` but doesn't work, on the screenshot the marker does not appear so i dont know.

By now i just executing some javascript to set the coordinates directly.

**Comment by twalpole** [comment]
What exactly have you tried using `drag_to`, what does "doesn't work" mean?  What does the HTML look like?

**Comment by Xosmond** [comment]
The html render the map but the marker doesn't appear on the map so i can't drag it. Also i couldn't figure out how to select the maker because marker properties depend of the window that renders it.

I have tried to print error messages but there are not error messages.

**Comment by twalpole** [comment]
@Xosmond Without an example and specific code that you're trying to use no one is going to be able to answer this.
