### ISSUE TITLE
Whitelist tests failing

### ISSUE THREAD

**Issue by twalpole** [thoughtbot/capybara-webkit#979]
@jferris @mhoran  The whitelist tests now fail on travis due to ~~example.com not resolving/responding  - do you have a different site/set of urls you'd prefer to use for these tests, implement a proxy to respond for those tests, etc?~~ unknown reason

**Comment by mhoran** [comment]
I saw your comment elsewhere and thought we could add an entry to /etc/hosts so this resolves.

It's disappointing that this domain no longer resolves on Travis as there's a purpose to this domain.


On February 8, 2017 12:41:49 PM EST, Thomas Walpole <notifications@github.com> wrote:
>@jferris @mhoran  The whitelist tests now fail on travis due to
>example.com not resolving/responding  - do you have a different
>site/set of urls you'd prefer to use for these tests, implement a proxy
>to sue for those tests, etc?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/thoughtbot/capybara-webkit/issues/979

-- 
Sent from my mobile device.

**Comment by twalpole** [comment]
@mhoran Yes an entry can be added using the  addons: hosts  key in .travis.yml but we don't know what port to put into the html so a response is returned (nothing running on 127.0.0.1:80)

**Comment by mhoran** [comment]
Can we just put in the IP currently associated with example.com to the hosts key? `93.184.216.34`. Unless Travis blocks this by firewall rules, then I guess we'll have to come up with something else.

**Comment by twalpole** [comment]
@mhoran The `addons: hosts:` key in .travis.yml only allows for adding adding hostnames that resolve to 127.0.0.1 - one could possibly manually cat to /etc/hosts but that will remove the ability to ever move away from `sudo: required` in the travis config.

**Comment by twalpole** [comment]
@mhoran Gave it a try - but looks like /etc/hosts is not writable except through the `addons: hosts:` key which only adds names resolving to 127.0.0.1

**Comment by jferris** [comment]
Are we positive that it's failing to resolve that domain? It's a reserved domain, but it's otherwise a normal domain, resolved by root nameservers as usual. We even have a check in `spec_helper.rb` to make sure `example.com` is resolvable.

I think it's unlikely the behavior of `example.com` changed, so it's probably a change in how we're handling the response. Maybe we were somehow swallowing the error in older versions of RSpec or something?

**Comment by twalpole** [comment]
@jferris Hmmm....  the failures are identical to a non-resolvable host, but you are correct that it appears (at least before the tests run) it is resolvable and replies.  However I don't think it is an RSpec issue because it happens with build runs that worked fine last week, and is occcuring on branches that don't have upgraded RSpec.

**Comment by twalpole** [comment]
Did http://example.com/path exist previously?

**Comment by mhoran** [comment]
Yeah, looks like it did according to archive.org.

On Thu, Feb 09, 2017 at 12:43:28PM -0800, Thomas Walpole wrote:
> Did http://example.com/path exist previously?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/thoughtbot/capybara-webkit/issues/979#issuecomment-278767439

-- 
Matt Horan matt@matthoran.com http://matthoran.com/

**Comment by twalpole** [comment]
@mhoran - Ok - maybe thats the issue - it 404s now

**Comment by twalpole** [comment]
@mhoran @jferris  Looks like this issue has gone away on its own, (travis firewall, example.com config, alien interference, etc...) if you want to restart the travis runs of some of the recent PRs

**Comment by twalpole** [comment]
@mhoran Could you please restart the travis builds for PR #975 and PR #977

**Comment by jferris** [comment]
I restarted those two builds.

**Comment by mhoran** [comment]
Oh, so did I (which is why I think @twalpole closed this.

**Comment by twalpole** [comment]
@jferris @mhoran  Sorry - should have commented when I closed this -- Yes I saw they had ben rerun and closed.  There are a few PRs waiting that would be good to get merged if/when you have the time.

**Comment by twalpole** [comment]
And I guess the issue was something to do with - https://blog.travis-ci.com/2017-02-13-feb4-container-based-issues-postmortem
