### ISSUE TITLE
Missing elements on screenshots

### ISSUE THREAD

**Issue by BroiSatse** [thoughtbot/capybara-webkit#985]
Hi all, 

We are having some issues with screenshots made during the capybara tests. Some of the elements are just not there - initially we fought it only affects modals (both bootstrap ones and the ones we've made), however we also noticed this is happening even for our main layout navigation and footer (see below):
![capybara-201703011507187244913248](https://cloud.githubusercontent.com/assets/2413414/23467945/4dc1e474-fe97-11e6-9042-d598f7d713fb.png)

I started playing with navigation styling to figure out what's wrong and it seems to be related with z-index. After removing z-index from the stylesheets the screenshot looks like below:
![capybara-201703011508307641479191](https://cloud.githubusercontent.com/assets/2413414/23467991/71681a9c-fe97-11e6-8a0e-2bb16ce092a2.png)

So now we can only see the navigation bar. Can anyone advice?

```
> puts page.driver.version

Capybara: 2.7.1
capybara-webkit: 1.11.1
Qt: 5.6.1
WebKit: 538.1
QtWebKit: 5.6.1
```

**Comment by samstickland** [comment]
This problem is still plaguing us. Any hints on how we can go about debugging this?

**Comment by twalpole** [comment]
This is due to the level of JS/CSS support provided by QtWebkit, the only "solution" to get screenshots looking exactly like the page is to make sure the page is only using CSS that was supported 5-6 years ago - Nothing capybara-webkit can really do about it.
