### ISSUE TITLE
How to fix "Your browser needs to be updated"

### ISSUE THREAD

**Issue by ifyouseewendy** [thoughtbot/capybara-webkit#989]
It took me some time to finally configure well QT(5.5), Xcode and capybara-webkit (1.12.0). When I started to write my test, I got this warning after running `save_and_open_page`:

![image](https://cloud.githubusercontent.com/assets/1019171/23836958/c33ad13a-0756-11e7-8745-d1cfddb4249a.png)

Could anyone please give some advice on the case? Thanks!

**Comment by mvz** [comment]
@ifyouseewendy this really depends on what you're trying to do. Why are your tests loading a page on Shopify?

**Comment by jferris** [comment]
I'm going to close this issue, as it doesn't seem like a bug in capybara-webkit, but if you can describe what your tests are doing that causes that warning, feel free to ask for more help.
