### ISSUE TITLE
Problem inserting data

### ISSUE THREAD

**Issue by raamonzera** [thoughtbot/capybara-webkit#999]
When entering a phone number, when the part with ifen arrives, the typing cursor returns to the initial field, so that when entering the sequence "123456" the expected would be "123-456", but the result is "123-564". Any suggestion?

* Only in Mobile devices

**Comment by twalpole** [comment]
It could be because the keys are sent too fast for the JS on the page to handle, try

    element.set('123').send_keys('456') 

or

    element.send_keys('123').send_keys('456')

and see if that makes a difference for you

**Comment by raamonzera** [comment]
@twalpole 
During the tests I realized that the field is considering the points and ifens during the replace. This happens only on android devices.

**Comment by raamonzera** [comment]
During insertion of the text, the points are considered, however, they are not substituted, making the character intended for the point to be displayed in the field next to the point, however, the cursor remains one step earlier, making the sequence "456" Displayed "564".
Is it possible to ignore the point?
As a palatative solution, I increased 1 digit to the size of the field, because without this, the numbers were not even displayed when typed.
